using ILGPU;
using ILGPU.Runtime;
using System.Text.Json;

namespace SpawnDev.ILGPU.ML;

/// <summary>
/// Loads pre-extracted neural network weights from a flat binary blob + JSON manifest.
/// Weights are stored as FP16, converted to FP32 during GPU upload.
///
/// Binary format (generated by Python extract script):
///   weights_fp16.bin — contiguous FP16 values for all tensors
///   manifest_fp16.json — { "tensor_name": { offset, shape, elements, bytes, dtype } }
///
/// Future home: SpawnDev.ILGPU.ML
/// </summary>
public class WeightLoader
{
    private readonly Accelerator _accelerator;
    private readonly HttpClient _http;

    /// <summary>
    /// All weights in a single GPU buffer. Individual tensors accessed via Views.
    /// </summary>
    private MemoryBuffer1D<float, Stride1D.Dense>? _weightBuffer;

    /// <summary>Weight tensor views: name → (offset, length) into the single weight buffer.</summary>
    private Dictionary<string, (long offset, int length)> _tensorSlices = new();

    /// <summary>Shape metadata for each loaded tensor.</summary>
    public Dictionary<string, int[]> Shapes { get; } = new();

    public bool IsLoaded => _weightBuffer != null;
    public int TensorCount => _tensorSlices.Count;

    public WeightLoader(Accelerator accelerator, HttpClient http)
    {
        _accelerator = accelerator;
        _http = http;
    }

    /// <summary>
    /// Load all weights from the pre-extracted binary blob.
    /// Fetches manifest + blob via HTTP (chunked streaming), converts FP16→FP32, uploads to GPU.
    /// Reports progress through onProgress callback: ("download", 0-100), ("convert", 0-100), ("upload", 0-100).
    /// </summary>
    public async Task LoadAsync(string basePath = "models/dav3_weights", Action<string, int>? onProgress = null)
    {
        if (IsLoaded) return;

        var accelerator = _accelerator;
        var sw = System.Diagnostics.Stopwatch.StartNew();

        // Fetch manifest (small — direct download is fine)
        Console.WriteLine($"[WeightLoader] Loading manifest...");
        onProgress?.Invoke("manifest", 0);
        var manifestJson = await _http.GetStringAsync($"{basePath}/manifest_fp16.json");
        var manifest = JsonSerializer.Deserialize<Dictionary<string, TensorInfo>>(manifestJson)!;
        Console.WriteLine($"[WeightLoader] Manifest: {manifest.Count} tensors");
        onProgress?.Invoke("manifest", 100);

        // Fetch binary blob — chunked streaming to avoid OOM and keep UI responsive
        Console.WriteLine($"[WeightLoader] Downloading weight blob...");
        var blob = await InferenceSession.DownloadBytesChunkedAsync(_http, $"{basePath}/weights_fp16.bin", onProgress);
        Console.WriteLine($"[WeightLoader] Blob: {blob.Length / (1024.0 * 1024.0):F1} MB");

        // Convert all weights to one contiguous FP32 array, track offsets.
        // Each tensor is aligned to 64 floats (256 bytes) so SubViews don't
        // create overlapping binding ranges after WebGPU's 256-byte alignment.
        const int ALIGN_FLOATS = 64; // 256 bytes / 4 bytes per float
        Console.WriteLine($"[WeightLoader] Converting FP16 → FP32...");
        onProgress?.Invoke("convert", 0);
        int totalElements = manifest.Values.Sum(v => ((v.elements + ALIGN_FLOATS - 1) / ALIGN_FLOATS) * ALIGN_FLOATS);
        var allWeights = new float[totalElements];
        int currentOffset = 0;
        int tensorsDone = 0;
        int tensorCount = manifest.Count;
        int lastConvertPct = -1;

        foreach (var (name, info) in manifest)
        {
            // Ensure offset is 256-byte aligned (64 floats)
            currentOffset = ((currentOffset + ALIGN_FLOATS - 1) / ALIGN_FLOATS) * ALIGN_FLOATS;

            if (info.dtype == "fp16")
            {
                ConvertFp16ToFp32InPlace(blob, info.offset, info.elements, allWeights, currentOffset);
            }
            else
            {
                Buffer.BlockCopy(blob, info.offset, allWeights, currentOffset * 4, info.bytes);
            }

            _tensorSlices[name] = (currentOffset, info.elements);
            Shapes[name] = info.shape;
            currentOffset += info.elements;

            // Report conversion progress + yield to keep UI responsive
            tensorsDone++;
            int pct = tensorsDone * 100 / tensorCount;
            if (pct != lastConvertPct)
            {
                lastConvertPct = pct;
                onProgress?.Invoke("convert", pct);
            }
            if (tensorsDone % 50 == 0)
                await Task.Yield();
        }

        // Single GPU allocation + upload (avoids 340 separate Allocate1D calls)
        Console.WriteLine($"[WeightLoader] Uploading {totalElements:N0} params ({totalElements * 4 / (1024.0 * 1024.0):F1} MB FP32) as single buffer...");
        onProgress?.Invoke("upload", 0);
        _weightBuffer = accelerator.Allocate1D(allWeights);
        await accelerator.SynchronizeAsync();
        onProgress?.Invoke("upload", 100);

        sw.Stop();
        Console.WriteLine($"[WeightLoader] Loaded {_tensorSlices.Count} tensors in {sw.Elapsed.TotalSeconds:F1}s (1 GPU buffer)");
    }

    /// <summary>Get a weight tensor view by name. Returns a SubView into the single weight buffer.</summary>
    public ArrayView1D<float, Stride1D.Dense> GetView(string name)
    {
        if (_weightBuffer == null) throw new InvalidOperationException("Weights not loaded.");
        if (_tensorSlices.TryGetValue(name, out var slice))
            return _weightBuffer.View.SubView(slice.offset, slice.length);
        throw new KeyNotFoundException($"Weight tensor '{name}' not found. Available: {string.Join(", ", _tensorSlices.Keys.Take(5))}...");
    }

    /// <summary>Backwards compat: Get returns the full buffer (for APIs that need MemoryBuffer1D).</summary>
    public MemoryBuffer1D<float, Stride1D.Dense> Get(string name)
    {
        // For TransformerBlock.ResolveWeights which takes .View — redirect to the single buffer
        // This won't work correctly since it returns the whole buffer.
        // Use GetView instead.
        throw new NotSupportedException("Use GetView() instead of Get() — single buffer architecture.");
    }

    /// <summary>Try to get a weight tensor view. Returns null if not found.</summary>
    public ArrayView1D<float, Stride1D.Dense>? TryGetView(string name)
    {
        if (_weightBuffer == null) return null;
        if (_tensorSlices.TryGetValue(name, out var slice))
            return _weightBuffer.View.SubView(slice.offset, slice.length);
        return null;
    }

    /// <summary>Get the slice info (offset, length) for a named tensor.</summary>
    public (long offset, long length)? GetSlice(string name)
        => _tensorSlices.TryGetValue(name, out var slice) ? (slice.offset, slice.length) : null;

    /// <summary>Copy the entire master weight buffer to CPU. One-time operation for bulk weight extraction.</summary>
    public async Task<float[]> CopyAllToHostAsync()
    {
        if (_weightBuffer == null) throw new InvalidOperationException("Weights not loaded.");
        return await _weightBuffer.CopyToHostAsync<float>();
    }

    /// <summary>Get shape of a tensor.</summary>
    public int[] GetShape(string name) => Shapes[name];

    /// <summary>Dispose the single GPU weight buffer.</summary>
    public void DisposeWeights()
    {
        _weightBuffer?.Dispose();
        _weightBuffer = null;
        _tensorSlices.Clear();
        Shapes.Clear();
    }

    /// <summary>Print summary of loaded weights for debugging.</summary>
    public void PrintSummary(int maxEntries = 20)
    {
        var sorted = Shapes.OrderByDescending(kv => kv.Value.Aggregate(1, (a, b) => a * b)).ToList();
        Console.WriteLine($"[WeightLoader] {sorted.Count} tensors loaded:");
        foreach (var (name, shape) in sorted.Take(maxEntries))
        {
            int elements = shape.Aggregate(1, (a, b) => a * b);
            Console.WriteLine($"  {name}: [{string.Join(", ", shape)}] ({elements:N0} params)");
        }
        if (sorted.Count > maxEntries)
            Console.WriteLine($"  ... and {sorted.Count - maxEntries} more");
    }

    /// <summary>Convert FP16 bytes to FP32 into an existing array at a given offset.</summary>
    private static void ConvertFp16ToFp32InPlace(byte[] blob, int byteOffset, int elementCount, float[] dest, int destOffset)
    {
        for (int i = 0; i < elementCount; i++)
        {
            ushort fp16Bits = (ushort)(blob[byteOffset + i * 2] | (blob[byteOffset + i * 2 + 1] << 8));
            dest[destOffset + i] = HalfToFloat(fp16Bits);
        }
    }

    /// <summary>Convert IEEE 754 half-precision bits to single-precision float.</summary>
    private static float HalfToFloat(ushort h)
    {
        int sign = (h >> 15) & 1;
        int exp = (h >> 10) & 0x1F;
        int mant = h & 0x3FF;

        if (exp == 0)
        {
            if (mant == 0) return sign == 1 ? -0f : 0f; // Zero
            // Denormalized
            float val = mant / 1024f * MathF.Pow(2f, -14f);
            return sign == 1 ? -val : val;
        }
        if (exp == 31)
        {
            return mant == 0
                ? (sign == 1 ? float.NegativeInfinity : float.PositiveInfinity)
                : float.NaN;
        }

        // Normalized
        float result = (1f + mant / 1024f) * MathF.Pow(2f, exp - 15f);
        return sign == 1 ? -result : result;
    }

    private class TensorInfo
    {
        public int offset { get; set; }
        public int[] shape { get; set; } = [];
        public int elements { get; set; }
        public int bytes { get; set; }
        public string dtype { get; set; } = "fp16";
    }
}
