using ILGPU;
using ILGPU.Runtime;
using System.Net.Http;
using System.IO;
using System.Text.Json;

namespace SpawnDev.ILGPU.ML;

/// <summary>
/// Loads pre-extracted neural network weights from a flat binary blob + JSON manifest.
/// Weights are stored as FP16, converted to FP32 during GPU upload.
///
/// Binary format (generated by Python extract script):
///   weights_fp16.bin — contiguous FP16 values for all tensors
///   manifest_fp16.json — { "tensor_name": { offset, shape, elements, bytes, dtype } }
///
/// Future home: SpawnDev.ILGPU.ML
/// </summary>
public class WeightLoader
{
    private readonly Accelerator _accelerator;
    private readonly HttpClient _http;

    /// <summary>
    /// All weights in a single GPU buffer. Individual tensors accessed via Views.
    /// </summary>
    private MemoryBuffer1D<float, Stride1D.Dense>? _weightBuffer;

    /// <summary>Weight tensor views: name → (offset, length) into the single weight buffer.</summary>
    private Dictionary<string, (long offset, int length)> _tensorSlices = new();

    /// <summary>Shape metadata for each loaded tensor.</summary>
    public Dictionary<string, int[]> Shapes { get; } = new();

    public bool IsLoaded => _weightBuffer != null;
    public int TensorCount => _tensorSlices.Count;

    public WeightLoader(Accelerator accelerator, HttpClient http)
    {
        _accelerator = accelerator;
        _http = http;
    }

    /// <summary>
    /// Load all weights from the pre-extracted binary blob.
    /// Fetches manifest + blob via HTTP (chunked streaming), converts FP16→FP32, uploads to GPU.
    /// Reports progress through onProgress callback: ("download", 0-100), ("convert", 0-100), ("upload", 0-100).
    /// </summary>
    public async Task LoadAsync(string basePath = "models/dav3_weights", Action<string, int>? onProgress = null)
    {
        if (IsLoaded) return;

        var accelerator = _accelerator;
        var sw = System.Diagnostics.Stopwatch.StartNew();

        // Fetch manifest (small — direct download is fine)
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Loading manifest...");
        onProgress?.Invoke("manifest", 0);
        var manifestJson = await _http.GetStringAsync($"{basePath}/manifest_fp16.json");
        var manifest = JsonSerializer.Deserialize<Dictionary<string, TensorInfo>>(manifestJson)!;
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Manifest: {manifest.Count} tensors");
        onProgress?.Invoke("manifest", 100);

        // ⚠️ The weight blob is NEVER materialised as one managed byte[]. It used to be
        // (`DownloadBytesChunkedAsync` returns the whole file), which put a model-sized CONTIGUOUS array on
        // the single-threaded WASM heap - the allocation that still threw OutOfMemoryException after the
        // fp32 copy below was removed. It is the standing "browser bulk bytes stay in JS, never the .NET
        // managed heap" rule; a model-sized managed array has no business existing here at all.
        //
        // Tensors are read in FILE ORDER straight off the response stream and uploaded into their slice of
        // the GPU buffer as they arrive, so peak managed heap is ONE TENSOR - independent of model size.
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Streaming weight blob...");
        using var blobRequest = new HttpRequestMessage(HttpMethod.Get, $"{basePath}/weights_fp16.bin");
        // Without this the browser fetch handler buffers the ENTIRE body into the managed heap before the
        // first byte is readable, which defeats the streaming below. Same raw option key
        // DownloadBytesChunkedAsync uses, and a no-op off-browser.
        blobRequest.Options.Set(new HttpRequestOptionsKey<bool>("WebAssemblyEnableStreamingResponse"), true);
        using var blobResponse = await _http.SendAsync(blobRequest, HttpCompletionOption.ResponseHeadersRead);
        blobResponse.EnsureSuccessStatusCode();
        using var blobStream = await blobResponse.Content.ReadAsStreamAsync();

        // Convert all weights to one contiguous FP32 array, track offsets.
        // Each tensor is aligned to 64 floats (256 bytes) so SubViews don't
        // create overlapping binding ranges after WebGPU's 256-byte alignment.
        const int ALIGN_FLOATS = 64; // 256 bytes / 4 bytes per float
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Converting FP16 → FP32...");
        onProgress?.Invoke("convert", 0);
        int totalElements = manifest.Values.Sum(v => ((v.elements + ALIGN_FLOATS - 1) / ALIGN_FLOATS) * ALIGN_FLOATS);

        // ⚠️ The whole model used to be expanded into ONE `new float[totalElements]` here and uploaded at the
        // end, which meant the fp16 `blob` AND its fp32 expansion - about 3x the model - were live on the
        // single-threaded WASM managed heap AT THE SAME TIME. MEASURED: OutOfMemoryException loading
        // SqueezeNet in the Wasm lane. Peak heap scaled with MODEL SIZE, so it was a latent OOM for every
        // larger model, not a lane flake.
        //
        // The GPU buffer is now allocated up front and each tensor is converted and uploaded into its own
        // slice, so peak managed heap is `blob` + ONE TENSOR. Zeroed first because the 64-float alignment
        // leaves padding between tensors that no longer gets written; a zeroed device buffer keeps that
        // padding deterministic (it was implicitly zero when the host array was allocated) without costing
        // any host memory.
        _weightBuffer = accelerator.Allocate1D<float>(totalElements);
        _weightBuffer.MemSetToZero();
        int currentOffset = 0;
        int tensorsDone = 0;
        int tensorCount = manifest.Count;
        int lastConvertPct = -1;

        // FILE ORDER, so the response stream is read strictly forward - a stream cannot seek backwards, and
        // the manifest's dictionary order is not its byte order.
        long streamPos = 0;
        var skipScratch = new byte[64 * 1024];
        foreach (var (name, info) in manifest.OrderBy(kv => kv.Value.offset))
        {
            // Ensure offset is 256-byte aligned (64 floats)
            currentOffset = ((currentOffset + ALIGN_FLOATS - 1) / ALIGN_FLOATS) * ALIGN_FLOATS;

            // Discard any padding between the previous tensor and this one.
            while (streamPos < info.offset)
            {
                int want = (int)Math.Min(skipScratch.Length, info.offset - streamPos);
                int got = await blobStream.ReadAsync(skipScratch.AsMemory(0, want));
                if (got <= 0) throw new EndOfStreamException(
                    $"Weight blob ended while skipping to '{name}' at byte {info.offset} (read {streamPos}).");
                streamPos += got;
            }

            // Exact-size staging, uploaded immediately and collectable straight after - the established
            // SubView(...).CopyFromCPU(...) pattern used throughout this library.
            var raw = new byte[info.bytes];
            await blobStream.ReadExactlyAsync(raw.AsMemory(0, info.bytes));
            streamPos += info.bytes;

            var tensorFloats = new float[info.elements];
            if (info.dtype == "fp16")
            {
                ConvertFp16ToFp32InPlace(raw, 0, info.elements, tensorFloats, 0);
            }
            else
            {
                Buffer.BlockCopy(raw, 0, tensorFloats, 0, info.bytes);
            }
            if (info.elements > 0)
                _weightBuffer.View.SubView(currentOffset, info.elements).CopyFromCPU(tensorFloats);

            _tensorSlices[name] = (currentOffset, info.elements);
            Shapes[name] = info.shape;
            currentOffset += info.elements;

            // Report conversion progress + yield to keep UI responsive
            tensorsDone++;
            int pct = tensorsDone * 100 / tensorCount;
            if (pct != lastConvertPct)
            {
                lastConvertPct = pct;
                onProgress?.Invoke("convert", pct);
            }
            if (tensorsDone % 50 == 0)
                await Task.Yield();
        }

        // Still ONE GPU buffer (not 340 Allocate1D calls) - it was allocated before the loop and filled
        // slice by slice, so there is nothing left to upload here beyond draining the queued writes.
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Uploaded {totalElements:N0} params ({totalElements * 4 / (1024.0 * 1024.0):F1} MB FP32) as single buffer...");
        onProgress?.Invoke("upload", 0);
        await accelerator.SynchronizeAsync();
        onProgress?.Invoke("upload", 100);

        sw.Stop();
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] Loaded {_tensorSlices.Count} tensors in {sw.Elapsed.TotalSeconds:F1}s (1 GPU buffer)");
    }

    /// <summary>Get a weight tensor view by name. Returns a SubView into the single weight buffer.</summary>
    public ArrayView1D<float, Stride1D.Dense> GetView(string name)
    {
        if (_weightBuffer == null) throw new InvalidOperationException("Weights not loaded.");
        if (_tensorSlices.TryGetValue(name, out var slice))
            return _weightBuffer.View.SubView(slice.offset, slice.length);
        throw new KeyNotFoundException($"Weight tensor '{name}' not found. Available: {string.Join(", ", _tensorSlices.Keys.Take(5))}...");
    }

    /// <summary>Backwards compat: Get returns the full buffer (for APIs that need MemoryBuffer1D).</summary>
    public MemoryBuffer1D<float, Stride1D.Dense> Get(string name)
    {
        // For TransformerBlock.ResolveWeights which takes .View — redirect to the single buffer
        // This won't work correctly since it returns the whole buffer.
        // Use GetView instead.
        throw new NotSupportedException("Use GetView() instead of Get() — single buffer architecture.");
    }

    /// <summary>Try to get a weight tensor view. Returns null if not found.</summary>
    public ArrayView1D<float, Stride1D.Dense>? TryGetView(string name)
    {
        if (_weightBuffer == null) return null;
        if (_tensorSlices.TryGetValue(name, out var slice))
            return _weightBuffer.View.SubView(slice.offset, slice.length);
        return null;
    }

    /// <summary>Get the slice info (offset, length) for a named tensor.</summary>
    public (long offset, long length)? GetSlice(string name)
        => _tensorSlices.TryGetValue(name, out var slice) ? (slice.offset, slice.length) : null;

    // ⚠️ REMOVED: CopyAllToHostAsync() - "copy the entire master weight buffer to CPU".
    //
    // Its only caller staged Wasm/WebGL weights through it, which put THE WHOLE MODEL on the single-threaded
    // WASM managed heap and threw OutOfMemoryException in TypedArray.ReadBytes on a model as small as
    // SqueezeNet. Peak heap scaled with model size, so it was a latent OOM for every larger model.
    //
    // There is no safe caller for a whole-model host copy in this library. Read the slice you need instead -
    // `GetView(name).CopyToHostAsync()` is a real partial readback on every backend (Wasm: a
    // SharedArrayBuffer slice), so peak heap is one tensor rather than one model.

    /// <summary>Get shape of a tensor.</summary>
    public int[] GetShape(string name) => Shapes[name];

    /// <summary>Dispose the single GPU weight buffer.</summary>
    public void DisposeWeights()
    {
        _weightBuffer?.Dispose();
        _weightBuffer = null;
        _tensorSlices.Clear();
        Shapes.Clear();
    }

    /// <summary>Print summary of loaded weights for debugging.</summary>
    public void PrintSummary(int maxEntries = 20)
    {
        var sorted = Shapes.OrderByDescending(kv => kv.Value.Aggregate(1, (a, b) => a * b)).ToList();
        if (InferenceSession.VerboseLogging) Console.WriteLine($"[WeightLoader] {sorted.Count} tensors loaded:");
        foreach (var (name, shape) in sorted.Take(maxEntries))
        {
            int elements = shape.Aggregate(1, (a, b) => a * b);
            if (InferenceSession.VerboseLogging) Console.WriteLine($"  {name}: [{string.Join(", ", shape)}] ({elements:N0} params)");
        }
        if (sorted.Count > maxEntries)
            if (InferenceSession.VerboseLogging) Console.WriteLine($"  ... and {sorted.Count - maxEntries} more");
    }

    /// <summary>Convert FP16 bytes to FP32 into an existing array at a given offset.</summary>
    private static void ConvertFp16ToFp32InPlace(byte[] blob, int byteOffset, int elementCount, float[] dest, int destOffset)
    {
        for (int i = 0; i < elementCount; i++)
        {
            ushort fp16Bits = (ushort)(blob[byteOffset + i * 2] | (blob[byteOffset + i * 2 + 1] << 8));
            dest[destOffset + i] = HalfToFloat(fp16Bits);
        }
    }

    /// <summary>Convert IEEE 754 half-precision bits to single-precision float.</summary>
    private static float HalfToFloat(ushort h)
    {
        int sign = (h >> 15) & 1;
        int exp = (h >> 10) & 0x1F;
        int mant = h & 0x3FF;

        if (exp == 0)
        {
            if (mant == 0) return sign == 1 ? -0f : 0f; // Zero
            // Denormalized
            float val = mant / 1024f * MathF.Pow(2f, -14f);
            return sign == 1 ? -val : val;
        }
        if (exp == 31)
        {
            return mant == 0
                ? (sign == 1 ? float.NegativeInfinity : float.PositiveInfinity)
                : float.NaN;
        }

        // Normalized
        float result = (1f + mant / 1024f) * MathF.Pow(2f, exp - 15f);
        return sign == 1 ? -result : result;
    }

    private class TensorInfo
    {
        public int offset { get; set; }
        public int[] shape { get; set; } = [];
        public int elements { get; set; }
        public int bytes { get; set; }
        public string dtype { get; set; } = "fp16";
    }
}
