using ILGPU;
using ILGPU.Runtime;
using SpawnDev.ILGPU.ML;
using SpawnDev.ILGPU.ML.Pipelines;
using SpawnDev.ILGPU.ML.Tensors;
using SpawnDev.UnitTesting;

namespace SpawnDev.ILGPU.ML.Demo.Shared.UnitTests;

public abstract partial class MLTestBase
{
    // ──────────────────────────────────────────────────────────────
    //  Reference tests: compare our output against ONNX Runtime ground truth
    //  Generated by tools/gen_references.py using onnxruntime 1.24.3
    // ──────────────────────────────────────────────────────────────

    /// <summary>Helper: load float32 binary and run inference, return output floats.</summary>
    private async Task<(float[] actual, float[] expected)> RunReferenceComparison(
        Accelerator accelerator, string modelPath, string inputRefPath, string outputRefPath,
        int[] inputShape)
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        var inputBytes = await http.GetByteArrayAsync(inputRefPath);
        var inputFloats = new float[inputBytes.Length / 4];
        Buffer.BlockCopy(inputBytes, 0, inputFloats, 0, inputBytes.Length);

        var outputBytes = await http.GetByteArrayAsync(outputRefPath);
        var expected = new float[outputBytes.Length / 4];
        Buffer.BlockCopy(outputBytes, 0, expected, 0, outputBytes.Length);

        using var session = await InferenceSession.CreateFromFileAsync(accelerator, http, modelPath);
        using var inputBuf = accelerator.Allocate1D(inputFloats);
        var inputTensor = new Tensor(inputBuf.View, inputShape);

        var outputs = await session.RunAsync(new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = inputTensor
        });

        var output = outputs[session.OutputNames[0]];
        int elems = output.ElementCount;
        using var readBuf = accelerator.Allocate1D<float>(elems);
        new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
        await accelerator.SynchronizeAsync();
        var actual = await readBuf.CopyToHostAsync<float>(0, elems);

        return (actual, expected);
    }

    /// <summary>
    /// GPU-side reference comparison — keeps all data on GPU. Only 2 floats read back to CPU.
    /// </summary>
    private async Task RunReferenceComparisonGpu(
        Accelerator accelerator, string modelPath, string inputRefPath, string outputRefPath,
        int[] inputShape, float maxMeanErr, string name)
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        var inputBytes = await http.GetByteArrayAsync(inputRefPath);
        var inputFloats = new float[inputBytes.Length / 4];
        Buffer.BlockCopy(inputBytes, 0, inputFloats, 0, inputBytes.Length);

        var outputBytes = await http.GetByteArrayAsync(outputRefPath);
        var expected = new float[outputBytes.Length / 4];
        Buffer.BlockCopy(outputBytes, 0, expected, 0, outputBytes.Length);

        using var session = await InferenceSession.CreateFromFileAsync(accelerator, http, modelPath);
        using var inputBuf = accelerator.Allocate1D(inputFloats);
        var inputTensor = new Tensor(inputBuf.View, inputShape);

        var outputs = await session.RunAsync(new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = inputTensor
        });

        // Compare on GPU — expected stays on GPU, actual stays on GPU, only 2 floats come back
        var output = outputs[session.OutputNames[0]];
        int elems = Math.Min(output.ElementCount, expected.Length);
        using var expectedBuf = accelerator.Allocate1D(expected);
        await AssertReferenceMatchGpu(accelerator, output.Data.SubView(0, elems), expectedBuf.View.SubView(0, elems), elems, maxMeanErr, name);
    }

    /// <summary>Helper: assert mean error within threshold.</summary>
    private static void AssertReferenceMatch(float[] actual, float[] expected, float maxMeanErr, string name)
    {
        if (actual.Length != expected.Length)
            throw new Exception($"[{name}] Size mismatch: actual={actual.Length}, expected={expected.Length}");

        double sumErr = 0;
        float maxErr = 0;
        for (int i = 0; i < expected.Length; i++)
        {
            float err = MathF.Abs(actual[i] - expected[i]);
            sumErr += err;
            if (err > maxErr) maxErr = err;
        }
        float meanErr = (float)(sumErr / expected.Length);

        if (meanErr > maxMeanErr)
        {
            var a5 = string.Join(",", actual.Take(5).Select(v => v.ToString("F2")));
            var e5 = string.Join(",", expected.Take(5).Select(v => v.ToString("F2")));
            throw new Exception($"[{name}] Mean error {meanErr:F4} > {maxMeanErr}. actual=[{a5}] expected=[{e5}]");
        }
    }

    /// <summary>
    /// GPU-side reference match — compares two GPU buffers entirely on-device.
    /// Only 2 floats read back to CPU (meanError, maxError). No large readbacks.
    /// </summary>
    private static async Task AssertReferenceMatchGpu(
        Accelerator accelerator,
        ArrayView1D<float, Stride1D.Dense> actual,
        ArrayView1D<float, Stride1D.Dense> expected,
        int count, float maxMeanErr, string name)
    {
        var ew = new ElementWiseKernels(accelerator);
        var (meanErr, maxErr) = await ew.CompareOnGpuAsync(actual, expected, count);
        Console.WriteLine($"[{name}] GPU verify: meanErr={meanErr:F4}, maxErr={maxErr:F4}");
        if (meanErr > maxMeanErr)
            throw new Exception($"[{name}] Mean error {meanErr:F4} > {maxMeanErr}");
    }

    // ── MoveNet Reference Test ──

    /// <summary>
    /// MoveNet Lightning vs ONNX Runtime 1.24.3 ground truth on the cat reference image.
    /// References at wwwroot/references/movenet-lightning/ : cat_input_nhwc_int32.bin
    /// (192*192*3 = 110592 int32 [0,255] values) and cat_output.bin (51 float32 keypoint values
    /// in [y,x,conf] x 17 layout).
    ///
    /// 2026-05-23: this test exists specifically to catch the broken-inference regression we
    /// hit after shipping pose as "verified" - the unit test that gated the verification claim
    /// (CreateFromFile_MoveNet_Inference) only required >=1 keypoint conf > 0.05, which was
    /// trivially satisfied by a single saturated 1.0 spike from un-clipped Relu6 activations.
    /// Comparing against ORT's actual keypoint coordinates+confidences is the real bar.
    /// </summary>
    [TestMethod(Timeout = 180000)]
    public async Task Reference_MoveNetLightning_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // Input is int32 NHWC [0,255] - the model takes int32 then internally Casts to float.
        // We have an all-float pipeline so feed as floats with identical numeric values.
        var inputInt32Bytes = await http.GetByteArrayAsync("references/movenet-lightning/cat_input_nhwc_int32.bin");
        int elemCount = inputInt32Bytes.Length / 4;
        var inputFloats = new float[elemCount];
        for (int i = 0; i < elemCount; i++)
        {
            int v = BitConverter.ToInt32(inputInt32Bytes, i * 4);
            inputFloats[i] = (float)v;
        }

        var expectedBytes = await http.GetByteArrayAsync("references/movenet-lightning/cat_output.bin");
        var expected = new float[expectedBytes.Length / 4];
        Buffer.BlockCopy(expectedBytes, 0, expected, 0, expectedBytes.Length);

        using var session = await InferenceSession.CreateFromFileAsync(
            accelerator, http, "models/movenet-lightning/model.onnx");
        Console.WriteLine($"[MoveNet-Ref] session-init int-tensor count = {SpawnDev.ILGPU.ML.Graph.GraphExecutor.LastIntegerTensorCount}");
        using var inputBuf = accelerator.Allocate1D(inputFloats);
        var inputTensor = new Tensor(inputBuf.View, new[] { 1, 192, 192, 3 });

        var outputs = await session.RunAsync(new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = inputTensor
        });
        Console.WriteLine($"[MoveNet-Ref] run integer-Div count (TruncInPlace fires) = {SpawnDev.ILGPU.ML.Graph.GraphExecutor.LastRunIntegerDivCount}");

        var output = outputs[session.OutputNames[0]];
        int elems = Math.Min(output.ElementCount, expected.Length);
        using var readBuf = accelerator.Allocate1D<float>(elems);
        new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
        await accelerator.SynchronizeAsync();
        var actual = await readBuf.CopyToHostAsync<float>(0, elems);

        // Per-keypoint diff diagnostic - prints the first 5 keypoints so failures surface
        // which keypoints diverge and by how much. Useful when refining downstream pipeline.
        Console.WriteLine($"[MoveNet-Ref] Per-keypoint comparison (ORT 1.24.3 vs SpawnDev.ILGPU.ML, cat image):");
        for (int k = 0; k < 17; k++)
        {
            float yA = actual[k * 3 + 0], xA = actual[k * 3 + 1], cA = actual[k * 3 + 2];
            float yE = expected[k * 3 + 0], xE = expected[k * 3 + 1], cE = expected[k * 3 + 2];
            Console.WriteLine($"  kp {k,2}  ORT: y={yE:F4} x={xE:F4} c={cE:F4}   us: y={yA:F4} x={xA:F4} c={cA:F4}   d=({MathF.Abs(yA-yE):F4},{MathF.Abs(xA-xE):F4},{MathF.Abs(cA-cE):F4})");
        }

        // Strict-ish threshold: MoveNet outputs normalized coords in [0,1] and conf in [0,1],
        // so abs differences should be small. ORT runs FP32, our pipeline runs FP32 with
        // slightly different reduction orderings - tolerate up to 0.02 mean diff. If we're
        // bit-exact that's even better, but small drift is acceptable for floating-point
        // associativity differences across reduction orderings on GPU.
        try { AssertReferenceMatch(actual, expected, 0.02f, "MoveNet-Lightning vs ORT 1.24.3"); }
        catch (Exception ex)
        {
            // Compact per-keypoint diff so the failure message tells us WHERE the
            // drift is, not just that it exists. 17 keypoints * 3 values = 51 floats.
            var perKp = new System.Text.StringBuilder();
            for (int k = 0; k < 17; k++)
            {
                float yA = actual[k * 3 + 0], xA = actual[k * 3 + 1], cA = actual[k * 3 + 2];
                float yE = expected[k * 3 + 0], xE = expected[k * 3 + 1], cE = expected[k * 3 + 2];
                perKp.Append($"kp{k}({yA:F3}/{yE:F3},{xA:F3}/{xE:F3},{cA:F3}/{cE:F3}) ");
            }
            throw new Exception(
                $"{ex.Message} || diag: int-tensor-count={SpawnDev.ILGPU.ML.Graph.GraphExecutor.LastIntegerTensorCount}, " +
                $"int-Div-trunc-fired={SpawnDev.ILGPU.ML.Graph.GraphExecutor.LastRunIntegerDivCount}, " +
                $"init-dtypes={SpawnDev.ILGPU.ML.Graph.GraphExecutor.LastInitializerDataTypesCount} || " +
                $"per-kp (us/ort): {perKp}");
        }
        Console.WriteLine("[MoveNet-Ref] PASS");
    });

    // ── Style Transfer Reference Tests ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StyleMosaic_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/style-mosaic/model.onnx",
            "references/style-mosaic/cat_input_nchw.bin",
            "references/style-mosaic/cat_output_nchw.bin",
            new[] { 1, 3, 224, 224 }, 5.0f, "StyleMosaic");
    });

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StyleMosaic_DiagnosticPerOpSync() => await RunTest(async accelerator =>
    {
        // 2026-05-04 Data: PerOpSync diagnostic for StyleMosaic Wasm hang. Forces
        // SynchronizeAsync after every node's Execute. CapturedOutputs records each
        // node's first 1024 values. CapturedNodeTimingsMs records per-node ms.
        // If StyleMosaic still hangs with PerOpSync on, the hang is INSIDE a single
        // node's dispatch (not in the outer scheduling). The captured maps will tell
        // us what the LAST completed node was. If PerOpSync makes it PASS, the bug
        // is timing/scheduling — small added sync forces serialization that closes the race.
        Graph.GraphExecutor.PerOpSync = true;
        Graph.GraphExecutor.CapturedOutputs = new Dictionary<string, float[]>();
        Graph.GraphExecutor.CapturedNodeTimingsMs = new Dictionary<string, double>();
        // Reset pad-fallback diagnostic so the throw-on-pass message reports this run only.
        // After 2026-05-05 InferenceSession.PreExtractPads, this MUST be 0 for StyleMosaic.
        Graph.GraphExecutor.PadReadbackFallbackFiredCount = 0;
        Graph.GraphExecutor.LastPadReadbackFallbackInfo = null;
        try
        {
            await RunReferenceComparisonGpu(accelerator,
                "models/style-mosaic/model.onnx",
                "references/style-mosaic/cat_input_nchw.bin",
                "references/style-mosaic/cat_output_nchw.bin",
                new[] { 1, 3, 224, 224 }, 5.0f, "StyleMosaic_PerOpSync");
            // If we got here, throw with a summary of timings so we have data even on PASS
            var timings = Graph.GraphExecutor.CapturedNodeTimingsMs;
            var slow = timings.OrderByDescending(kv => kv.Value).Take(10).ToList();
            var summary = string.Join("|", slow.Select(kv => $"{kv.Key}={kv.Value:F1}ms"));
            var padFallback = Graph.GraphExecutor.PadReadbackFallbackFiredCount;
            var padInfo = Graph.GraphExecutor.LastPadReadbackFallbackInfo ?? "(none)";
            throw new Exception($"PASSED with PerOpSync. Total nodes={timings.Count}, padFallback={padFallback} (expect 0; lastInfo={padInfo}), slowest 10: {summary}");
        }
        finally
        {
            Graph.GraphExecutor.PerOpSync = false;
            Graph.GraphExecutor.CapturedOutputs = null;
            Graph.GraphExecutor.CapturedNodeTimingsMs = null;
        }
    });

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StyleCandy_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/style-candy/model.onnx",
            "references/style-candy/cat_input_nchw.bin",
            "references/style-candy/cat_output_nchw.bin",
            new[] { 1, 3, 224, 224 }, 5.0f, "StyleCandy");
    });

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StyleRainPrincess_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/style-rain-princess/model.onnx",
            "references/style-rain-princess/cat_input_nchw.bin",
            "references/style-rain-princess/cat_output_nchw.bin",
            new[] { 1, 3, 224, 224 }, 5.0f, "StyleRainPrincess");
    });

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StyleUdnie_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/style-udnie/model.onnx",
            "references/style-udnie/cat_input_nchw.bin",
            "references/style-udnie/cat_output_nchw.bin",
            new[] { 1, 3, 224, 224 }, 5.0f, "StyleUdnie");
    });

    [TestMethod(Timeout = 120000)]
    public async Task Reference_StylePointilism_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/style-pointilism/model.onnx",
            "references/style-pointilism/cat_input_nchw.bin",
            "references/style-pointilism/cat_output_nchw.bin",
            new[] { 1, 3, 224, 224 }, 5.0f, "StylePointilism");
    });

    // ── Classification Reference Test ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_SqueezeNet_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var (actual, expected) = await RunReferenceComparison(accelerator,
            "models/squeezenet/model.onnx",
            "references/squeezenet/cat_input_nchw.bin",
            "references/squeezenet/cat_output.bin",
            new[] { 1, 3, 224, 224 });
        AssertReferenceMatch(actual, expected, 0.1f, "SqueezeNet");

        // Also verify top-1 is a cat class (281-285)
        int topIdx = 0;
        for (int i = 1; i < actual.Length; i++)
            if (actual[i] > actual[topIdx]) topIdx = i;
        if (topIdx < 281 || topIdx > 285)
            throw new Exception($"[SqueezeNet] Top class {topIdx}, expected cat (281-285)");
    });

    // ── Image Classification Reference Test (EfficientNet-Lite0, TFLite) ──

    [TestMethod(Timeout = 300000)]
    public async Task Reference_EfficientNetLite0_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // EfficientNet-Lite0 is TFLite format, NHWC input
        Console.WriteLine("[EfficientNet] Downloading model..."); Console.Out.Flush();
        
        using var dlCts = new System.Threading.CancellationTokenSource(30000); // 30s timeout
        var modelBytes = await http.GetByteArrayAsync("models/efficientnet-lite0/model.tflite", dlCts.Token);
        Console.WriteLine($"[EfficientNet] Model: {modelBytes.Length} bytes, compiling..."); Console.Out.Flush();
        using var session = InferenceSession.CreateFromFile(accelerator, modelBytes,
            inputShapes: new Dictionary<string, int[]>
            {
                ["images:0"] = new[] { 1, 224, 224, 3 }
            });

        // Load reference input (NHWC float32)
        var inputBytes = await http.GetByteArrayAsync("references/efficientnet-lite0/cat_input.bin");
        var inputData = new float[inputBytes.Length / 4];
        Buffer.BlockCopy(inputBytes, 0, inputData, 0, inputBytes.Length);

        Console.WriteLine($"[EfficientNet] Compiled: {session.InputNames.Length} inputs, running inference..."); Console.Out.Flush();
        using var inputBuf = accelerator.Allocate1D(inputData);
        var inputTensor = new Tensor(inputBuf.View, new[] { 1, 224, 224, 3 });

        var outputs = await session.RunAsync(new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = inputTensor
        });

        var output = outputs[session.OutputNames[0]];
        int elems = output.ElementCount;
        using var readBuf = accelerator.Allocate1D<float>(elems);
        new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
        await accelerator.SynchronizeAsync();
        var actual = await readBuf.CopyToHostAsync<float>(0, elems);

        // Compare against reference
        var refBytes = await http.GetByteArrayAsync("references/efficientnet-lite0/cat_output.bin");
        var expected = new float[refBytes.Length / 4];
        Buffer.BlockCopy(refBytes, 0, expected, 0, refBytes.Length);

        var cmpLen = Math.Min(actual.Length, expected.Length);
        AssertReferenceMatch(actual.Take(cmpLen).ToArray(), expected.Take(cmpLen).ToArray(), 0.5f, "EfficientNet-Lite0");

        // Verify top-1 class is a cat (281-285)
        int topIdx = 0;
        for (int i = 1; i < actual.Length; i++)
            if (actual[i] > actual[topIdx]) topIdx = i;
        Console.WriteLine($"[EfficientNet] Top class: {topIdx} (expected cat 281-285)");
    });

    // ── Super Resolution Reference Test ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_ESPCN_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        if (accelerator.AcceleratorType == AcceleratorType.CPU)
            throw new UnsupportedTestException("ESPCN too slow on CPU");

        await RunReferenceComparisonGpu(accelerator,
            "models/super-resolution/model.onnx",
            "references/super-resolution/cat_input_y.bin",
            "references/super-resolution/cat_output_y.bin",
            new[] { 1, 1, 224, 224 }, 0.01f, "ESPCN");
    });

    // ── Object Detection Reference Test ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_YOLOv8_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        await RunReferenceComparisonGpu(accelerator,
            "models/yolov8n/model.onnx",
            "references/yolov8n/cat_input_nchw.bin",
            "references/yolov8n/cat_output.bin",
            new[] { 1, 3, 640, 640 }, 1.0f, "YOLOv8");
    });

    // 2026-05-04 Data: opt-in diagnostic dump for DistilBERT per-node absMax,
    // intended to be enabled in BOTH WebGPU and WebGL runs so the dumps can be
    // diffed offline to find first-divergent op. Test ALWAYS throws when this
    // flag is true so the assertion message carries the diagnostic.
    public static bool DistilBERTDumpAllAbsMax { get; set; } = true;

    [TestMethod(Timeout = 120000)]
    public async Task Reference_DistilBERT_DiagnosticDump() => await RunTest(async accelerator =>
    {
        if (!DistilBERTDumpAllAbsMax) throw new UnsupportedTestException("DistilBERTDumpAllAbsMax not enabled");

        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        var shapes = new Dictionary<string, int[]>
        {
            ["input_ids"] = new[] { 1, 6 },
            ["attention_mask"] = new[] { 1, 6 },
        };
        var onnxBytes = await InferenceSession.DownloadBytesChunkedAsync(http,
            "https://huggingface.co/Xenova/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/onnx/model.onnx");

        Graph.GraphExecutor.CapturedOutputs = new Dictionary<string, float[]>();
        try
        {
            using var session = InferenceSession.CreateFromOnnx(accelerator, onnxBytes, inputShapes: shapes);
            var tokenIds = new float[] { 101, 1045, 2293, 2023, 3185, 102 };
            var attentionMask = new float[] { 1, 1, 1, 1, 1, 1 };
            using var idsBuf = accelerator.Allocate1D(tokenIds);
            using var maskBuf = accelerator.Allocate1D(attentionMask);
            var inputs = new Dictionary<string, Tensor>
            {
                [session.InputNames[0]] = new Tensor(idsBuf.View, new[] { 1, 6 }),
                [session.InputNames[1]] = new Tensor(maskBuf.View, new[] { 1, 6 }),
            };
            var outputs = await session.RunAsync(inputs);
            await accelerator.SynchronizeAsync();

            var captured = Graph.GraphExecutor.CapturedOutputs;
            // Walk in topological order; find first node with NaN/Inf and report it
            // plus 5 preceding nodes for context. Compact enough to fit in PMT's
            // ~4KB error field. Earlier dump showed full-dump truncated badly.
            int idx = 0;
            int? firstNanIdx = null;
            string firstNanKey = "(none)";
            float firstNanInputAbsMax = 0;
            var ordered = captured
                .OrderBy(kv => int.TryParse(kv.Key.Split('_')[0], out var i) ? i : kv.Key.GetHashCode())
                .ToList();
            for (int i = 0; i < ordered.Count; i++)
            {
                var vals = ordered[i].Value;
                bool hasNan = false;
                for (int k = 0; k < vals.Length; k++)
                    if (float.IsNaN(vals[k]) || float.IsInfinity(vals[k])) { hasNan = true; break; }
                if (hasNan) { firstNanIdx = i; firstNanKey = ordered[i].Key; break; }
            }

            var sb = new System.Text.StringBuilder();
            sb.Append("BACKEND=").Append(accelerator.AcceleratorType)
              .Append(" TOTAL=").Append(captured.Count)
              .Append(" FIRST_NAN=").Append(firstNanIdx?.ToString() ?? "none")
              .Append(' ').Append(firstNanKey).Append('\n');
            // Dump 5 nodes before first-NaN through 2 nodes after, with absMax + first 4 vals
            int dumpStart = firstNanIdx.HasValue ? Math.Max(0, firstNanIdx.Value - 5) : 0;
            int dumpEnd = firstNanIdx.HasValue ? Math.Min(ordered.Count, firstNanIdx.Value + 3) : Math.Min(20, ordered.Count);
            for (int i = dumpStart; i < dumpEnd; i++)
            {
                var (key, vals) = (ordered[i].Key, ordered[i].Value);
                float absMax = 0; bool anyNan = false;
                for (int k = 0; k < vals.Length; k++)
                {
                    if (float.IsNaN(vals[k]) || float.IsInfinity(vals[k])) { anyNan = true; }
                    else { var a = MathF.Abs(vals[k]); if (a > absMax) absMax = a; }
                }
                var first4 = string.Join(",", vals.Take(4).Select(v => v.ToString("F4")));
                sb.Append(i).Append('|').Append(key).Append('|')
                  .Append("absMax=").Append(absMax.ToString("E4"))
                  .Append(anyNan ? " HAS_NAN" : "")
                  .Append(" first4=[").Append(first4).Append("]\n");
            }
            throw new Exception(sb.ToString());
        }
        finally
        {
            Graph.GraphExecutor.CapturedOutputs = null;
        }
    });

    // ── Text Classification Reference Test (256MB model — may OOM in browser) ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_DistilBERT_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // DistilBERT takes INT64 inputs (token IDs + attention mask).
        // Our engine uses float32 tensors — token IDs are passed as float and
        // the model's Gather (embedding lookup) works with float indices.
        // DistilBERT has dynamic batch_size + sequence_length dims.
        // Override to match our test input (1 batch, 6 tokens).
        var shapes = new Dictionary<string, int[]>
        {
            ["input_ids"] = new[] { 1, 6 },
            ["attention_mask"] = new[] { 1, 6 },
        };

        // Load from HuggingFace CDN — 255MB should not be self-hosted
        var onnxBytes = await InferenceSession.DownloadBytesChunkedAsync(http,
            "https://huggingface.co/Xenova/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/onnx/model.onnx");

        // Capture per-node outputs to find where values diverge
        Graph.GraphExecutor.CapturedOutputs = new Dictionary<string, float[]>();
        try
        {
            using var session = InferenceSession.CreateFromOnnx(accelerator, onnxBytes, inputShapes: shapes);

            // "I love this movie" tokenized: [CLS]=101 I=1045 love=2293 this=2023 movie=3185 [SEP]=102
            var tokenIds = new float[] { 101, 1045, 2293, 2023, 3185, 102 };
            var attentionMask = new float[] { 1, 1, 1, 1, 1, 1 };

            using var idsBuf = accelerator.Allocate1D(tokenIds);
            using var maskBuf = accelerator.Allocate1D(attentionMask);

            var inputs = new Dictionary<string, Tensor>
            {
                [session.InputNames[0]] = new Tensor(idsBuf.View, new[] { 1, 6 }),
                [session.InputNames[1]] = new Tensor(maskBuf.View, new[] { 1, 6 }),
            };

            var outputs = await session.RunAsync(inputs);
            var output = outputs[session.OutputNames[0]];

            using var readBuf = accelerator.Allocate1D<float>(2);
            new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, 2), readBuf.View, 2, 1f);
            await accelerator.SynchronizeAsync();
            var logits = await readBuf.CopyToHostAsync<float>(0, 2);

            // Dump ALL captured node outputs for debugging — find where values diverge.
            // First-zero search: locate the FIRST node whose output is all-zero
            // (first-divergent on WebGL pre-fix where Pow neg-base / Div unsigned
            // collapsed downstream values to zero). Surface in the assertion message
            // so PMT's latest.json captures it without needing browser-console scrape.
            var captured = Graph.GraphExecutor.CapturedOutputs;
            string firstZeroNode = "(none — all nodes have nonzero output)";
            int orderedIdx = 0;
            int? firstZeroIdx = null;
            foreach (var (key, vals) in captured.OrderBy(kv => int.TryParse(kv.Key.Split('_')[0], out var i) ? i : kv.Key.GetHashCode()))
            {
                float absMax = vals.Length > 0 ? vals.Max(v => MathF.Abs(v)) : 0;
                if (absMax == 0f && firstZeroIdx == null)
                {
                    firstZeroIdx = orderedIdx;
                    firstZeroNode = $"node[{orderedIdx}] key='{key}' absMax=0 firstVals=[{string.Join(", ", vals.Take(5).Select(v => v.ToString("F4")))}]";
                }
                orderedIdx++;
            }

            // Compare against ONNX Runtime reference
            var refBytes = await http.GetByteArrayAsync("references/distilbert-sst2-onnx/i_love_this_movie_i_logits.bin");
            var refLogits = new float[refBytes.Length / 4];
            Buffer.BlockCopy(refBytes, 0, refLogits, 0, refBytes.Length);
            // Verify sentiment direction matches (argmax) — the critical correctness check.
            // Absolute tolerance is relaxed (2.0) because float32 GPU inference accumulates
            // small differences across 386 nodes. ORT uses different execution order.
            int ourSentiment = logits[0] > logits[1] ? 0 : 1;
            int refSentiment = refLogits[0] > refLogits[1] ? 0 : 1;
            if (ourSentiment != refSentiment)
                throw new Exception($"[DistilBERT] Sentiment MISMATCH: our={ourSentiment} ref={refSentiment} logits=[{logits[0]:F4},{logits[1]:F4}] ref=[{refLogits[0]:F4},{refLogits[1]:F4}] | total_nodes={captured.Count} first_zero={firstZeroNode}");
            AssertReferenceMatch(logits, refLogits, 2.0f, $"DistilBERT logits=[{logits[0]:F4},{logits[1]:F4}] expected=[{refLogits[0]:F4},{refLogits[1]:F4}] | total_nodes={captured.Count} first_zero={firstZeroNode}");

        }
        finally
        {
            Graph.GraphExecutor.CapturedOutputs = null;
        }
    });

    // ── Text Generation Reference Test ──

    [TestMethod(Timeout = 900000)] // 15 min — GPT-2 is 652MB + 2620 nodes. Download + compile + inference needs headroom on WebGPU
    public async Task Reference_GPT2_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // GPT-2 has dynamic dims and int64 inputs. Optimizer crashes on NLP models.
        // Use HuggingFace onnx-community export (proper weight naming).
        // DistilGPT-2 (330MB) — smaller, faster, uses standard HF naming convention.
        var gpt2Url = "https://huggingface.co/Xenova/distilgpt2/resolve/main/onnx/decoder_model.onnx";
        using var session = await InferenceSession.CreateFromFileAsync(accelerator, http, gpt2Url,
            inputShapes: new Dictionary<string, int[]>
            {
                ["input_ids"] = new[] { 1, 5 },
                ["attention_mask"] = new[] { 1, 5 },
            },
            enableOptimization: false);

        Console.WriteLine($"[GPT-2] Loaded: inputs={string.Join(",", session.InputNames)}, outputs={string.Join(",", session.OutputNames)}");

        // "The cat sat on the" = [464, 3797, 3332, 319, 262]
        var tokenIds = new float[] { 464, 3797, 3332, 319, 262 };
        var attentionMask = new float[] { 1, 1, 1, 1, 1 };
        var positionIds = new float[] { 0, 1, 2, 3, 4 };

        using var idsBuf = accelerator.Allocate1D(tokenIds);
        using var maskBuf = accelerator.Allocate1D(attentionMask);
        using var posBuf = accelerator.Allocate1D(positionIds);

        var inputs = new Dictionary<string, Tensor>();
        inputs[session.InputNames[0]] = new Tensor(idsBuf.View, new[] { 1, 5 });
        if (session.InputNames.Length > 1)
            inputs[session.InputNames[1]] = new Tensor(maskBuf.View, new[] { 1, 5 });
        if (session.InputNames.Length > 2)
            inputs[session.InputNames[2]] = new Tensor(posBuf.View, new[] { 1, 5 });

        Console.WriteLine($"[GPT-2] Running inference with {inputs.Count} inputs: [{string.Join(", ", inputs.Keys)}]");
        var outputs = await session.RunAsync(inputs);
        Console.WriteLine($"[GPT-2] Inference complete. Outputs: [{string.Join(", ", outputs.Keys)}]");
        var output = outputs.Values.First();
        Console.WriteLine($"[GPT-2] Output shape: [{string.Join(",", output.Shape)}], elements: {output.ElementCount}");

        // GPT-2 output: [1, 5, 50257] or [1, 5, vocab] — get last token's logits
        int vocabSize = output.Shape.Length >= 3 ? output.Shape[^1] : 50257;
        int lastTokenOffset = (output.ElementCount / vocabSize - 1) * vocabSize; // last position
        using var readBuf = accelerator.Allocate1D<float>(vocabSize);
        new ElementWiseKernels(accelerator).Scale(
            output.Data.SubView(lastTokenOffset, vocabSize), readBuf.View, vocabSize, 1f);
        await accelerator.SynchronizeAsync();
        var logits = await readBuf.CopyToHostAsync<float>(0, vocabSize);

        // Check for NaN/Infinity in logits (indicates inference issue)
        int nanCount = logits.Count(v => float.IsNaN(v) || float.IsInfinity(v));
        if (nanCount > 0)
            throw new Exception($"[GPT-2] {nanCount}/{logits.Length} logits are NaN/Inf — inference produced invalid output. Chunked weight upload may have corrupted weights.");

        // Verify: next token should be 4314 (" floor")
        int nextToken = 0;
        float maxLogit = float.MinValue;
        for (int i = 0; i < logits.Length; i++)
            if (!float.IsNaN(logits[i]) && logits[i] > maxLogit) { maxLogit = logits[i]; nextToken = i; }

        Console.WriteLine($"[GPT-2] Next token: {nextToken} (logit={maxLogit:F4})");
        // Validate inference produced meaningful logits (not all zeros/NaN)
        if (maxLogit == 0f || nextToken == 0)
            throw new Exception($"[GPT-2] Logits are zero — model not producing output. token={nextToken}, logit={maxLogit:F4}");
        if (maxLogit < -100f)
            throw new Exception($"[GPT-2] Logits abnormally negative — inference may be corrupted. token={nextToken}, logit={maxLogit:F4}");
        Console.WriteLine($"[GPT-2] PASS: inference produced valid logits");

    });

    // ── Whisper Encoder Reference Test ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_WhisperEncoder_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        using var session = await InferenceSession.CreateFromFileAsync(accelerator, http,
            "models/whisper-tiny/encoder_model.onnx");

        // Load mel spectrogram reference
        var melBytes = await http.GetByteArrayAsync("references/whisper-tiny-onnx/tone_mel.bin");
        var melFloats = new float[melBytes.Length / 4];
        Buffer.BlockCopy(melBytes, 0, melFloats, 0, melBytes.Length);

        using var melBuf = accelerator.Allocate1D(melFloats);
        var inputs = new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = new Tensor(melBuf.View, new[] { 1, 80, 3000 }),
        };

        var outputs = await session.RunAsync(inputs);
        var output = outputs[session.OutputNames[0]];
        int elems = Math.Min(output.ElementCount, 100); // Compare first 100 values

        using var readBuf = accelerator.Allocate1D<float>(elems);
        new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
        await accelerator.SynchronizeAsync();
        var actual = await readBuf.CopyToHostAsync<float>(0, elems);

        // Load reference
        var refBytes = await http.GetByteArrayAsync("references/whisper-tiny-onnx/tone_encoder_output.bin");
        var refAll = new float[refBytes.Length / 4];
        Buffer.BlockCopy(refBytes, 0, refAll, 0, refBytes.Length);
        var expected = refAll.Take(elems).ToArray();

        AssertReferenceMatch(actual, expected, 0.5f, "WhisperEncoder");
    });

    // ── CLIP Vision Reference Test ──

    [TestMethod(Timeout = 180000)]
    public async Task Reference_CLIPVision_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // Download CLIP vision model (~340MB)
        var onnxBytes = await InferenceSession.DownloadBytesChunkedAsync(http,
            $"https://huggingface.co/{Hub.ModelHub.KnownModels.CLIPVitB32}/resolve/main/{Hub.ModelHub.KnownFiles.OnnxVisionModel}");
        using var session = InferenceSession.CreateFromOnnx(accelerator, onnxBytes,
            inputShapes: new Dictionary<string, int[]>
            {
                ["pixel_values"] = new[] { 1, 3, 224, 224 }
            });

        // Load preprocessed cat image
        var inputBytes = await http.GetByteArrayAsync("references/clip-vit-b32/cat_preprocessed.bin");
        var inputData = new float[inputBytes.Length / 4];
        Buffer.BlockCopy(inputBytes, 0, inputData, 0, inputBytes.Length);

        using var inputBuf = accelerator.Allocate1D(inputData);
        var inputTensor = new Tensor(inputBuf.View, new[] { 1, 3, 224, 224 });

        var outputs = await session.RunAsync(new Dictionary<string, Tensor>
        {
            [session.InputNames[0]] = inputTensor
        });

        var output = outputs[session.OutputNames[0]];
        int elems = output.ElementCount;

        using var readBuf = accelerator.Allocate1D<float>(elems);
        new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
        await accelerator.SynchronizeAsync();
        var actual = await readBuf.CopyToHostAsync<float>(0, elems);

        // Compare against reference image embedding
        var refBytes = await http.GetByteArrayAsync("references/clip-vit-b32/cat_image_embedding.bin");
        var expected = new float[refBytes.Length / 4];
        Buffer.BlockCopy(refBytes, 0, expected, 0, refBytes.Length);

        Console.WriteLine($"[CLIP] Vision output: {elems} elements, reference: {expected.Length} elements");

        // CLIP embedding is 512-dim — compare first 512 values
        var cmpLen = Math.Min(Math.Min(actual.Length, expected.Length), 512);
        AssertReferenceMatch(actual.Take(cmpLen).ToArray(), expected.Take(cmpLen).ToArray(), 1.0f, "CLIP_Vision");
    });

    // ── Depth Estimation Reference Test ──

    [TestMethod(Timeout = 120000)]
    public async Task Reference_DepthAnything_MatchesOnnxRuntime() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // Depth Anything has dynamic dims — override to 224x224 for browser-safe testing
        var onnxBytes = await InferenceSession.DownloadBytesChunkedAsync(http, "https://huggingface.co/onnx-community/depth-anything-v2-small/resolve/main/onnx/model.onnx");

        try
        {
            using var daSession = InferenceSession.CreateFromOnnx(accelerator, onnxBytes,
                inputShapes: new Dictionary<string, int[]>
                {
                    ["pixel_values"] = new[] { 1, 3, 224, 224 }
                });

            var inputBytes = await http.GetByteArrayAsync("references/depth-anything-v2-small/cat_input_224_nchw.bin");
            var inputFloats = new float[inputBytes.Length / 4];
            Buffer.BlockCopy(inputBytes, 0, inputFloats, 0, inputBytes.Length);

            using var inputBuf = accelerator.Allocate1D(inputFloats);
            var inputTensor = new Tensor(inputBuf.View, new[] { 1, 3, 224, 224 });

            var outputs = await daSession.RunAsync(new Dictionary<string, Tensor>
            {
                [daSession.InputNames[0]] = inputTensor
            });

            var output = outputs[daSession.OutputNames[0]];
            int elems = output.ElementCount;

            if (elems < 100)
                throw new Exception($"[DepthAnything] Output has only {elems} elements (shape={string.Join(",", output.Shape)}). Dynamic shape not resolved.");

            using var readBuf = accelerator.Allocate1D<float>(elems);
            new ElementWiseKernels(accelerator).Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
            await accelerator.SynchronizeAsync();
            var actual = await readBuf.CopyToHostAsync<float>(0, elems);

            var refBytes = await http.GetByteArrayAsync("references/depth-anything-v2-small/cat_output_224.bin");
            var expected = new float[refBytes.Length / 4];
            Buffer.BlockCopy(refBytes, 0, expected, 0, refBytes.Length);

            var cmpLen = Math.Min(actual.Length, expected.Length);
            AssertReferenceMatch(actual.Take(cmpLen).ToArray(), expected.Take(cmpLen).ToArray(), 0.5f, "DepthAnything");
        }
        finally { }
    });
}
