using ILGPU;
using ILGPU.Runtime;
using SpawnDev.ILGPU.ML;
using SpawnDev.ILGPU.ML.Operators;
using SpawnDev.ILGPU.ML.Tensors;
using SpawnDev.UnitTesting;
using System.Text.Json;

namespace SpawnDev.ILGPU.ML.Demo.Shared.UnitTests;

public abstract partial class MLTestBase
{
    // ──────────────────────────────────────────────────────────────
    //  Operator reference tests: numpy-verified exact-match cases.
    //  Data: operator_test_cases.json (18 cases, generated by Data)
    //  These catch broadcast bugs, pooling errors, and silent corruption.
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Run all 18 operator test cases from numpy reference data.
    /// Each case loads known inputs, runs the operator, and compares
    /// output element-by-element against numpy-verified expected values.
    /// </summary>
    [TestMethod(Timeout = 60000)]
    public async Task OperatorRef_AllCases_MatchNumpy() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        var json = await http.GetStringAsync("test-models/operator_test_cases.json");
        var cases = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json)!;

        var registry = new OperatorRegistry(accelerator);
        using var pool = new BufferPool(accelerator);
        int passed = 0;
        var failures = new List<string>();

        foreach (var (name, caseData) in cases)
        {
            try
            {
                var op = caseData.GetProperty("op").GetString()!;
                var expectedData = GetFloatArray(caseData.GetProperty("expected").GetProperty("data"));
                var expectedShape = GetIntArray(caseData.GetProperty("expected").GetProperty("shape"));

                // Resolve operator
                if (!registry.IsSupported(op))
                {
                    failures.Add($"{name}: operator '{op}' not registered");
                    continue;
                }
                var onnxOp = registry.Resolve(op);

                // Build inputs — handle various JSON layouts
                Tensor[] inputs;
                Dictionary<string, object> attrs = new();

                if (op == "Where" && caseData.TryGetProperty("condition", out var condElem))
                {
                    // Where: 3 inputs (condition, x, y)
                    var condData = GetFloatArray(condElem.GetProperty("data"));
                    var condShape = GetIntArray(condElem.GetProperty("shape"));
                    var xData = GetFloatArray(caseData.GetProperty("input_x").GetProperty("data"));
                    var xShape = GetIntArray(caseData.GetProperty("input_x").GetProperty("shape"));
                    var yData = GetFloatArray(caseData.GetProperty("input_y").GetProperty("data"));
                    var yShape = GetIntArray(caseData.GetProperty("input_y").GetProperty("shape"));
                    inputs = new[]
                    {
                        pool.AllocatePermanent(condData, condShape),
                        pool.AllocatePermanent(xData, xShape),
                        pool.AllocatePermanent(yData, yShape),
                    };
                }
                else if (caseData.TryGetProperty("input_a", out var inputA))
                {
                    var aData = GetFloatArray(inputA.GetProperty("data"));
                    var aShape = GetIntArray(inputA.GetProperty("shape"));
                    var bData = GetFloatArray(caseData.GetProperty("input_b").GetProperty("data"));
                    var bShape = GetIntArray(caseData.GetProperty("input_b").GetProperty("shape"));
                    var inputList = new List<Tensor>
                    {
                        pool.AllocatePermanent(aData, aShape),
                        pool.AllocatePermanent(bData, bShape),
                    };
                    // Handle 3+ inputs (e.g., 3-input Concat)
                    if (caseData.TryGetProperty("input_c", out var inputC))
                    {
                        var cData = GetFloatArray(inputC.GetProperty("data"));
                        var cShape = GetIntArray(inputC.GetProperty("shape"));
                        inputList.Add(pool.AllocatePermanent(cData, cShape));
                    }
                    inputs = inputList.ToArray();
                }
                else
                {
                    var inData = GetFloatArray(caseData.GetProperty("input").GetProperty("data"));
                    var inShape = GetIntArray(caseData.GetProperty("input").GetProperty("shape"));
                    var inputList = new List<Tensor> { pool.AllocatePermanent(inData, inShape) };

                    // Conv ops have a separate "weight" input
                    if (caseData.TryGetProperty("weight", out var weightElem))
                    {
                        var wData = GetFloatArray(weightElem.GetProperty("data"));
                        var wShape = GetIntArray(weightElem.GetProperty("shape"));
                        inputList.Add(pool.AllocatePermanent(wData, wShape));
                    }

                    inputs = inputList.ToArray();
                }

                // Extract attributes
                if (caseData.TryGetProperty("attributes", out var attrsElem))
                {
                    foreach (var prop in attrsElem.EnumerateObject())
                    {
                        if (prop.Value.ValueKind == JsonValueKind.Number)
                        {
                            // Try int first, fall back to double for floats like alpha=0.01
                            if (prop.Value.TryGetInt64(out var intVal) && !prop.Value.GetRawText().Contains('.'))
                                attrs[prop.Name] = intVal;
                            else
                                attrs[prop.Name] = prop.Value.GetDouble();
                        }
                        else if (prop.Value.ValueKind == JsonValueKind.Array)
                            attrs[prop.Name] = prop.Value.EnumerateArray().Select(e => e.GetInt64()).ToArray();
                        else if (prop.Value.ValueKind == JsonValueKind.String)
                            attrs[prop.Name] = prop.Value.GetString()!;
                    }
                }

                // Allocate output
                var output = pool.Rent(expectedShape, $"_test_{name}");

                // Build constant values so BroadcastHelper uses the CPU broadcast path
                // (without these, it falls to the broken GPU-copy fallback)
                var constValues = new Dictionary<string, float[]>();
                for (int ii = 0; ii < inputs.Length; ii++)
                {
                    var inputName = $"input_{ii}";
                    int elCount = inputs[ii].ElementCount;
                    using var tmpBuf = accelerator.Allocate1D<float>(elCount);
                    registry.ElementWise.Scale(inputs[ii].Data.SubView(0, elCount), tmpBuf.View, elCount, 1f);
                    await accelerator.SynchronizeAsync();
                    constValues[inputName] = await tmpBuf.CopyToHostAsync<float>(0, elCount);
                }

                var ctx = new OnnxOpContext
                {
                    Inputs = inputs,
                    Outputs = new[] { output },
                    Attributes = attrs,
                    Pool = pool,
                    InputNames = inputs.Select((_, i) => $"input_{i}").ToArray(),
                    ConstantValues = constValues,
                };
                onnxOp.Execute(ctx);
                await accelerator.SynchronizeAsync();

                // Read back and compare
                int elems = output.ElementCount;
                using var readBuf = accelerator.Allocate1D<float>(elems);
                registry.ElementWise.Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
                await accelerator.SynchronizeAsync();
                var actual = await readBuf.CopyToHostAsync<float>(0, elems);

                // Compare
                float maxErr = 0;
                for (int i = 0; i < Math.Min(actual.Length, expectedData.Length); i++)
                {
                    float err = MathF.Abs(actual[i] - expectedData[i]);
                    if (err > maxErr) maxErr = err;
                }

                if (maxErr > 0.01f)
                {
                    var a5 = string.Join(",", actual.Take(5).Select(v => v.ToString("F4")));
                    var e5 = string.Join(",", expectedData.Take(5).Select(v => v.ToString("F4")));
                    failures.Add($"{name} ({op}): maxErr={maxErr:F6}, actual=[{a5}] expected=[{e5}]");
                }
                else
                {
                    passed++;
                }
            }
            catch (Exception ex)
            {
                failures.Add($"{name}: {ex.Message.Split('\n')[0]}");
            }
        }

        if (failures.Count > 0)
            throw new Exception($"Operator tests: {passed}/{passed + failures.Count} passed. Failures:\n" +
                string.Join("\n", failures));
    });

    private static float[] GetFloatArray(JsonElement elem)
    {
        var list = new List<float>();
        FlattenJsonArray(elem, list);
        return list.ToArray();
    }

    private static void FlattenJsonArray(JsonElement elem, List<float> list)
    {
        if (elem.ValueKind == JsonValueKind.Array)
            foreach (var child in elem.EnumerateArray())
                FlattenJsonArray(child, list);
        else if (elem.ValueKind == JsonValueKind.Number)
            list.Add(elem.GetSingle());
        else if (elem.ValueKind == JsonValueKind.True)
            list.Add(1f);
        else if (elem.ValueKind == JsonValueKind.False)
            list.Add(0f);
    }

    private static int[] GetIntArray(JsonElement elem)
        => elem.EnumerateArray().Select(e => e.GetInt32()).ToArray();
}
