using ILGPU;
using ILGPU.Runtime;
using SpawnDev.ILGPU.ML;
using SpawnDev.ILGPU.ML.Operators;
using SpawnDev.ILGPU.ML.Tensors;
using SpawnDev.UnitTesting;
using System.Text.Json;

namespace SpawnDev.ILGPU.ML.Demo.Shared.UnitTests;

public abstract partial class MLTestBase
{
    // ──────────────────────────────────────────────────────────────
    //  Operator reference tests: numpy-verified exact-match cases.
    //  Data: operator_test_cases.json (96 cases, generated by Data)
    //  These catch broadcast bugs, pooling errors, and silent corruption.
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Run all operator test cases from numpy reference data.
    /// Each case loads known inputs, runs the operator, and compares
    /// output element-by-element against numpy-verified expected values.
    /// </summary>
    [TestMethod(Timeout = 120000)]
    public async Task OperatorRef_AllCases_MatchNumpy() => await RunTest(async accelerator =>
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        var json = await http.GetStringAsync("test-models/operator_test_cases.json");
        var cases = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(json)!;

        var registry = new OperatorRegistry(accelerator);
        using var pool = new BufferPool(accelerator);
        int passed = 0;
        var failures = new List<string>();

        foreach (var (name, caseData) in cases)
        {
            try
            {
                var op = caseData.GetProperty("op").GetString()!;
                var expectedData = GetFloatArray(caseData.GetProperty("expected").GetProperty("data"));
                var expectedShape = GetIntArray(caseData.GetProperty("expected").GetProperty("shape"));

                // Resolve operator
                if (!registry.IsSupported(op))
                {
                    failures.Add($"{name}: operator '{op}' not registered");
                    continue;
                }
                var onnxOp = registry.Resolve(op);

                // Build inputs — handle various JSON layouts
                var inputList = new List<Tensor>();
                Dictionary<string, object> attrs = new();

                if (op == "Where" && caseData.TryGetProperty("condition", out var condElem))
                {
                    // Where: 3 inputs (condition, x, y)
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(condElem.GetProperty("data")),
                        GetIntArray(condElem.GetProperty("shape"))));
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(caseData.GetProperty("input_x").GetProperty("data")),
                        GetIntArray(caseData.GetProperty("input_x").GetProperty("shape"))));
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(caseData.GetProperty("input_y").GetProperty("data")),
                        GetIntArray(caseData.GetProperty("input_y").GetProperty("shape"))));
                }
                else if (op == "ConstantOfShape" && caseData.TryGetProperty("input_shape", out var shapeElem))
                {
                    // ConstantOfShape: input is the shape tensor
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(shapeElem.GetProperty("data")),
                        GetIntArray(shapeElem.GetProperty("shape"))));
                }
                else if (caseData.TryGetProperty("input_a", out var inputA))
                {
                    // Binary operators: input_a, input_b, optional input_c
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(inputA.GetProperty("data")),
                        GetIntArray(inputA.GetProperty("shape"))));
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(caseData.GetProperty("input_b").GetProperty("data")),
                        GetIntArray(caseData.GetProperty("input_b").GetProperty("shape"))));
                    if (caseData.TryGetProperty("input_c", out var inputC))
                    {
                        inputList.Add(pool.AllocatePermanent(
                            GetFloatArray(inputC.GetProperty("data")),
                            GetIntArray(inputC.GetProperty("shape"))));
                    }
                }
                else
                {
                    // Single input operators
                    inputList.Add(pool.AllocatePermanent(
                        GetFloatArray(caseData.GetProperty("input").GetProperty("data")),
                        GetIntArray(caseData.GetProperty("input").GetProperty("shape"))));

                    // Conv/ConvTranspose: weight tensor
                    if (caseData.TryGetProperty("weight", out var weightElem))
                    {
                        inputList.Add(pool.AllocatePermanent(
                            GetFloatArray(weightElem.GetProperty("data")),
                            GetIntArray(weightElem.GetProperty("shape"))));
                    }
                }

                // Additional named inputs: scale, bias, mean, var, indices
                // These are extra inputs required by normalization and gather operators
                foreach (var extraField in new[] { "scale", "bias", "mean", "var", "indices" })
                {
                    if (caseData.TryGetProperty(extraField, out var extraElem))
                    {
                        inputList.Add(pool.AllocatePermanent(
                            GetFloatArray(extraElem.GetProperty("data")),
                            GetIntArray(extraElem.GetProperty("shape"))));
                    }
                }

                var inputs = inputList.ToArray();

                // Extract attributes
                if (caseData.TryGetProperty("attributes", out var attrsElem))
                {
                    foreach (var prop in attrsElem.EnumerateObject())
                    {
                        if (prop.Value.ValueKind == JsonValueKind.Number)
                        {
                            if (prop.Value.TryGetInt64(out var intVal) && !prop.Value.GetRawText().Contains('.'))
                                attrs[prop.Name] = intVal;
                            else
                                attrs[prop.Name] = prop.Value.GetDouble();
                        }
                        else if (prop.Value.ValueKind == JsonValueKind.Array)
                        {
                            // Handle arrays that may contain floats (e.g., scales=[1.0,1.0,2.0,2.0])
                            var arr = prop.Value.EnumerateArray().ToArray();
                            bool allInts = arr.All(e => e.TryGetInt64(out _) && !e.GetRawText().Contains('.'));
                            if (allInts)
                                attrs[prop.Name] = arr.Select(e => e.GetInt64()).ToArray();
                            else
                                attrs[prop.Name] = arr.Select(e => e.GetDouble()).ToArray();
                        }
                        else if (prop.Value.ValueKind == JsonValueKind.String)
                        {
                            var sv = prop.Value.GetString()!;
                            // Handle special float values encoded as strings
                            if (sv == "-Infinity") attrs[prop.Name] = (double)float.NegativeInfinity;
                            else if (sv == "Infinity") attrs[prop.Name] = (double)float.PositiveInfinity;
                            else if (sv == "NaN") attrs[prop.Name] = (double)float.NaN;
                            else attrs[prop.Name] = sv;
                        }
                    }
                }

                // Allocate output — use a dedicated buffer to avoid aliasing with inputs
                // (e.g., GELU reads from input and writes to output; if pool reuses the same
                //  underlying buffer, WebGPU throws a buffer aliasing error)
                using var outputBuf = accelerator.Allocate1D<float>(expectedData.Length);
                var output = new Tensor(outputBuf.View, expectedShape);

                // Build constant values so BroadcastHelper uses the CPU broadcast path
                var constValues = new Dictionary<string, float[]>();
                for (int ii = 0; ii < inputs.Length; ii++)
                {
                    var inputName = $"input_{ii}";
                    int elCount = inputs[ii].ElementCount;
                    using var tmpBuf = accelerator.Allocate1D<float>(elCount);
                    registry.ElementWise.Scale(inputs[ii].Data.SubView(0, elCount), tmpBuf.View, elCount, 1f);
                    await accelerator.SynchronizeAsync();
                    constValues[inputName] = await tmpBuf.CopyToHostAsync<float>(0, elCount);
                }

                // Handle Split: output_index specifies which split part to test
                int outputIndex = attrs.ContainsKey("output_index") ? Convert.ToInt32(attrs["output_index"]) : -1;
                // Remove output_index from attrs so the operator doesn't see it
                attrs.Remove("output_index");

                Tensor[] outputs;
                if (op == "Split" && outputIndex >= 0)
                {
                    // Create multiple output buffers for Split, select the right one
                    var splitSizes = attrs.ContainsKey("split") && attrs["split"] is long[] splitLongs
                        ? splitLongs.Select(s => (int)s).ToArray()
                        : null;
                    int axis = attrs.ContainsKey("axis") ? Convert.ToInt32(attrs["axis"]) : 0;
                    if (axis < 0) axis += inputs[0].Shape.Length;
                    int numOutputs = splitSizes?.Length ?? (attrs.ContainsKey("num_outputs") ? Convert.ToInt32(attrs["num_outputs"]) : 2);
                    if (splitSizes == null)
                    {
                        int dimSize = inputs[0].Shape[axis];
                        int partSize = dimSize / numOutputs;
                        splitSizes = Enumerable.Repeat(partSize, numOutputs).ToArray();
                        if (dimSize % numOutputs != 0)
                            splitSizes[numOutputs - 1] = dimSize - partSize * (numOutputs - 1);
                    }

                    var splitOutputs = new List<Tensor>();
                    var splitBufs = new List<MemoryBuffer1D<float, Stride1D.Dense>>();
                    for (int si = 0; si < numOutputs; si++)
                    {
                        var outShape = (int[])inputs[0].Shape.Clone();
                        outShape[axis] = splitSizes[si];
                        int elCount = outShape.Aggregate(1, (a, b) => a * b);
                        var buf = accelerator.Allocate1D<float>(elCount);
                        splitBufs.Add(buf);
                        splitOutputs.Add(new Tensor(buf.View, outShape));
                    }
                    outputs = splitOutputs.ToArray();
                    output = outputs[outputIndex];

                    var ctx = new OnnxOpContext
                    {
                        Inputs = inputs,
                        Outputs = outputs,
                        Attributes = attrs,
                        Pool = pool,
                        InputNames = inputs.Select((_, i) => $"input_{i}").ToArray(),
                        ConstantValues = constValues,
                    };
                    onnxOp.Execute(ctx);
                    await accelerator.SynchronizeAsync();

                    // Dispose extra split buffers (not the one we're reading)
                    for (int si = 0; si < splitBufs.Count; si++)
                        if (si != outputIndex) splitBufs[si].Dispose();
                }
                else
                {
                    outputs = new[] { output };
                    var ctx = new OnnxOpContext
                    {
                        Inputs = inputs,
                        Outputs = outputs,
                        Attributes = attrs,
                        Pool = pool,
                        InputNames = inputs.Select((_, i) => $"input_{i}").ToArray(),
                        ConstantValues = constValues,
                    };
                    onnxOp.Execute(ctx);
                    await accelerator.SynchronizeAsync();
                }

                // Read back and compare
                int elems = output.ElementCount;
                using var readBuf = accelerator.Allocate1D<float>(elems);
                registry.ElementWise.Scale(output.Data.SubView(0, elems), readBuf.View, elems, 1f);
                await accelerator.SynchronizeAsync();
                var actual = await readBuf.CopyToHostAsync<float>(0, elems);

                // Compare (handle -Infinity in expected values)
                float maxErr = 0;
                for (int i = 0; i < Math.Min(actual.Length, expectedData.Length); i++)
                {
                    if (float.IsNegativeInfinity(expectedData[i]))
                    {
                        if (!float.IsNegativeInfinity(actual[i]))
                            maxErr = float.MaxValue;
                    }
                    else if (float.IsPositiveInfinity(expectedData[i]))
                    {
                        if (!float.IsPositiveInfinity(actual[i]))
                            maxErr = float.MaxValue;
                    }
                    else if (float.IsNaN(expectedData[i]))
                    {
                        if (!float.IsNaN(actual[i]))
                            maxErr = float.MaxValue;
                    }
                    else
                    {
                        float err = MathF.Abs(actual[i] - expectedData[i]);
                        if (err > maxErr) maxErr = err;
                    }
                }

                if (maxErr > 0.01f)
                {
                    var a5 = string.Join(",", actual.Take(5).Select(v => v.ToString("F4")));
                    var e5 = string.Join(",", expectedData.Take(5).Select(v => v.ToString("F4")));
                    failures.Add($"{name} ({op}): maxErr={maxErr:F6}, actual=[{a5}] expected=[{e5}]");
                }
                else
                {
                    passed++;
                }
            }
            catch (Exception ex)
            {
                failures.Add($"{name}: {ex.Message.Split('\n')[0]}");
            }
        }

        Console.WriteLine($"Operator tests: {passed}/{passed + failures.Count} passed.");
        if (failures.Count > 0)
            throw new Exception($"Operator tests: {passed}/{passed + failures.Count} passed. Failures:\n" +
                string.Join("\n", failures));
    });

    private static float[] GetFloatArray(JsonElement elem)
    {
        var list = new List<float>();
        FlattenJsonArray(elem, list);
        return list.ToArray();
    }

    private static void FlattenJsonArray(JsonElement elem, List<float> list)
    {
        if (elem.ValueKind == JsonValueKind.Array)
            foreach (var child in elem.EnumerateArray())
                FlattenJsonArray(child, list);
        else if (elem.ValueKind == JsonValueKind.Number)
            list.Add(elem.GetSingle());
        else if (elem.ValueKind == JsonValueKind.True)
            list.Add(1f);
        else if (elem.ValueKind == JsonValueKind.False)
            list.Add(0f);
        else if (elem.ValueKind == JsonValueKind.String)
        {
            // Handle special float values encoded as strings (e.g., "-Infinity")
            var s = elem.GetString()!;
            if (s == "-Infinity") list.Add(float.NegativeInfinity);
            else if (s == "Infinity") list.Add(float.PositiveInfinity);
            else if (s == "NaN") list.Add(float.NaN);
        }
    }

    private static int[] GetIntArray(JsonElement elem)
        => elem.EnumerateArray().Select(e => e.GetInt32()).ToArray();
}
