using SpawnDev.ILGPU.ML.Preprocessing;
using SpawnDev.UnitTesting;
using System.Text.Json;

namespace SpawnDev.ILGPU.ML.Demo.Shared.UnitTests;

/// <summary>
/// Tests for CPU-side preprocessors: TextPreprocessor, AudioPreprocessor, BPETokenizer.
/// Reference data generated by Data's Python scripts.
/// </summary>
public abstract partial class MLTestBase
{
    // ═══════════════════════════════════════════════════════════
    //  TextPreprocessor Tests
    // ═══════════════════════════════════════════════════════════

    [TestMethod]
    public async Task TextPreprocessor_AttentionMask()
    {
        await Task.CompletedTask;
        // Real tokens get 1, padding (0) gets 0
        var mask = TextPreprocessor.CreateAttentionMask(new[] { 101, 7592, 2088, 102, 0, 0 }, padToken: 0);
        AssertArrayEquals(new[] { 1, 1, 1, 1, 0, 0 }, mask, "AttentionMask");
    }

    [TestMethod]
    public async Task TextPreprocessor_PadOrTruncate()
    {
        await Task.CompletedTask;
        // Pad short sequence
        var padded = TextPreprocessor.PadOrTruncate(new[] { 101, 7592, 102 }, maxLength: 6, padToken: 0);
        AssertArrayEquals(new[] { 101, 7592, 102, 0, 0, 0 }, padded, "PadShort");

        // Truncate long sequence
        var truncated = TextPreprocessor.PadOrTruncate(new[] { 1, 2, 3, 4, 5, 6, 7 }, maxLength: 4, padToken: 0);
        AssertArrayEquals(new[] { 1, 2, 3, 4 }, truncated, "TruncateLong");

        // Exact length — no change
        var exact = TextPreprocessor.PadOrTruncate(new[] { 1, 2, 3 }, maxLength: 3, padToken: 0);
        AssertArrayEquals(new[] { 1, 2, 3 }, exact, "ExactLength");
    }

    [TestMethod]
    public async Task TextPreprocessor_PositionIds()
    {
        await Task.CompletedTask;
        var ids = TextPreprocessor.CreatePositionIds(6);
        AssertArrayEquals(new[] { 0, 1, 2, 3, 4, 5 }, ids, "PositionIds");
    }

    [TestMethod]
    public async Task TextPreprocessor_Softmax_Basic()
    {
        await Task.CompletedTask;
        var result = TextPreprocessor.Softmax(new float[] { 1.0f, 2.0f, 3.0f });
        // Sum should be ~1.0
        float sum = result.Sum();
        if (MathF.Abs(sum - 1.0f) > 1e-5f)
            throw new Exception($"Softmax sum={sum}, expected ~1.0");
        // Result should be monotonically increasing
        if (result[0] >= result[1] || result[1] >= result[2])
            throw new Exception($"Softmax not monotonically increasing: [{string.Join(",", result.Select(v => v.ToString("F4")))}]");
    }

    [TestMethod]
    public async Task TextPreprocessor_Softmax_NumericalStability()
    {
        await Task.CompletedTask;
        // Very large values should not produce NaN/Infinity
        var result = TextPreprocessor.Softmax(new float[] { 1000.0f, 1000.0f, 999.0f });
        if (result.Any(float.IsNaN) || result.Any(float.IsInfinity))
            throw new Exception($"Softmax produced NaN/Infinity for large inputs: [{string.Join(",", result)}]");
        float sum = result.Sum();
        if (MathF.Abs(sum - 1.0f) > 1e-5f)
            throw new Exception($"Softmax large-value sum={sum}, expected ~1.0");
    }

    [TestMethod]
    public async Task TextPreprocessor_TopK()
    {
        await Task.CompletedTask;
        var scores = new float[] { 0.1f, 0.8f, 0.3f, 0.9f, 0.5f };
        var top3 = TextPreprocessor.TopK(scores, k: 3);
        if (top3.Length != 3)
            throw new Exception($"TopK returned {top3.Length} items, expected 3");
        if (top3[0].Index != 3 || top3[1].Index != 1 || top3[2].Index != 4)
            throw new Exception($"TopK wrong order: [{string.Join(",", top3.Select(t => $"idx={t.Index}"))}]");
    }

    [TestMethod]
    public async Task TextPreprocessor_CosineSimilarity()
    {
        await Task.CompletedTask;
        // Identical vectors → 1.0
        float sim1 = TextPreprocessor.CosineSimilarity(new float[] { 1, 0, 0 }, new float[] { 1, 0, 0 });
        if (MathF.Abs(sim1 - 1.0f) > 1e-5f)
            throw new Exception($"Identical vectors similarity={sim1}, expected 1.0");

        // Orthogonal vectors → 0.0
        float sim2 = TextPreprocessor.CosineSimilarity(new float[] { 1, 0, 0 }, new float[] { 0, 1, 0 });
        if (MathF.Abs(sim2) > 1e-5f)
            throw new Exception($"Orthogonal vectors similarity={sim2}, expected 0.0");

        // Opposite vectors → -1.0
        float sim3 = TextPreprocessor.CosineSimilarity(new float[] { 1, 0, 0 }, new float[] { -1, 0, 0 });
        if (MathF.Abs(sim3 - (-1.0f)) > 1e-5f)
            throw new Exception($"Opposite vectors similarity={sim3}, expected -1.0");
    }

    // ═══════════════════════════════════════════════════════════
    //  AudioPreprocessor Tests
    // ═══════════════════════════════════════════════════════════

    [TestMethod]
    public async Task AudioPreprocessor_HzToMel_RoundTrip()
    {
        await Task.CompletedTask;
        float[] hzValues = { 0f, 100f, 200f, 440f, 1000f, 2000f, 4000f, 8000f };
        foreach (var hz in hzValues)
        {
            float mel = AudioPreprocessor.HzToMel(hz);
            float roundTrip = AudioPreprocessor.MelToHz(mel);
            float err = MathF.Abs(roundTrip - hz);
            if (err > 0.1f)
                throw new Exception($"Hz→Mel→Hz round-trip failed: {hz} → {mel} → {roundTrip} (err={err})");
        }
    }

    [TestMethod]
    public async Task AudioPreprocessor_HannWindow_Endpoints()
    {
        await Task.CompletedTask;
        var window = AudioPreprocessor.GenerateHannWindow(400);
        if (window.Length != 400)
            throw new Exception($"Hann window length={window.Length}, expected 400");
        // Endpoints should be near 0
        if (window[0] > 0.001f)
            throw new Exception($"Hann window[0]={window[0]}, expected ~0");
        // Middle should be near 1
        float mid = window[200];
        if (mid < 0.99f)
            throw new Exception($"Hann window[200]={mid}, expected ~1.0");
        // Symmetric
        for (int i = 0; i < 10; i++)
        {
            float diff = MathF.Abs(window[i] - window[399 - i]);
            if (diff > 1e-6f)
                throw new Exception($"Hann window not symmetric at {i}: {window[i]} vs {window[399 - i]}");
        }
    }

    [TestMethod]
    public async Task AudioPreprocessor_Resample_Frequency()
    {
        await Task.CompletedTask;
        // Generate 440Hz tone at 44100Hz for 0.1 seconds
        int srcRate = 44100;
        int dstRate = 16000;
        float freq = 440f;
        int srcLen = (int)(srcRate * 0.1f);
        var srcSamples = new float[srcLen];
        for (int i = 0; i < srcLen; i++)
            srcSamples[i] = MathF.Sin(2 * MathF.PI * freq * i / srcRate);

        var resampled = AudioPreprocessor.Resample(srcSamples, srcRate, dstRate);
        int expectedLen = (int)(dstRate * 0.1f);
        // Allow ±1 sample tolerance
        if (Math.Abs(resampled.Length - expectedLen) > 1)
            throw new Exception($"Resampled length={resampled.Length}, expected ~{expectedLen}");
        // Values should be in [-1, 1]
        if (resampled.Any(v => v < -1.1f || v > 1.1f))
            throw new Exception("Resampled values outside [-1.1, 1.1]");
    }

    [TestMethod]
    public async Task AudioPreprocessor_PadOrTrim()
    {
        await Task.CompletedTask;
        // Pad short
        var padded = AudioPreprocessor.PadOrTrim(new float[] { 1, 2, 3 }, 5);
        if (padded.Length != 5)
            throw new Exception($"Padded length={padded.Length}, expected 5");
        if (padded[3] != 0f || padded[4] != 0f)
            throw new Exception("Padding should be zeros");

        // Trim long
        var trimmed = AudioPreprocessor.PadOrTrim(new float[] { 1, 2, 3, 4, 5 }, 3);
        if (trimmed.Length != 3)
            throw new Exception($"Trimmed length={trimmed.Length}, expected 3");
    }

    [TestMethod]
    public async Task AudioPreprocessor_StereoToMono()
    {
        await Task.CompletedTask;
        // Interleaved L/R: [L0, R0, L1, R1]
        var mono = AudioPreprocessor.StereoToMono(new float[] { 1.0f, 0.0f, 0.5f, 0.5f, 0.0f, 1.0f });
        if (mono.Length != 3)
            throw new Exception($"Mono length={mono.Length}, expected 3");
        if (MathF.Abs(mono[0] - 0.5f) > 1e-6f)
            throw new Exception($"Mono[0]={mono[0]}, expected 0.5 (average of 1.0 and 0.0)");
    }

    // ═══════════════════════════════════════════════════════════
    //  BPE Tokenizer Tests (requires model tokenizer files)
    // ═══════════════════════════════════════════════════════════

    [TestMethod]
    public async Task BPETokenizer_LoadAndEncode_GPT2()
    {
        var http = GetHttpClient();
        if (http == null) throw new UnsupportedTestException("HttpClient not available");

        // Load GPT-2 tokenizer files
        string vocabJson, mergesText;
        try
        {
            vocabJson = await http.GetStringAsync("references/gpt2/vocab.json");
            mergesText = await http.GetStringAsync("references/gpt2/merges.txt");
        }
        catch
        {
            throw new UnsupportedTestException("GPT-2 tokenizer files not available locally");
        }

        var tokenizer = BPETokenizer.Load(vocabJson, mergesText);
        if (tokenizer.VocabSize < 50000)
            throw new Exception($"GPT-2 vocab size={tokenizer.VocabSize}, expected ~50257");

        // Encode "Hello world"
        var tokens = tokenizer.Encode("Hello world");
        if (tokens.Length < 2)
            throw new Exception($"'Hello world' produced {tokens.Length} tokens, expected >= 2");

        // Decode round-trip
        var decoded = tokenizer.Decode(tokens);
        if (!decoded.Contains("Hello") || !decoded.Contains("world"))
            throw new Exception($"Decode round-trip failed: '{decoded}'");

        Console.WriteLine($"[BPETokenizer] GPT-2: 'Hello world' → {tokens.Length} tokens → '{decoded}'");
    }

    // ═══════════════════════════════════════════════════════════
    //  Helpers
    // ═══════════════════════════════════════════════════════════

    private static void AssertArrayEquals(int[] expected, int[] actual, string name)
    {
        if (expected.Length != actual.Length)
            throw new Exception($"{name}: length mismatch. Expected {expected.Length}, got {actual.Length}");
        for (int i = 0; i < expected.Length; i++)
        {
            if (expected[i] != actual[i])
                throw new Exception($"{name}: mismatch at [{i}]. Expected {expected[i]}, got {actual[i]}");
        }
    }
}
