using ILGPU;
using ILGPU.Runtime;
using SpawnDev.ILGPU.ML;
using SpawnDev.ILGPU.ML.Operators;
using SpawnDev.ILGPU.ML.Tensors;
using SpawnDev.UnitTesting;

namespace SpawnDev.ILGPU.ML.Demo.Shared.UnitTests;

/// <summary>
/// Real GPU kernel tests for core element-wise operators.
/// Each test allocates GPU buffers, dispatches the kernel, and compares against CPU reference.
/// Operator-level tests via the Execute() path are in MLTestBase.OperatorCoverageTests.cs.
/// Fake Resolve()-only tests have been removed — every test here runs real GPU code.
/// </summary>
public abstract partial class MLTestBase
{
    // Helper for operator-level tests
    private static OnnxOpContext MakeOpCtx(Accelerator acc, Tensor[] inputs, Tensor[] outputs,
        Dictionary<string, object>? attrs = null, string[]? inputNames = null,
        Dictionary<string, float[]>? constants = null) => new OnnxOpContext
    {
        Inputs = inputs, Outputs = outputs,
        Attributes = attrs ?? new Dictionary<string, object>(),
        Pool = new BufferPool(acc),
        InputNames = inputNames ?? inputs.Select((_, i) => $"input_{i}").ToArray(),
        ConstantValues = constants
    };

    [TestMethod] public async Task AllOps_Abs() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-3,-1,0,1,3}); using var o = a.Allocate1D<float>(5); e.Abs(i.View,o.View,5); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{3,1,0,1,3},0f,"Abs:"); });
    [TestMethod] public async Task AllOps_Acos() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,0.5f,1}); using var o = a.Allocate1D<float>(3); e.Acos(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Acos(0),MathF.Acos(0.5f),MathF.Acos(1)},1e-4f,"Acos:"); });
    [TestMethod] public async Task AllOps_Acosh() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{1,2,5}); using var o = a.Allocate1D<float>(3); e.Acosh(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Acosh(1),MathF.Acosh(2),MathF.Acosh(5)},1e-4f,"Acosh:"); });
    [TestMethod] public async Task AllOps_Add() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,2,3}); using var y = a.Allocate1D(new float[]{4,5,6}); using var o = a.Allocate1D<float>(3); e.Add(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{5,7,9},0f,"Add:"); });
    [TestMethod] public async Task AllOps_ArgMax() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{1,5,3,2,4,6}); using var o = a.Allocate1D<float>(2); e.ArgMax(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,2},0f,"ArgMax:"); });
    [TestMethod] public async Task AllOps_Asin() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,0.5f,-0.5f}); using var o = a.Allocate1D<float>(3); e.Asin(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Asin(0),MathF.Asin(0.5f),MathF.Asin(-0.5f)},1e-4f,"Asin:"); });
    [TestMethod] public async Task AllOps_Asinh() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Asinh(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Asinh(-1),MathF.Asinh(0),MathF.Asinh(1)},1e-4f,"Asinh:"); });
    [TestMethod] public async Task AllOps_Atan() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Atan(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Atan(-1),MathF.Atan(0),MathF.Atan(1)},1e-4f,"Atan:"); });
    [TestMethod] public async Task AllOps_Atanh() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-0.5f,0,0.5f}); using var o = a.Allocate1D<float>(3); e.Atanh(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Atanh(-0.5f),MathF.Atanh(0),MathF.Atanh(0.5f)},1e-4f,"Atanh:"); });
    [TestMethod] public async Task AllOps_Ceil() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0.1f,0.9f,-0.1f}); using var o = a.Allocate1D<float>(3); e.Ceil(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,1,0},0f,"Ceil:"); });
    [TestMethod] public async Task AllOps_Celu() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Celu(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Max(0,-1)+MathF.Min(0,MathF.Exp(-1)-1),0f,1f},1e-4f,"Celu:"); });
    [TestMethod] public async Task AllOps_Clip() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-5,-1,0,1,5}); using var o = a.Allocate1D<float>(5); e.Clip(i.View,o.View,5,-2f,2f); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{-2,-1,0,1,2},0f,"Clip:"); });
    [TestMethod] public async Task AllOps_Cos() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,MathF.PI/2,MathF.PI}); using var o = a.Allocate1D<float>(3); e.Cos(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{1f,0f,-1f},1e-4f,"Cos:"); });
    [TestMethod] public async Task AllOps_Cosh() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,1,-1}); using var o = a.Allocate1D<float>(3); e.Cosh(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Cosh(0),MathF.Cosh(1),MathF.Cosh(-1)},1e-4f,"Cosh:"); });
    [TestMethod] public async Task AllOps_Div() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{6,8,10}); using var y = a.Allocate1D(new float[]{2,4,5}); using var o = a.Allocate1D<float>(3); e.Div(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{3,2,2},1e-4f,"Div:"); });
    [TestMethod] public async Task AllOps_Elu() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Elu(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Exp(-1)-1,0f,1f},1e-4f,"Elu:"); });
    [TestMethod] public async Task AllOps_Equal() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,2,3}); using var y = a.Allocate1D(new float[]{1,0,3}); using var o = a.Allocate1D<float>(3); e.Equal(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,0,1},0f,"Equal:"); });
    [TestMethod] public async Task AllOps_Erf() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0}); using var o = a.Allocate1D<float>(1); e.Erf(i.View,o.View,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0},1e-4f,"Erf:"); });
    [TestMethod] public async Task AllOps_Exp() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,1}); using var o = a.Allocate1D<float>(2); e.Exp(i.View,o.View,2); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{1f,MathF.E},1e-4f,"Exp:"); });
    [TestMethod] public async Task AllOps_Floor() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0.9f,1.1f,-0.1f,-0.9f}); using var o = a.Allocate1D<float>(4); e.Floor(i.View,o.View,4); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,1,-1,-1},0f,"Floor:"); });
    [TestMethod] public async Task AllOps_GlobalMaxPool() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{1,5,3,2,4,6}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceMax(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{5,6},0f,"GlobalMaxPool:"); });
    [TestMethod] public async Task AllOps_Greater() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,5,3}); using var y = a.Allocate1D(new float[]{2,2,3}); using var o = a.Allocate1D<float>(3); e.Greater(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,1,0},0f,"Greater:"); });
    [TestMethod] public async Task AllOps_IsInf() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,float.PositiveInfinity,float.NegativeInfinity}); using var o = a.Allocate1D<float>(3); e.IsInf(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,1,1},0f,"IsInf:"); });
    [TestMethod] public async Task AllOps_Less() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,5,3}); using var y = a.Allocate1D(new float[]{2,2,3}); using var o = a.Allocate1D<float>(3); e.Less(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,0,0},0f,"Less:"); });
    [TestMethod] public async Task AllOps_Log() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{1,MathF.E}); using var o = a.Allocate1D<float>(2); e.Log(i.View,o.View,2); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,1},1e-4f,"Log:"); });
    [TestMethod] public async Task AllOps_MatMul() => await RunTest(async a => { var r = new OperatorRegistry(a); using var x = a.Allocate1D(new float[]{1,2,3,4}); using var y = a.Allocate1D(new float[]{5,6,7,8}); using var o = a.Allocate1D<float>(4); r.MatMul.MatMul(x.View,y.View,o.View,2,2,2); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{19,22,43,50},1e-3f,"MatMul:"); });
    [TestMethod] public async Task AllOps_Max() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,5,3}); using var y = a.Allocate1D(new float[]{4,2,6}); using var o = a.Allocate1D<float>(3); e.Max(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{4,5,6},0f,"Max:"); });
    [TestMethod] public async Task AllOps_Min() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{1,5,3}); using var y = a.Allocate1D(new float[]{4,2,6}); using var o = a.Allocate1D<float>(3); e.Min(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,2,3},0f,"Min:"); });
    [TestMethod] public async Task AllOps_Mish() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,1,-1}); using var o = a.Allocate1D<float>(3); e.Mish(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{0f,MathF.Tanh(MathF.Log(1+MathF.Exp(1))),-MathF.Tanh(MathF.Log(1+MathF.Exp(-1)))},1e-4f,"Mish:"); });
    [TestMethod] public async Task AllOps_Mul() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{2,3,4}); using var y = a.Allocate1D(new float[]{5,6,7}); using var o = a.Allocate1D<float>(3); e.Mul(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{10,18,28},0f,"Mul:"); });
    [TestMethod] public async Task AllOps_Neg() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-3,0,3}); using var o = a.Allocate1D<float>(3); e.Scale(i.View,o.View,3,-1f); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{3,0,-3},0f,"Neg:"); });
    [TestMethod] public async Task AllOps_Pow() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{2,3,4}); using var y = a.Allocate1D(new float[]{3,2,0.5f}); using var o = a.Allocate1D<float>(3); e.Pow(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{8,9,2},1e-3f,"Pow:"); });
    [TestMethod] public async Task AllOps_Reciprocal() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{2,4,5}); using var o = a.Allocate1D<float>(3); e.Reciprocal(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0.5f,0.25f,0.2f},1e-4f,"Reciprocal:"); });
    [TestMethod] public async Task AllOps_ReduceMax() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{1,5,3,2,4,6}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceMax(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{5,6},0f,"ReduceMax:"); });
    [TestMethod] public async Task AllOps_ReduceMean() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{1,2,3,4,5,6}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceMean(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{2,5},1e-4f,"ReduceMean:"); });
    [TestMethod] public async Task AllOps_ReduceMin() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{5,1,3,6,2,4}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceMin(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{1,2},0f,"ReduceMin:"); });
    [TestMethod] public async Task AllOps_ReduceProd() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{1,2,3,4,5,6}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceProd(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{6,120},1e-2f,"ReduceProd:"); });
    [TestMethod] public async Task AllOps_ReduceSum() => await RunTest(async a => { var r = new OperatorRegistry(a); using var i = a.Allocate1D(new float[]{1,2,3,4,5,6}); using var o = a.Allocate1D<float>(2); r.Reductions.ReduceSum(i.View,o.View,2,3,1); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{6,15},1e-4f,"ReduceSum:"); });
    [TestMethod] public async Task AllOps_Relu() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-2,-1,0,1,2}); using var o = a.Allocate1D<float>(5); e.ReLU(i.View,o.View,5); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,0,0,1,2},0f,"Relu:"); });
    [TestMethod] public async Task AllOps_Selu() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Selu(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{1.0507f*1.67326f*(MathF.Exp(-1)-1),0f,1.0507f},1e-3f,"Selu:"); });
    [TestMethod] public async Task AllOps_Sin() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,MathF.PI/2,MathF.PI}); using var o = a.Allocate1D<float>(3); e.Sin(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{0f,1f,0f},1e-4f,"Sin:"); });
    [TestMethod] public async Task AllOps_Sinh() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,1}); using var o = a.Allocate1D<float>(2); e.Sinh(i.View,o.View,2); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{0f,MathF.Sinh(1)},1e-4f,"Sinh:"); });
    [TestMethod] public async Task AllOps_Softplus() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-1,0,1}); using var o = a.Allocate1D<float>(3); e.Softplus(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{MathF.Log(1+MathF.Exp(-1)),MathF.Log(2),MathF.Log(1+MathF.Exp(1))},1e-4f,"Softplus:"); });
    [TestMethod] public async Task AllOps_Softsign() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{-2,0,2}); using var o = a.Allocate1D<float>(3); e.Softsign(i.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{-2f/3,0f,2f/3},1e-4f,"Softsign:"); });
    [TestMethod] public async Task AllOps_Sqrt() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,1,4,9}); using var o = a.Allocate1D<float>(4); e.Sqrt(i.View,o.View,4); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{0,1,2,3},1e-4f,"Sqrt:"); });
    [TestMethod] public async Task AllOps_Sub() => await RunTest(async a => { var e = GetOrCreateEW(a); using var x = a.Allocate1D(new float[]{5,7,9}); using var y = a.Allocate1D(new float[]{1,2,3}); using var o = a.Allocate1D<float>(3); e.Sub(x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{4,5,6},0f,"Sub:"); });
    [TestMethod] public async Task AllOps_Tan() => await RunTest(async a => { var e = GetOrCreateEW(a); using var i = a.Allocate1D(new float[]{0,MathF.PI/4}); using var o = a.Allocate1D<float>(2); e.Tan(i.View,o.View,2); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new[]{0f,1f},1e-4f,"Tan:"); });
    [TestMethod] public async Task AllOps_Where() => await RunTest(async a => { var e = GetOrCreateEW(a); using var c = a.Allocate1D(new float[]{1,0,1}); using var x = a.Allocate1D(new float[]{10,20,30}); using var y = a.Allocate1D(new float[]{100,200,300}); using var o = a.Allocate1D<float>(3); e.Where(c.View,x.View,y.View,o.View,3); await a.SynchronizeAsync(); await AssertCloseGpu(a,o.View,new float[]{10,200,30},0f,"Where:"); });
}
