// Kernel: FusedLinearGeluImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 5
// Time: 2026-03-24T04:51:44.5260000Z

// Kernel: FusedLinearGeluImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: FusedLinearGeluImpl_243
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_63086 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(3) var<storage, read_write> param4_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 7: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param2000 at scalar slot 3
// View offset for param3000 at scalar slot 4
// View offset for param4000 at scalar slot 5
// View offset for param5000 at scalar slot 6
@group(0) @binding(4) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : i32 = 0;
    var v_3 : i32 = 0;
    var v_4 : f32 = 0.0;
    var v_5 : i32 = 0;
    var v_6 : i32 = 0;
    var v_7 : bool = false;
    var v_8 : i32 = 0;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : i32 = 0;
    var v_12 : bool = false;
    var v_13 : i32 = 0;
    var v_14 : f32 = 0.0;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : bool = false;
    var v_18 : bool = false;
    var v_19 : f32 = 0.0;
    var v_20 : bool = false;
    var v_21 : bool = false;
    var v_22 : bool = false;
    var v_23 : bool = false;
    var v_24 : bool = false;
    var v_25 : bool = false;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : f32 = 0.0;
    var v_29 : f32 = 0.0;
    var v_30 : f32 = 0.0;
    var v_31 : f32 = 0.0;
    var v_32 : f32 = 0.0;
    var v_33 : f32 = 0.0;
    var v_34 : f32 = 0.0;
    var v_35 : f32 = 0.0;
    var v_36 : f32 = 0.0;
    var v_37 : f32 = 0.0;
    var v_38 : f32 = 0.0;
    var v_39 : f32 = 0.0;
    var v_40 : f32 = 0.0;
    var v_41 : f32 = 0.0;
    var v_42 : f32 = 0.0;
    var v_43 : f32 = 0.0;
    var v_44 : f32 = 0.0;
    var v_45 : f32 = 0.0;
    var v_46 : f32 = 0.0;
    var v_47 : f32 = 0.0;
    var v_48 : f32 = 0.0;
    var v_49 : f32 = 0.0;
    var v_50 : f32 = 0.0;
    var v_51 : f32 = 0.0;
    var v_52 : bool = false;
    var v_53 : bool = false;
    var v_54 : bool = false;
    var v_55 : bool = false;
    var v_56 : f32 = 0.0;
    var v_57 : f32 = 0.0;
    var v_58 : f32 = 0.0;
    var v_59 : i32 = 0;
    var v_60 : bool = false;
    var v_61 : bool = false;
    var v_62 : bool = false;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    var v_65 : bool = false;
    var v_66 : bool = false;
    var v_67 : bool = false;
    var v_68 : f32 = 0.0;
    var v_69 : f32 = 0.0;
    var v_70 : i32 = 0;
    var v_71 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_71) >= _ilgpu_user_dim) { return; }
    let v_72_f0 = &param1_f0;
    var v_72_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_73_f0 = &param2_f0;
    var v_73_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_74_f0 = &param3_f0;
    var v_74_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    let v_75_f0 = &param4_f0;
    var v_75_f1 = i64_from_i32(i32(arrayLength(&param4_f0)));
    var v_77 = bitcast<i32>(_scalar_params[1]);
    var v_78 = bitcast<i32>(_scalar_params[2]);
    var v_85 : emu_i64;
    var v_87 : emu_i64;
    var v_89 : i32;
    var v_90 : emu_i64;
    var v_92 : emu_i64;
    var v_94 : i32;
    var v_96 : i32;
    var v_99 : i32;
    var v_102 : f32;
    var v_103 : i32;
    var v_106 : i32;
    var v_109 : f32;
    var v_110 : i32;
    var v_111 : emu_i64;
    var v_113 : emu_i64;
    var v_116 : i32;
    var v_119 : i32;
    var v_121 : i32;
    var v_124 : f32;
    var v_125 : f32;
    var v_127 : f32;
    var v_129 : f32;
    var v_130 : f32;
    var v_132 : f32;
    var v_133 : f32;
    var v_134 : f32;
    var v_135 : f32;
    var v_136 : f32;
    var v_137 : f32;
    var v_138 : f32;
    var v_139 : f32;
    var v_140 : f32;
    var v_141 : f32;
    var v_143 : f32;
    var v_144 : emu_i64;
    var v_146 : emu_i64;
    var v_149 : i32;
    var v_152 : i32;
    var v_154 : i32;
    var v_157 : f32;
    var v_158 : f32;
    var v_159 : emu_i64;
    var v_161 : emu_i64;
    var v_164 : i32;
    var v_167 : i32;
    var v_169 : i32;
    var v_172 : f32;
    var v_173 : emu_i64;
    var v_175 : emu_i64;
    var v_178 : i32;
    var v_181 : i32;
    var v_183 : i32;
    var v_80 : emu_i64;
    var v_82 : emu_i64;
    var v_86 : bool;
    var v_88 : bool;
    var v_91 : bool;
    var v_93 : bool;
    var v_95 : bool;
    var v_97 : bool;
    var v_98 : bool;
    var v_100 : bool;
    var v_104 : bool;
    var v_105 : bool;
    var v_107 : bool;
    var v_112 : bool;
    var v_114 : bool;
    var v_115 : i32;
    var v_117 : bool;
    var v_118 : bool;
    var v_120 : bool;
    var v_122 : bool;
    var v_126 : bool;
    var v_128 : bool;
    var v_131 : bool;
    var v_142 : bool;
    var v_145 : bool;
    var v_147 : bool;
    var v_148 : i32;
    var v_150 : bool;
    var v_151 : bool;
    var v_153 : bool;
    var v_155 : bool;
    var v_160 : bool;
    var v_162 : bool;
    var v_163 : i32;
    var v_165 : bool;
    var v_166 : bool;
    var v_168 : bool;
    var v_170 : bool;
    var v_174 : bool;
    var v_176 : bool;
    var v_177 : i32;
    var v_179 : bool;
    var v_180 : bool;
    var v_182 : bool;
    var v_184 : bool;













































    let v_79 = v_72_f0;
    let v_81 = v_73_f0;
    let v_83 = v_74_f0;
    let v_84 = v_75_f0;

    v_80 = v_72_f1;

    v_82 = v_73_f1;

    v_0 = v_74_f1;

    v_1 = v_75_f1;
    v_2 = v_71 / v_78;
    v_3 = v_71 % v_78;
    v_4 = f32(0.0);
    v_5 = i32(0);
    v_6 = v_2 * v_77;
    v_85 = _c_i64_0;
    v_86 = i64_ge(v_80, v_85);
    v_87 = _c_i64_1;
    v_88 = i64_le(v_80, v_87);
    v_7 = v_86 & v_88;
    v_8 = i64_to_i32(v_80);
    v_89 = i32(0);
    v_9 = v_8 == v_89;
    v_90 = _c_i64_0;
    v_91 = i64_ge(v_82, v_90);
    v_92 = _c_i64_1;
    v_93 = i64_le(v_82, v_92);
    v_10 = v_91 & v_93;
    v_11 = i64_to_i32(v_82);
    v_94 = i32(0);
    v_12 = v_11 == v_94;
    v_13 = v_5;
    v_14 = v_4;
    loop {
        v_95 = v_13 < v_77;
        if (!v_95) {
            break;
        }
        v_59 = v_6 + v_13;
        v_96 = i32(0);
        v_97 = v_59 >= v_96;
        v_98 = v_59 < v_8;
        v_60 = v_97 & v_98;
        v_99 = i32(0);
        v_100 = v_59 == v_99;
        v_61 = v_100 & v_9;
        v_62 = v_60 | v_61;
        let v_101 = &param1_f0[(i32(_scalar_params[3]) + v_59)];
        v_102 = *v_101;
        v_63 = v_13 * v_78;
        v_64 = v_63 + v_3;
        v_103 = i32(0);
        v_104 = v_64 >= v_103;
        v_105 = v_64 < v_11;
        v_65 = v_104 & v_105;
        v_106 = i32(0);
        v_107 = v_64 == v_106;
        v_66 = v_107 & v_12;
        v_67 = v_65 | v_66;
        let v_108 = &param2_f0[(i32(_scalar_params[4]) + v_64)];
        v_109 = *v_108;
        v_68 = v_102 * v_109;
        v_69 = v_14 + v_68;
        v_110 = i32(1);
        v_70 = v_13 + v_110;
        v_13 = v_70;
        v_14 = v_69;
    }
    v_111 = _c_i64_0;
    v_112 = i64_ge(v_0, v_111);
    v_113 = _c_i64_1;
    v_114 = i64_le(v_0, v_113);
    v_15 = v_112 & v_114;
    v_115 = i64_to_i32(v_0);
    v_116 = i32(0);
    v_117 = v_3 >= v_116;
    v_118 = v_3 < v_115;
    v_16 = v_117 & v_118;
    v_119 = i32(0);
    v_120 = v_3 == v_119;
    v_121 = i32(0);
    v_122 = v_115 == v_121;
    v_17 = v_120 & v_122;
    v_18 = v_16 | v_17;
    let v_123 = &param3_f0[(i32(_scalar_params[5]) + v_3)];
    v_124 = *v_123;
    v_19 = v_14 + v_124;
    v_125 = f32(10.0);
    v_126 = v_19 <= v_125;
    if (v_126) {
        v_127 = f32(-10.0);
        v_128 = v_19 >= v_127;
        if (v_128) {
            v_129 = f32(0.707106769);
            v_28 = v_19 * v_129;
            v_130 = f32(0.0);
            v_131 = v_28 < v_130;
            v_29 = -v_28;
            v_132 = select(v_28, v_29, v_131);
            v_133 = f32(1.0);
            v_134 = f32(0.327591091);
            v_30 = v_132 * v_134;
            v_31 = v_30 + v_133;
            v_32 = 1.0 / v_31;
            v_33 = v_32 * v_32;
            v_34 = v_33 * v_32;
            v_35 = v_34 * v_32;
            v_36 = v_35 * v_32;
            v_135 = f32(1.0);
            v_136 = f32(0.254829586);
            v_37 = v_32 * v_136;
            v_137 = f32(-0.284496725);
            v_38 = v_33 * v_137;
            v_39 = v_37 + v_38;
            v_138 = f32(1.42141378);
            v_40 = v_34 * v_138;
            v_41 = v_39 + v_40;
            v_139 = f32(-1.45315206);
            v_42 = v_35 * v_139;
            v_43 = v_41 + v_42;
            v_140 = f32(1.06140542);
            v_44 = v_36 * v_140;
            v_45 = v_43 + v_44;
            v_46 = -v_132;
            v_47 = v_46 * v_132;
            v_48 = exp(v_47);
            v_49 = v_45 * v_48;
            v_50 = v_135 - v_49;
            v_141 = f32(0.0);
            v_142 = v_28 < v_141;
            v_51 = -v_50;
            v_143 = select(v_50, v_51, v_142);
            v_144 = _c_i64_0;
            v_145 = i64_ge(v_1, v_144);
            v_146 = _c_i64_1;
            v_147 = i64_le(v_1, v_146);
            v_52 = v_145 & v_147;
            v_148 = i64_to_i32(v_1);
            v_149 = i32(0);
            v_150 = v_71 >= v_149;
            v_151 = v_71 < v_148;
            v_53 = v_150 & v_151;
            v_152 = i32(0);
            v_153 = v_71 == v_152;
            v_154 = i32(0);
            v_155 = v_148 == v_154;
            v_54 = v_153 & v_155;
            v_55 = v_53 | v_54;
            let v_156 = &param4_f0[(i32(_scalar_params[6]) + v_71)];
            v_157 = f32(0.5);
            v_56 = v_19 * v_157;
            v_158 = f32(1.0);
            v_57 = v_143 + v_158;
            v_58 = v_56 * v_57;
            *v_156 = v_58;
        } else {
            v_159 = _c_i64_0;
            v_160 = i64_ge(v_1, v_159);
            v_161 = _c_i64_1;
            v_162 = i64_le(v_1, v_161);
            v_24 = v_160 & v_162;
            v_163 = i64_to_i32(v_1);
            v_164 = i32(0);
            v_165 = v_71 >= v_164;
            v_166 = v_71 < v_163;
            v_25 = v_165 & v_166;
            v_167 = i32(0);
            v_168 = v_71 == v_167;
            v_169 = i32(0);
            v_170 = v_163 == v_169;
            v_26 = v_168 & v_170;
            v_27 = v_25 | v_26;
            let v_171 = &param4_f0[(i32(_scalar_params[6]) + v_71)];
            v_172 = f32(0.0);
            *v_171 = v_172;
        }
    } else {
        v_173 = _c_i64_0;
        v_174 = i64_ge(v_1, v_173);
        v_175 = _c_i64_1;
        v_176 = i64_le(v_1, v_175);
        v_20 = v_174 & v_176;
        v_177 = i64_to_i32(v_1);
        v_178 = i32(0);
        v_179 = v_71 >= v_178;
        v_180 = v_71 < v_177;
        v_21 = v_179 & v_180;
        v_181 = i32(0);
        v_182 = v_71 == v_181;
        v_183 = i32(0);
        v_184 = v_177 == v_183;
        v_22 = v_182 & v_184;
        v_23 = v_21 | v_22;
        let v_185 = &param4_f0[(i32(_scalar_params[6]) + v_71)];
        *v_185 = v_19;
    }
    return;
}
