// Kernel: LayerNormApplyImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 7
// Time: 2026-03-24T04:51:46.5550000Z

// Kernel: LayerNormApplyImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: LayerNormApplyImpl_288
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_63086 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(3) var<storage, read_write> param4_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 5: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(4) var<storage, read_write> param5_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 6: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(5) var<storage, read_write> param6_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 7: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// View offset for param2000 at scalar slot 1
// View offset for param3000 at scalar slot 2
// View offset for param4000 at scalar slot 3
// View offset for param5000 at scalar slot 4
// View offset for param6000 at scalar slot 5
// View offset for param7000 at scalar slot 6
@group(0) @binding(6) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : i32 = 0;
    var v_1 : i32 = 0;
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : bool = false;
    var v_5 : bool = false;
    var v_6 : bool = false;
    var v_7 : bool = false;
    var v_8 : bool = false;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : bool = false;
    var v_13 : bool = false;
    var v_14 : bool = false;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : bool = false;
    var v_18 : f32 = 0.0;
    var v_19 : bool = false;
    var v_20 : bool = false;
    var v_21 : bool = false;
    var v_22 : bool = false;
    var v_23 : f32 = 0.0;
    var v_24 : f32 = 0.0;
    var v_25 : bool = false;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : bool = false;
    var v_29 : f32 = 0.0;
    var v_30 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_30) >= _ilgpu_user_dim) { return; }
    let v_31_f0 = &param1_f0;
    var v_31_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_32_f0 = &param2_f0;
    var v_32_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_33_f0 = &param3_f0;
    var v_33_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    let v_34_f0 = &param4_f0;
    var v_34_f1 = i64_from_i32(i32(arrayLength(&param4_f0)));
    let v_35_f0 = &param5_f0;
    var v_35_f1 = i64_from_i32(i32(arrayLength(&param5_f0)));
    let v_36_f0 = &param6_f0;
    var v_36_f1 = i64_from_i32(i32(arrayLength(&param6_f0)));
    var v_37 = bitcast<i32>(_scalar_params[0]);
    let v_38 = v_31_f0;
    let v_39 = v_31_f1;
    let v_40 = v_32_f0;
    let v_41 = v_32_f1;
    let v_42 = v_33_f0;
    let v_43 = v_33_f1;
    let v_44 = v_34_f0;
    let v_45 = v_34_f1;
    let v_46 = v_35_f0;
    let v_47 = v_35_f1;
    let v_48 = v_36_f0;
    let v_49 = v_36_f1;
    v_0 = v_30 / v_37;
    v_1 = v_30 % v_37;
    var v_50 : emu_i64;
    v_50 = _c_i64_0;
    let v_51 = i64_ge(v_41, v_50);
    var v_52 : emu_i64;
    v_52 = _c_i64_1;
    let v_53 = i64_le(v_41, v_52);
    v_2 = v_51 & v_53;
    let v_54 = i64_to_i32(v_41);
    var v_55 : i32;
    v_55 = i32(0);
    let v_56 = v_30 >= v_55;
    let v_57 = v_30 < v_54;
    v_3 = v_56 & v_57;
    var v_58 : i32;
    v_58 = i32(0);
    let v_59 = v_30 == v_58;
    var v_60 : i32;
    v_60 = i32(0);
    let v_61 = v_54 == v_60;
    v_4 = v_59 & v_61;
    v_5 = v_3 | v_4;
    let v_62 = &param2_f0[(i32(_scalar_params[2]) + v_30)];
    var v_63 : emu_i64;
    v_63 = _c_i64_0;
    let v_64 = i64_ge(v_43, v_63);
    var v_65 : emu_i64;
    v_65 = _c_i64_1;
    let v_66 = i64_le(v_43, v_65);
    v_6 = v_64 & v_66;
    let v_67 = i64_to_i32(v_43);
    var v_68 : i32;
    v_68 = i32(0);
    let v_69 = v_1 >= v_68;
    let v_70 = v_1 < v_67;
    v_7 = v_69 & v_70;
    var v_71 : i32;
    v_71 = i32(0);
    let v_72 = v_1 == v_71;
    var v_73 : i32;
    v_73 = i32(0);
    let v_74 = v_67 == v_73;
    v_8 = v_72 & v_74;
    v_9 = v_7 | v_8;
    let v_75 = &param3_f0[(i32(_scalar_params[3]) + v_1)];
    var v_76 : f32;
    v_76 = *v_75;
    var v_77 : emu_i64;
    v_77 = _c_i64_0;
    let v_78 = i64_ge(v_39, v_77);
    var v_79 : emu_i64;
    v_79 = _c_i64_1;
    let v_80 = i64_le(v_39, v_79);
    v_10 = v_78 & v_80;
    let v_81 = i64_to_i32(v_39);
    var v_82 : i32;
    v_82 = i32(0);
    let v_83 = v_30 >= v_82;
    let v_84 = v_30 < v_81;
    v_11 = v_83 & v_84;
    var v_85 : i32;
    v_85 = i32(0);
    let v_86 = v_30 == v_85;
    var v_87 : i32;
    v_87 = i32(0);
    let v_88 = v_81 == v_87;
    v_12 = v_86 & v_88;
    v_13 = v_11 | v_12;
    let v_89 = &param1_f0[(i32(_scalar_params[1]) + v_30)];
    var v_90 : f32;
    v_90 = *v_89;
    var v_91 : emu_i64;
    v_91 = _c_i64_0;
    let v_92 = i64_ge(v_47, v_91);
    var v_93 : emu_i64;
    v_93 = _c_i64_1;
    let v_94 = i64_le(v_47, v_93);
    v_14 = v_92 & v_94;
    let v_95 = i64_to_i32(v_47);
    var v_96 : i32;
    v_96 = i32(0);
    let v_97 = v_0 >= v_96;
    let v_98 = v_0 < v_95;
    v_15 = v_97 & v_98;
    var v_99 : i32;
    v_99 = i32(0);
    let v_100 = v_0 == v_99;
    var v_101 : i32;
    v_101 = i32(0);
    let v_102 = v_95 == v_101;
    v_16 = v_100 & v_102;
    v_17 = v_15 | v_16;
    let v_103 = &param5_f0[(i32(_scalar_params[5]) + v_0)];
    var v_104 : f32;
    v_104 = *v_103;
    v_18 = v_90 - v_104;
    var v_105 : emu_i64;
    v_105 = _c_i64_0;
    let v_106 = i64_ge(v_49, v_105);
    var v_107 : emu_i64;
    v_107 = _c_i64_1;
    let v_108 = i64_le(v_49, v_107);
    v_19 = v_106 & v_108;
    let v_109 = i64_to_i32(v_49);
    var v_110 : i32;
    v_110 = i32(0);
    let v_111 = v_0 >= v_110;
    let v_112 = v_0 < v_109;
    v_20 = v_111 & v_112;
    var v_113 : i32;
    v_113 = i32(0);
    let v_114 = v_0 == v_113;
    var v_115 : i32;
    v_115 = i32(0);
    let v_116 = v_109 == v_115;
    v_21 = v_114 & v_116;
    v_22 = v_20 | v_21;
    let v_117 = &param6_f0[(i32(_scalar_params[6]) + v_0)];
    var v_118 : f32;
    v_118 = *v_117;
    v_23 = v_18 * v_118;
    v_24 = v_76 * v_23;
    var v_119 : emu_i64;
    v_119 = _c_i64_0;
    let v_120 = i64_ge(v_45, v_119);
    var v_121 : emu_i64;
    v_121 = _c_i64_1;
    let v_122 = i64_le(v_45, v_121);
    v_25 = v_120 & v_122;
    let v_123 = i64_to_i32(v_45);
    var v_124 : i32;
    v_124 = i32(0);
    let v_125 = v_1 >= v_124;
    let v_126 = v_1 < v_123;
    v_26 = v_125 & v_126;
    var v_127 : i32;
    v_127 = i32(0);
    let v_128 = v_1 == v_127;
    var v_129 : i32;
    v_129 = i32(0);
    let v_130 = v_123 == v_129;
    v_27 = v_128 & v_130;
    v_28 = v_26 | v_27;
    let v_131 = &param4_f0[(i32(_scalar_params[4]) + v_1)];
    var v_132 : f32;
    v_132 = *v_131;
    v_29 = v_24 + v_132;
    *v_62 = v_29;
        return;
}
