// Kernel: TransposeLastTwoImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 3
// Time: 2026-03-24T04:52:25.2730000Z

// Kernel: TransposeLastTwoImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: TransposeLastTwoImpl_653
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_63086 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// View offset for param2000 at scalar slot 2
// View offset for param3000 at scalar slot 3
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : i32 = 0;
    var v_1 : i32 = 0;
    var v_2 : i32 = 0;
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : i32 = 0;
    var v_6 : i32 = 0;
    var v_7 : i32 = 0;
    var v_8 : i32 = 0;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : bool = false;
    var v_13 : bool = false;
    var v_14 : bool = false;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_17) >= _ilgpu_user_dim) { return; }
    let v_18_f0 = &param1_f0;
    var v_18_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_19_f0 = &param2_f0;
    var v_19_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    var v_20 = bitcast<i32>(_scalar_params[0]);
    var v_21 = bitcast<i32>(_scalar_params[1]);
    let v_22 = v_18_f0;
    let v_23 = v_18_f1;
    let v_24 = v_19_f0;
    let v_25 = v_19_f1;
    v_0 = v_20 * v_21;
    v_1 = v_17 / v_0;
    v_2 = v_17 % v_0;
    v_3 = v_2 / v_21;
    v_4 = v_2 % v_21;
    v_5 = v_1 * v_0;
    v_6 = v_4 * v_20;
    v_7 = v_5 + v_6;
    v_8 = v_7 + v_3;
    var v_26 : emu_i64;
    v_26 = _c_i64_0;
    let v_27 = i64_ge(v_25, v_26);
    var v_28 : emu_i64;
    v_28 = _c_i64_1;
    let v_29 = i64_le(v_25, v_28);
    v_9 = v_27 & v_29;
    let v_30 = i64_to_i32(v_25);
    var v_31 : i32;
    v_31 = i32(0);
    let v_32 = v_8 >= v_31;
    let v_33 = v_8 < v_30;
    v_10 = v_32 & v_33;
    var v_34 : i32;
    v_34 = i32(0);
    let v_35 = v_8 == v_34;
    var v_36 : i32;
    v_36 = i32(0);
    let v_37 = v_30 == v_36;
    v_11 = v_35 & v_37;
    v_12 = v_10 | v_11;
    let v_38 = &param2_f0[(i32(_scalar_params[3]) + v_8)];
    var v_39 : emu_i64;
    v_39 = _c_i64_0;
    let v_40 = i64_ge(v_23, v_39);
    var v_41 : emu_i64;
    v_41 = _c_i64_1;
    let v_42 = i64_le(v_23, v_41);
    v_13 = v_40 & v_42;
    let v_43 = i64_to_i32(v_23);
    var v_44 : i32;
    v_44 = i32(0);
    let v_45 = v_17 >= v_44;
    let v_46 = v_17 < v_43;
    v_14 = v_45 & v_46;
    var v_47 : i32;
    v_47 = i32(0);
    let v_48 = v_17 == v_47;
    var v_49 : i32;
    v_49 = i32(0);
    let v_50 = v_43 == v_49;
    v_15 = v_48 & v_50;
    v_16 = v_14 | v_15;
    let v_51 = &param1_f0[(i32(_scalar_params[2]) + v_17)];
    var v_52 : f32;
    v_52 = *v_51;
    *v_38 = v_52;
        return;
}
