// Kernel: ReduceMaxImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 3
// Time: 2026-03-24T04:52:28.6500000Z

// Kernel: ReduceMaxImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: ReduceMaxImpl_775
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_63086 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param2000 at scalar slot 3
// View offset for param3000 at scalar slot 4
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : i32 = 0;
    var v_2 : i32 = 0;
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : i32 = 0;
    var v_6 : bool = false;
    var v_7 : bool = false;
    var v_8 : bool = false;
    var v_9 : bool = false;
    var v_10 : f32 = 0.0;
    var v_11 : i32 = 0;
    var v_12 : bool = false;
    var v_13 : i32 = 0;
    var v_14 : bool = false;
    var v_15 : f32 = 0.0;
    var v_16 : i32 = 0;
    var v_17 : bool = false;
    var v_18 : bool = false;
    var v_19 : bool = false;
    var v_20 : bool = false;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : bool = false;
    var v_24 : bool = false;
    var v_25 : bool = false;
    var v_26 : f32 = 0.0;
    var v_27 : f32 = 0.0;
    var v_28 : i32 = 0;
    var v_29 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_29) >= _ilgpu_user_dim) { return; }
    let v_30_f0 = &param1_f0;
    var v_30_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_31_f0 = &param2_f0;
    var v_31_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    var v_33 = bitcast<i32>(_scalar_params[1]);
    var v_34 = bitcast<i32>(_scalar_params[2]);
    var v_38 : emu_i64;
    var v_40 : emu_i64;
    var v_43 : i32;
    var v_46 : i32;
    var v_48 : i32;
    var v_51 : emu_i64;
    var v_53 : emu_i64;
    var v_55 : i32;
    var v_57 : i32;
    var v_60 : i32;
    var v_64 : i32;
    var v_65 : emu_i64;
    var v_67 : emu_i64;
    var v_70 : i32;
    var v_73 : i32;
    var v_75 : i32;
    var v_36 : emu_i64;
    var v_39 : bool;
    var v_41 : bool;
    var v_42 : i32;
    var v_44 : bool;
    var v_45 : bool;
    var v_47 : bool;
    var v_49 : bool;
    var v_52 : bool;
    var v_54 : bool;
    var v_56 : bool;
    var v_58 : bool;
    var v_59 : bool;
    var v_61 : bool;
    var v_63 : bool;
    var v_66 : bool;
    var v_68 : bool;
    var v_69 : i32;
    var v_71 : bool;
    var v_72 : bool;
    var v_74 : bool;
    var v_76 : bool;






















    let v_35 = v_30_f0;
    let v_37 = v_31_f0;

    v_36 = v_30_f1;

    v_0 = v_31_f1;
    v_1 = v_29 / v_34;
    v_2 = v_29 % v_34;
    v_3 = v_1 * v_33;
    v_4 = v_3 * v_34;
    v_5 = v_4 + v_2;
    v_38 = _c_i64_0;
    v_39 = i64_ge(v_36, v_38);
    v_40 = _c_i64_1;
    v_41 = i64_le(v_36, v_40);
    v_6 = v_39 & v_41;
    v_42 = i64_to_i32(v_36);
    v_43 = i32(0);
    v_44 = v_5 >= v_43;
    v_45 = v_5 < v_42;
    v_7 = v_44 & v_45;
    v_46 = i32(0);
    v_47 = v_5 == v_46;
    v_48 = i32(0);
    v_49 = v_42 == v_48;
    v_8 = v_47 & v_49;
    v_9 = v_7 | v_8;
    let v_50 = &param1_f0[(i32(_scalar_params[3]) + v_5)];
    v_10 = *v_50;
    v_11 = i32(1);
    v_51 = _c_i64_0;
    v_52 = i64_ge(v_36, v_51);
    v_53 = _c_i64_1;
    v_54 = i64_le(v_36, v_53);
    v_12 = v_52 & v_54;
    v_13 = i64_to_i32(v_36);
    v_55 = i32(0);
    v_14 = v_13 == v_55;
    v_15 = v_10;
    v_16 = v_11;
    loop {
        v_56 = v_16 < v_33;
        if (!v_56) {
            break;
        }
        v_21 = v_16 * v_34;
        v_22 = v_5 + v_21;
        v_57 = i32(0);
        v_58 = v_22 >= v_57;
        v_59 = v_22 < v_13;
        v_23 = v_58 & v_59;
        v_60 = i32(0);
        v_61 = v_22 == v_60;
        v_24 = v_61 & v_14;
        v_25 = v_23 | v_24;
        let v_62 = &param1_f0[(i32(_scalar_params[3]) + v_22)];
        v_26 = *v_62;
        v_63 = v_26 <= v_15;
        if (!v_63) {
            v_27 = v_26;
        } else {
            v_27 = v_15;
        }
        v_64 = i32(1);
        v_28 = v_16 + v_64;
        v_15 = v_27;
        v_16 = v_28;
    }
    v_65 = _c_i64_0;
    v_66 = i64_ge(v_0, v_65);
    v_67 = _c_i64_1;
    v_68 = i64_le(v_0, v_67);
    v_17 = v_66 & v_68;
    v_69 = i64_to_i32(v_0);
    v_70 = i32(0);
    v_71 = v_29 >= v_70;
    v_72 = v_29 < v_69;
    v_18 = v_71 & v_72;
    v_73 = i32(0);
    v_74 = v_29 == v_73;
    v_75 = i32(0);
    v_76 = v_69 == v_75;
    v_19 = v_74 & v_76;
    v_20 = v_18 | v_19;
    let v_77 = &param2_f0[(i32(_scalar_params[4]) + v_29)];
    *v_77 = v_15;
    return;
}
