// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T03:39:23.7010000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_31176 {
    int field_0;
    uvec2 field_1;
    int field_2;
};

struct struct_31181 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp isampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp int u_param2_length; // element count
uniform highp sampler2D u_param3; // buffer param[3]
uniform highp int u_param3_tileW;
uniform highp int u_param3_offset;
uniform highp int u_param3_length; // element count

out highp float tf_out_2; // TF output for param[2]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    
    uvec2 v_3 = uvec2(0u);
    uvec2 v_4 = uvec2(0u);
    uvec2 v_5 = uvec2(0u);
    int v_6 = 0;
    uvec2 v_7 = uvec2(0u);
    bool v_8 = false;
    uvec2 v_9 = uvec2(0u);
    bool v_10 = false;
    bool v_11 = false;
    int v_12 = 0;
    int v_13 = 0;
    bool v_14 = false;
    bool v_15 = false;
    int v_16 = 0;
    bool v_17 = false;
    int v_18 = 0;
    bool v_19 = false;
    bool v_20 = false;
    float v_21 = 0.0;
    int v_22 = 0;
    int v_23 = 0;
    uvec2 v_24 = uvec2(0u);
    bool v_25 = false;
    uvec2 v_26 = uvec2(0u);
    bool v_27 = false;
    bool v_28 = false;
    int v_29 = 0;
    int v_30 = 0;
    bool v_31 = false;
    bool v_32 = false;
    int v_33 = 0;
    bool v_34 = false;
    int v_35 = 0;
    bool v_36 = false;
    float v_37 = 0.0;
    int v_38 = 0;
    int v_39 = 0;
    uvec2 v_40 = uvec2(0u);
    bool v_41 = false;
    uvec2 v_42 = uvec2(0u);
    bool v_43 = false;
    bool v_44 = false;
    int v_45 = 0;
    int v_46 = 0;
    bool v_47 = false;
    bool v_48 = false;
    int v_49 = 0;
    bool v_50 = false;
    int v_51 = 0;
    bool v_52 = false;
    float v_53 = 0.0;
    int v_54 = 0;
    int v_55 = 0;
    uvec2 v_56 = uvec2(0u);
    bool v_57 = false;
    uvec2 v_58 = uvec2(0u);
    bool v_59 = false;
    bool v_60 = false;
    int v_61 = 0;
    int v_62 = 0;
    bool v_63 = false;
    bool v_64 = false;
    int v_65 = 0;
    bool v_66 = false;
    int v_67 = 0;
    bool v_68 = false;
    float v_69 = 0.0;
    int v_70 = 0;
    int v_71 = 0;
    int v_72 = 0;
    int v_73 = 0;
    int v_74 = 0;
    int v_75 = 0;
    float v_76 = 0.0;
    float v_77 = 0.0;
    float v_78 = 0.0;
    float v_79 = 0.0;
    float v_80 = 0.0;
    float v_81 = 0.0;
    float v_82 = 0.0;
    float v_83 = 0.0;
    float v_84 = 0.0;
    float v_85 = 0.0;
    float v_86 = 0.0;
    float v_87 = 0.0;
    float v_88 = 0.0;
    float v_89 = 0.0;
    float v_90 = 0.0;
    float v_91 = 0.0;
    float v_92 = 0.0;
    float v_93 = 0.0;
    int v_94 = 0;
    int v_95 = 0;
    int v_96 = 0;
    int v_97 = 0;
    int v_98 = 0;
    int v_99 = 0;
    float v_100 = 0.0;
    float v_101 = 0.0;
    float v_102 = 0.0;
    float v_103 = 0.0;
    int v_104 = 0;
    bool v_105 = false;
    int v_106 = 0;
    int v_107 = 0;
    bool v_108 = false;
    int v_109 = 0;
    int v_110 = 0;
    int v_111 = 0;
    int v_112 = 0;
    bool v_113 = false;
    int v_114 = 0;
    int v_115 = 0;
    bool v_116 = false;
    int v_117 = 0;
    int v_118 = 0;
    int v_119 = 0;
    int v_120 = 0;
    int v_121 = 0;
    int v_122 = 0;
    int v_123 = 0;
    uvec2 v_124 = uvec2(0u);
    bool v_125 = false;
    uvec2 v_126 = uvec2(0u);
    bool v_127 = false;
    bool v_128 = false;
    int v_129 = 0;
    int v_130 = 0;
    bool v_131 = false;
    bool v_132 = false;
    bool v_133 = false;
    int v_134 = 0;
    bool v_135 = false;
    int v_136 = 0;
    bool v_137 = false;
    bool v_138 = false;
    bool v_139 = false;
    int v_140 = 0;
    int v_141 = 0;
    int v_142 = 0;
    int v_143 = 0;
    int v_144 = 0;
    int v_145 = 0;
    float v_146 = 0.0;
    float v_147 = 0.0;
    float v_148 = 0.0;
    int v_149 = 0;
    int v_150 = 0;
    uvec2 v_151 = uvec2(0u);
    bool v_152 = false;
    uvec2 v_153 = uvec2(0u);
    bool v_154 = false;
    bool v_155 = false;
    int v_156 = 0;
    int v_157 = 0;
    bool v_158 = false;
    bool v_159 = false;
    bool v_160 = false;
    int v_161 = 0;
    bool v_162 = false;
    int v_163 = 0;
    bool v_164 = false;
    bool v_165 = false;
    bool v_166 = false;
    int v_167 = 0;
    int v_168 = 0;
    int v_169 = 0;
    int v_170 = 0;
    int v_171 = 0;
    int v_172 = 0;
    float v_173 = 0.0;
    float v_174 = 0.0;
    float v_175 = 0.0;
    int v_176 = 0;
    int v_177 = 0;
    uvec2 v_178 = uvec2(0u);
    bool v_179 = false;
    uvec2 v_180 = uvec2(0u);
    bool v_181 = false;
    bool v_182 = false;
    int v_183 = 0;
    int v_184 = 0;
    bool v_185 = false;
    bool v_186 = false;
    bool v_187 = false;
    int v_188 = 0;
    bool v_189 = false;
    int v_190 = 0;
    bool v_191 = false;
    bool v_192 = false;
    bool v_193 = false;
    int v_194 = 0;
    int v_195 = 0;
    int v_196 = 0;
    int v_197 = 0;
    int v_198 = 0;
    int v_199 = 0;
    float v_200 = 0.0;
    float v_201 = 0.0;
    float v_202 = 0.0;
    int v_203 = 0;
    int v_204 = 0;
    uvec2 v_205 = uvec2(0u);
    bool v_206 = false;
    uvec2 v_207 = uvec2(0u);
    bool v_208 = false;
    bool v_209 = false;
    int v_210 = 0;
    int v_211 = 0;
    bool v_212 = false;
    bool v_213 = false;
    bool v_214 = false;
    int v_215 = 0;
    bool v_216 = false;
    int v_217 = 0;
    bool v_218 = false;
    bool v_219 = false;
    bool v_220 = false;
    int v_221 = 0;
    int v_222 = 0;
    int v_223 = 0;
    int v_224 = 0;
    int v_225 = 0;
    int v_226 = 0;
    float v_227 = 0.0;
    float v_228 = 0.0;
    float v_229 = 0.0;
    float v_230 = 0.0;
    float v_231 = 0.0;
    float v_232 = 0.0;
    float v_233 = 0.0;
    float v_234 = 0.0;
    float v_235 = 0.0;
    float v_236 = 0.0;
    float v_237 = 0.0;
    float v_238 = 0.0;
    float v_239 = 0.0;
    float v_240 = 0.0;
    float v_241 = 0.0;
    float v_242 = 0.0;
    float v_243 = 0.0;
    float v_244 = 0.0;
    float v_245 = 0.0;
    float v_246 = 0.0;
    float v_247 = 0.0;
    float v_248 = 0.0;
    int v_249 = 0;
    int v_250 = 0;
    uvec2 v_251 = uvec2(0u);
    bool v_252 = false;
    uvec2 v_253 = uvec2(0u);
    bool v_254 = false;
    bool v_255 = false;
    int v_256 = 0;
    int v_257 = 0;
    bool v_258 = false;
    bool v_259 = false;
    bool v_260 = false;
    int v_261 = 0;
    bool v_262 = false;
    int v_263 = 0;
    bool v_264 = false;
    bool v_265 = false;
    bool v_266 = false;
    float v_267 = 0.0;
    int v_268 = 0;
    int v_269 = 0;
    uvec2 v_270 = uvec2(0u);
    bool v_271 = false;
    uvec2 v_272 = uvec2(0u);
    bool v_273 = false;
    bool v_274 = false;
    int v_275 = 0;
    int v_276 = 0;
    bool v_277 = false;
    bool v_278 = false;
    bool v_279 = false;
    int v_280 = 0;
    bool v_281 = false;
    int v_282 = 0;
    bool v_283 = false;
    bool v_284 = false;
    bool v_285 = false;
    float v_286 = 0.0;
    uvec2 v_287 = uvec2(0u);
    bool v_288 = false;
    uvec2 v_289 = uvec2(0u);
    bool v_290 = false;
    bool v_291 = false;
    int v_292 = 0;
    int v_293 = 0;
    bool v_294 = false;
    bool v_295 = false;
    bool v_296 = false;
    int v_297 = 0;
    bool v_298 = false;
    int v_299 = 0;
    bool v_300 = false;
    bool v_301 = false;
    bool v_302 = false;
    float v_303 = 0.0;
    float v_304 = 0.0;
    // v_305 = buffer alias for param1
    v_3 = uvec2(0u);
    // v_306 = buffer alias for param2
    v_4 = uvec2(0u);
    // v_307 = buffer alias for param3
    v_5 = uvec2(0u);
    v_6 = int(0);
    v_7 = uvec2(2147483648u, 4294967295u);
    v_8 = i64_ge(v_5, v_7);
    v_9 = uvec2(2147483647u, 0u);
    v_10 = i64_le(v_5, v_9);
    v_11 = v_8 && v_10;
    // String: 32-bit index out of range
    v_12 = i64_to_i32(v_5);
    v_13 = int(0);
    v_14 = true;
    v_15 = v_12 > v_6;
    v_16 = int(0);
    v_17 = true;
    v_18 = int(0);
    v_19 = v_12 == v_18;
    v_20 = v_15 || v_19;
    // String: X index out of bounds
    int v_308 = int(v_6); // LEA into param3
    v_21 = float(texelFetch(u_param3, ivec2((int(v_308) + u_param3_offset) % u_param3_tileW, (int(v_308) + u_param3_offset) / u_param3_tileW), 0).r);
    v_22 = int(v_21);
    v_23 = int(1);
    v_24 = uvec2(2147483648u, 4294967295u);
    v_25 = i64_ge(v_5, v_24);
    v_26 = uvec2(2147483647u, 0u);
    v_27 = i64_le(v_5, v_26);
    v_28 = v_25 && v_27;
    // String: 32-bit index out of range
    v_29 = i64_to_i32(v_5);
    v_30 = int(0);
    v_31 = true;
    v_32 = v_29 > v_23;
    v_33 = int(0);
    v_34 = false;
    v_35 = int(0);
    v_36 = v_29 == v_35;
    // String: X index out of bounds
    int v_309 = int(v_23); // LEA into param3
    v_37 = float(texelFetch(u_param3, ivec2((int(v_309) + u_param3_offset) % u_param3_tileW, (int(v_309) + u_param3_offset) / u_param3_tileW), 0).r);
    v_38 = int(v_37);
    v_39 = int(2);
    v_40 = uvec2(2147483648u, 4294967295u);
    v_41 = i64_ge(v_5, v_40);
    v_42 = uvec2(2147483647u, 0u);
    v_43 = i64_le(v_5, v_42);
    v_44 = v_41 && v_43;
    // String: 32-bit index out of range
    v_45 = i64_to_i32(v_5);
    v_46 = int(0);
    v_47 = true;
    v_48 = v_45 > v_39;
    v_49 = int(0);
    v_50 = false;
    v_51 = int(0);
    v_52 = v_45 == v_51;
    // String: X index out of bounds
    int v_310 = int(v_39); // LEA into param3
    v_53 = float(texelFetch(u_param3, ivec2((int(v_310) + u_param3_offset) % u_param3_tileW, (int(v_310) + u_param3_offset) / u_param3_tileW), 0).r);
    v_54 = int(v_53);
    v_55 = int(3);
    v_56 = uvec2(2147483648u, 4294967295u);
    v_57 = i64_ge(v_5, v_56);
    v_58 = uvec2(2147483647u, 0u);
    v_59 = i64_le(v_5, v_58);
    v_60 = v_57 && v_59;
    // String: 32-bit index out of range
    v_61 = i64_to_i32(v_5);
    v_62 = int(0);
    v_63 = true;
    v_64 = v_61 > v_55;
    v_65 = int(0);
    v_66 = false;
    v_67 = int(0);
    v_68 = v_61 == v_67;
    // String: X index out of bounds
    int v_311 = int(v_55); // LEA into param3
    v_69 = float(texelFetch(u_param3, ivec2((int(v_311) + u_param3_offset) % u_param3_tileW, (int(v_311) + u_param3_offset) / u_param3_tileW), 0).r);
    v_70 = int(v_69);
    v_71 = v_70 * v_54;
    v_72 = _idx / v_71;
    v_73 = _idx % v_71;
    v_74 = v_73 / v_54;
    v_75 = v_73 % v_54;
    v_76 = float(v_74);
    v_77 = float(0.5);
    v_78 = v_76 + v_77;
    v_79 = float(v_38);
    v_80 = v_78 * v_79;
    v_81 = float(v_70);
    v_82 = v_80 / v_81;
    v_83 = float(0.5);
    v_84 = v_82 - v_83;
    v_85 = float(v_75);
    v_86 = float(0.5);
    v_87 = v_85 + v_86;
    v_88 = float(v_22);
    v_89 = v_87 * v_88;
    v_90 = float(v_54);
    v_91 = v_89 / v_90;
    v_92 = float(0.5);
    v_93 = v_91 - v_92;
    v_94 = int(v_84);
    v_95 = int(1);
    v_96 = v_94 + v_95;
    v_97 = int(v_93);
    v_98 = int(1);
    v_99 = v_97 + v_98;
    v_100 = float(v_94);
    v_101 = v_84 - v_100;
    v_102 = float(v_97);
    v_103 = v_93 - v_102;
    v_104 = int(0);
    v_105 = v_94 >= v_104;
    v_107 = v_94;
    if (v_105) {
    } else {
        v_106 = int(0);
        v_107 = v_106;
    }
    v_108 = v_96 < v_38;
    v_109 = int(1);
    v_110 = v_38 - v_109;
    v_111 = v_108 ? v_96 : v_110;
    v_112 = int(0);
    v_113 = v_97 >= v_112;
    v_114 = int(0);
    v_115 = v_113 ? v_97 : v_114;
    v_116 = v_99 < v_22;
    v_117 = int(1);
    v_118 = v_22 - v_117;
    v_119 = v_116 ? v_99 : v_118;
    v_120 = int(3);
    v_121 = v_72 << v_120;
    v_122 = v_107 * v_22;
    v_123 = v_122 + v_115;
    v_124 = uvec2(2147483648u, 4294967295u);
    v_125 = i64_ge(v_3, v_124);
    v_126 = uvec2(2147483647u, 0u);
    v_127 = i64_le(v_3, v_126);
    v_128 = v_125 && v_127;
    // String: 32-bit index out of range
    v_129 = i64_to_i32(v_3);
    v_130 = int(0);
    v_131 = v_123 >= v_130;
    v_132 = v_123 < v_129;
    v_133 = v_131 && v_132;
    v_134 = int(0);
    v_135 = v_123 == v_134;
    v_136 = int(0);
    v_137 = v_129 == v_136;
    v_138 = v_135 && v_137;
    v_139 = v_133 || v_138;
    // String: X index out of bounds
    int v_312 = int(v_123); // LEA into param1
    v_140 = int(texelFetch(u_param1, ivec2((int(v_312) + u_param1_offset) % u_param1_tileW, (int(v_312) + u_param1_offset) / u_param1_tileW), 0).r);
    v_141 = int(31);
    v_142 = v_121 & v_141;
    v_143 = v_140 >> v_142;
    v_144 = int(255);
    v_145 = v_143 & v_144;
    v_146 = float(v_145);
    v_147 = float(255.0);
    v_148 = v_146 / v_147;
    v_149 = v_107 * v_22;
    v_150 = v_149 + v_119;
    v_151 = uvec2(2147483648u, 4294967295u);
    v_152 = i64_ge(v_3, v_151);
    v_153 = uvec2(2147483647u, 0u);
    v_154 = i64_le(v_3, v_153);
    v_155 = v_152 && v_154;
    // String: 32-bit index out of range
    v_156 = i64_to_i32(v_3);
    v_157 = int(0);
    v_158 = v_150 >= v_157;
    v_159 = v_150 < v_156;
    v_160 = v_158 && v_159;
    v_161 = int(0);
    v_162 = v_150 == v_161;
    v_163 = int(0);
    v_164 = v_156 == v_163;
    v_165 = v_162 && v_164;
    v_166 = v_160 || v_165;
    // String: X index out of bounds
    int v_313 = int(v_150); // LEA into param1
    v_167 = int(texelFetch(u_param1, ivec2((int(v_313) + u_param1_offset) % u_param1_tileW, (int(v_313) + u_param1_offset) / u_param1_tileW), 0).r);
    v_168 = int(31);
    v_169 = v_121 & v_168;
    v_170 = v_167 >> v_169;
    v_171 = int(255);
    v_172 = v_170 & v_171;
    v_173 = float(v_172);
    v_174 = float(255.0);
    v_175 = v_173 / v_174;
    v_176 = v_111 * v_22;
    v_177 = v_176 + v_115;
    v_178 = uvec2(2147483648u, 4294967295u);
    v_179 = i64_ge(v_3, v_178);
    v_180 = uvec2(2147483647u, 0u);
    v_181 = i64_le(v_3, v_180);
    v_182 = v_179 && v_181;
    // String: 32-bit index out of range
    v_183 = i64_to_i32(v_3);
    v_184 = int(0);
    v_185 = v_177 >= v_184;
    v_186 = v_177 < v_183;
    v_187 = v_185 && v_186;
    v_188 = int(0);
    v_189 = v_177 == v_188;
    v_190 = int(0);
    v_191 = v_183 == v_190;
    v_192 = v_189 && v_191;
    v_193 = v_187 || v_192;
    // String: X index out of bounds
    int v_314 = int(v_177); // LEA into param1
    v_194 = int(texelFetch(u_param1, ivec2((int(v_314) + u_param1_offset) % u_param1_tileW, (int(v_314) + u_param1_offset) / u_param1_tileW), 0).r);
    v_195 = int(31);
    v_196 = v_121 & v_195;
    v_197 = v_194 >> v_196;
    v_198 = int(255);
    v_199 = v_197 & v_198;
    v_200 = float(v_199);
    v_201 = float(255.0);
    v_202 = v_200 / v_201;
    v_203 = v_111 * v_22;
    v_204 = v_203 + v_119;
    v_205 = uvec2(2147483648u, 4294967295u);
    v_206 = i64_ge(v_3, v_205);
    v_207 = uvec2(2147483647u, 0u);
    v_208 = i64_le(v_3, v_207);
    v_209 = v_206 && v_208;
    // String: 32-bit index out of range
    v_210 = i64_to_i32(v_3);
    v_211 = int(0);
    v_212 = v_204 >= v_211;
    v_213 = v_204 < v_210;
    v_214 = v_212 && v_213;
    v_215 = int(0);
    v_216 = v_204 == v_215;
    v_217 = int(0);
    v_218 = v_210 == v_217;
    v_219 = v_216 && v_218;
    v_220 = v_214 || v_219;
    // String: X index out of bounds
    int v_315 = int(v_204); // LEA into param1
    v_221 = int(texelFetch(u_param1, ivec2((int(v_315) + u_param1_offset) % u_param1_tileW, (int(v_315) + u_param1_offset) / u_param1_tileW), 0).r);
    v_222 = int(31);
    v_223 = v_121 & v_222;
    v_224 = v_221 >> v_223;
    v_225 = int(255);
    v_226 = v_224 & v_225;
    v_227 = float(v_226);
    v_228 = float(255.0);
    v_229 = v_227 / v_228;
    v_230 = float(1.0);
    v_231 = v_230 - v_101;
    v_232 = v_148 * v_231;
    v_233 = float(1.0);
    v_234 = v_233 - v_103;
    v_235 = v_232 * v_234;
    v_236 = float(1.0);
    v_237 = v_236 - v_101;
    v_238 = v_175 * v_237;
    v_239 = v_238 * v_103;
    v_240 = v_235 + v_239;
    v_241 = v_202 * v_101;
    v_242 = float(1.0);
    v_243 = v_242 - v_103;
    v_244 = v_241 * v_243;
    v_245 = v_240 + v_244;
    v_246 = v_229 * v_101;
    v_247 = v_246 * v_103;
    v_248 = v_245 + v_247;
    v_249 = int(4);
    v_250 = v_72 + v_249;
    v_251 = uvec2(2147483648u, 4294967295u);
    v_252 = i64_ge(v_5, v_251);
    v_253 = uvec2(2147483647u, 0u);
    v_254 = i64_le(v_5, v_253);
    v_255 = v_252 && v_254;
    // String: 32-bit index out of range
    v_256 = i64_to_i32(v_5);
    v_257 = int(0);
    v_258 = v_250 >= v_257;
    v_259 = v_250 < v_256;
    v_260 = v_258 && v_259;
    v_261 = int(0);
    v_262 = v_250 == v_261;
    v_263 = int(0);
    v_264 = v_256 == v_263;
    v_265 = v_262 && v_264;
    v_266 = v_260 || v_265;
    // String: X index out of bounds
    int v_316 = int(v_250); // LEA into param3
    v_267 = float(texelFetch(u_param3, ivec2((int(v_316) + u_param3_offset) % u_param3_tileW, (int(v_316) + u_param3_offset) / u_param3_tileW), 0).r);
    v_268 = int(7);
    v_269 = v_72 + v_268;
    v_270 = uvec2(2147483648u, 4294967295u);
    v_271 = i64_ge(v_5, v_270);
    v_272 = uvec2(2147483647u, 0u);
    v_273 = i64_le(v_5, v_272);
    v_274 = v_271 && v_273;
    // String: 32-bit index out of range
    v_275 = i64_to_i32(v_5);
    v_276 = int(0);
    v_277 = v_269 >= v_276;
    v_278 = v_269 < v_275;
    v_279 = v_277 && v_278;
    v_280 = int(0);
    v_281 = v_269 == v_280;
    v_282 = int(0);
    v_283 = v_275 == v_282;
    v_284 = v_281 && v_283;
    v_285 = v_279 || v_284;
    // String: X index out of bounds
    int v_317 = int(v_269); // LEA into param3
    v_286 = float(texelFetch(u_param3, ivec2((int(v_317) + u_param3_offset) % u_param3_tileW, (int(v_317) + u_param3_offset) / u_param3_tileW), 0).r);
    v_287 = uvec2(2147483648u, 4294967295u);
    v_288 = i64_ge(v_4, v_287);
    v_289 = uvec2(2147483647u, 0u);
    v_290 = i64_le(v_4, v_289);
    v_291 = v_288 && v_290;
    // String: 32-bit index out of range
    v_292 = i64_to_i32(v_4);
    v_293 = int(0);
    v_294 = _idx >= v_293;
    v_295 = _idx < v_292;
    v_296 = v_294 && v_295;
    v_297 = int(0);
    v_298 = _idx == v_297;
    v_299 = int(0);
    v_300 = v_292 == v_299;
    v_301 = v_298 && v_300;
    v_302 = v_296 || v_301;
    // String: X index out of bounds
    int v_318 = int(_idx); // LEA into param2
    v_303 = v_248 - v_267;
    v_304 = v_303 * v_286;
    tf_out_2 = v_304;
    return;
}
