// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T00:44:36.1220000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_367760 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp sampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp int u_param2_length; // element count
uniform highp int u_param3_length; // element count
uniform highp int u_param4_length; // element count
uniform highp int u_param5; // scalar param[5]

out highp float tf_out_2; // TF output for param[2]
out highp float tf_out_3; // TF output for param[3]
out highp float tf_out_4; // TF output for param[4]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    // param4 is buffer (accessed via u_param4)
    int v_4;
    v_4 = u_param5;
    
    // v_5 = buffer alias for param1
    uvec2 v_6 = uvec2(0u);
    // v_7 = buffer alias for param2
    uvec2 v_8 = uvec2(0u);
    // v_9 = buffer alias for param3
    uvec2 v_10 = uvec2(0u);
    // v_11 = buffer alias for param4
    uvec2 v_12 = uvec2(0u);
    int v_13;
    v_13 = int(64);
    int v_14 = _idx % v_13;
    int v_15;
    v_15 = int(6);
    int v_16 = _idx >> v_15;
    int v_17 = v_16 % v_4;
    int v_18;
    v_18 = int(6);
    int v_19 = v_4 << v_18;
    int v_20 = _idx / v_19;
    int v_21;
    v_21 = int(1152);
    int v_22 = v_17 * v_21;
    uvec2 v_23;
    v_23 = uvec2(2147483648u, 4294967295u);
    bool v_24 = i64_ge(v_8, v_23);
    uvec2 v_25;
    v_25 = uvec2(2147483647u, 0u);
    bool v_26 = i64_le(v_8, v_25);
    bool v_27 = v_24 && v_26;
    // String: 32-bit index out of range
    int v_28 = i64_to_i32(v_8);
    int v_29;
    v_29 = int(0);
    bool v_30 = _idx >= v_29;
    bool v_31 = _idx < v_28;
    bool v_32 = v_30 && v_31;
    int v_33;
    v_33 = int(0);
    bool v_34 = _idx == v_33;
    int v_35;
    v_35 = int(0);
    bool v_36 = v_28 == v_35;
    bool v_37 = v_34 && v_36;
    bool v_38 = v_32 || v_37;
    // String: X index out of bounds
    int v_39 = int(_idx); // LEA into param2
    int v_40;
    v_40 = int(6);
    int v_41 = v_20 << v_40;
    int v_42 = v_22 + v_41;
    int v_43 = v_42 + v_14;
    uvec2 v_44;
    v_44 = uvec2(2147483648u, 4294967295u);
    bool v_45 = i64_ge(v_6, v_44);
    uvec2 v_46;
    v_46 = uvec2(2147483647u, 0u);
    bool v_47 = i64_le(v_6, v_46);
    bool v_48 = v_45 && v_47;
    // String: 32-bit index out of range
    int v_49 = i64_to_i32(v_6);
    int v_50;
    v_50 = int(0);
    bool v_51 = v_43 >= v_50;
    bool v_52 = v_43 < v_49;
    bool v_53 = v_51 && v_52;
    int v_54;
    v_54 = int(0);
    bool v_55 = v_43 == v_54;
    int v_56;
    v_56 = int(0);
    bool v_57 = v_49 == v_56;
    bool v_58 = v_55 && v_57;
    bool v_59 = v_53 || v_58;
    // String: X index out of bounds
    int v_60 = int(v_43); // LEA into param1
    float v_61;
    v_61 = float(texelFetch(u_param1, ivec2((int(v_60) + u_param1_offset) % u_param1_tileW, (int(v_60) + u_param1_offset) / u_param1_tileW), 0).r);
    tf_out_2 = v_61;
    uvec2 v_62;
    v_62 = uvec2(2147483648u, 4294967295u);
    bool v_63 = i64_ge(v_10, v_62);
    uvec2 v_64;
    v_64 = uvec2(2147483647u, 0u);
    bool v_65 = i64_le(v_10, v_64);
    bool v_66 = v_63 && v_65;
    // String: 32-bit index out of range
    int v_67 = i64_to_i32(v_10);
    int v_68;
    v_68 = int(0);
    bool v_69 = _idx >= v_68;
    bool v_70 = _idx < v_67;
    bool v_71 = v_69 && v_70;
    int v_72;
    v_72 = int(0);
    bool v_73 = _idx == v_72;
    int v_74;
    v_74 = int(0);
    bool v_75 = v_67 == v_74;
    bool v_76 = v_73 && v_75;
    bool v_77 = v_71 || v_76;
    // String: X index out of bounds
    int v_78 = int(_idx); // LEA into param3
    int v_79;
    v_79 = int(384);
    int v_80 = v_22 + v_79;
    int v_81;
    v_81 = int(6);
    int v_82 = v_20 << v_81;
    int v_83 = v_80 + v_82;
    int v_84 = v_83 + v_14;
    uvec2 v_85;
    v_85 = uvec2(2147483648u, 4294967295u);
    bool v_86 = i64_ge(v_6, v_85);
    uvec2 v_87;
    v_87 = uvec2(2147483647u, 0u);
    bool v_88 = i64_le(v_6, v_87);
    bool v_89 = v_86 && v_88;
    // String: 32-bit index out of range
    int v_90 = i64_to_i32(v_6);
    int v_91;
    v_91 = int(0);
    bool v_92 = v_84 >= v_91;
    bool v_93 = v_84 < v_90;
    bool v_94 = v_92 && v_93;
    int v_95;
    v_95 = int(0);
    bool v_96 = v_84 == v_95;
    int v_97;
    v_97 = int(0);
    bool v_98 = v_90 == v_97;
    bool v_99 = v_96 && v_98;
    bool v_100 = v_94 || v_99;
    // String: X index out of bounds
    int v_101 = int(v_84); // LEA into param1
    float v_102;
    v_102 = float(texelFetch(u_param1, ivec2((int(v_101) + u_param1_offset) % u_param1_tileW, (int(v_101) + u_param1_offset) / u_param1_tileW), 0).r);
    tf_out_3 = v_102;
    uvec2 v_103;
    v_103 = uvec2(2147483648u, 4294967295u);
    bool v_104 = i64_ge(v_12, v_103);
    uvec2 v_105;
    v_105 = uvec2(2147483647u, 0u);
    bool v_106 = i64_le(v_12, v_105);
    bool v_107 = v_104 && v_106;
    // String: 32-bit index out of range
    int v_108 = i64_to_i32(v_12);
    int v_109;
    v_109 = int(0);
    bool v_110 = _idx >= v_109;
    bool v_111 = _idx < v_108;
    bool v_112 = v_110 && v_111;
    int v_113;
    v_113 = int(0);
    bool v_114 = _idx == v_113;
    int v_115;
    v_115 = int(0);
    bool v_116 = v_108 == v_115;
    bool v_117 = v_114 && v_116;
    bool v_118 = v_112 || v_117;
    // String: X index out of bounds
    int v_119 = int(_idx); // LEA into param4
    int v_120;
    v_120 = int(768);
    int v_121 = v_22 + v_120;
    int v_122;
    v_122 = int(6);
    int v_123 = v_20 << v_122;
    int v_124 = v_121 + v_123;
    int v_125 = v_124 + v_14;
    uvec2 v_126;
    v_126 = uvec2(2147483648u, 4294967295u);
    bool v_127 = i64_ge(v_6, v_126);
    uvec2 v_128;
    v_128 = uvec2(2147483647u, 0u);
    bool v_129 = i64_le(v_6, v_128);
    bool v_130 = v_127 && v_129;
    // String: 32-bit index out of range
    int v_131 = i64_to_i32(v_6);
    int v_132;
    v_132 = int(0);
    bool v_133 = v_125 >= v_132;
    bool v_134 = v_125 < v_131;
    bool v_135 = v_133 && v_134;
    int v_136;
    v_136 = int(0);
    bool v_137 = v_125 == v_136;
    int v_138;
    v_138 = int(0);
    bool v_139 = v_131 == v_138;
    bool v_140 = v_137 && v_139;
    bool v_141 = v_135 || v_140;
    // String: X index out of bounds
    int v_142 = int(v_125); // LEA into param1
    float v_143;
    v_143 = float(texelFetch(u_param1, ivec2((int(v_142) + u_param1_offset) % u_param1_tileW, (int(v_142) + u_param1_offset) / u_param1_tileW), 0).r);
    tf_out_4 = v_143;
}
