// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T00:44:37.9020000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_367760 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

struct struct_367774 {
    int field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp sampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp int u_param2_length; // element count
uniform highp isampler2D u_param3; // buffer param[3]
uniform highp int u_param3_tileW;
uniform highp int u_param3_offset;
uniform highp int u_param3_length; // element count

out highp float tf_out_2; // TF output for param[2]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    
    uvec2 v_3 = uvec2(0u);
    uvec2 v_4 = uvec2(0u);
    uvec2 v_5 = uvec2(0u);
    int v_6 = 0;
    uvec2 v_7 = uvec2(0u);
    bool v_8 = false;
    uvec2 v_9 = uvec2(0u);
    bool v_10 = false;
    bool v_11 = false;
    int v_12 = 0;
    bool v_13 = false;
    int v_14 = 0;
    bool v_15 = false;
    bool v_16 = false;
    int v_17 = 0;
    uvec2 v_18 = uvec2(0u);
    bool v_19 = false;
    uvec2 v_20 = uvec2(0u);
    bool v_21 = false;
    bool v_22 = false;
    int v_23 = 0;
    bool v_24 = false;
    int v_25 = 0;
    int v_26 = 0;
    uvec2 v_27 = uvec2(0u);
    bool v_28 = false;
    uvec2 v_29 = uvec2(0u);
    bool v_30 = false;
    bool v_31 = false;
    int v_32 = 0;
    bool v_33 = false;
    int v_34 = 0;
    int v_35 = 0;
    uvec2 v_36 = uvec2(0u);
    bool v_37 = false;
    uvec2 v_38 = uvec2(0u);
    bool v_39 = false;
    bool v_40 = false;
    int v_41 = 0;
    bool v_42 = false;
    int v_43 = 0;
    int v_44 = 0;
    uvec2 v_45 = uvec2(0u);
    bool v_46 = false;
    uvec2 v_47 = uvec2(0u);
    bool v_48 = false;
    bool v_49 = false;
    int v_50 = 0;
    bool v_51 = false;
    int v_52 = 0;
    int v_53 = 0;
    uvec2 v_54 = uvec2(0u);
    bool v_55 = false;
    uvec2 v_56 = uvec2(0u);
    bool v_57 = false;
    bool v_58 = false;
    int v_59 = 0;
    bool v_60 = false;
    int v_61 = 0;
    int v_62 = 0;
    uvec2 v_63 = uvec2(0u);
    bool v_64 = false;
    uvec2 v_65 = uvec2(0u);
    bool v_66 = false;
    bool v_67 = false;
    int v_68 = 0;
    bool v_69 = false;
    int v_70 = 0;
    int v_71 = 0;
    uvec2 v_72 = uvec2(0u);
    bool v_73 = false;
    uvec2 v_74 = uvec2(0u);
    bool v_75 = false;
    bool v_76 = false;
    int v_77 = 0;
    bool v_78 = false;
    int v_79 = 0;
    int v_80 = 0;
    uvec2 v_81 = uvec2(0u);
    bool v_82 = false;
    uvec2 v_83 = uvec2(0u);
    bool v_84 = false;
    bool v_85 = false;
    int v_86 = 0;
    bool v_87 = false;
    int v_88 = 0;
    int v_89 = 0;
    uvec2 v_90 = uvec2(0u);
    bool v_91 = false;
    uvec2 v_92 = uvec2(0u);
    bool v_93 = false;
    bool v_94 = false;
    int v_95 = 0;
    bool v_96 = false;
    int v_97 = 0;
    int v_98 = 0;
    int v_99 = 0;
    int v_100 = 0;
    int v_101 = 0;
    int v_102 = 0;
    int v_103 = 0;
    int v_104 = 0;
    int v_105 = 0;
    int v_106 = 0;
    int v_107 = 0;
    int v_108 = 0;
    int v_109 = 0;
    int v_110 = 0;
    int v_111 = 0;
    int v_112 = 0;
    int v_113 = 0;
    int v_114 = 0;
    int v_115 = 0;
    int v_116 = 0;
    int v_117 = 0;
    float v_118 = 0.0;
    int v_119 = 0;
    int v_120 = 0;
    int v_121 = 0;
    int v_122 = 0;
    int v_123 = 0;
    int v_124 = 0;
    int v_125 = 0;
    uvec2 v_126 = uvec2(0u);
    bool v_127 = false;
    uvec2 v_128 = uvec2(0u);
    bool v_129 = false;
    bool v_130 = false;
    int v_131 = 0;
    int v_132 = 0;
    bool v_133 = false;
    float v_134 = 0.0;
    int v_135 = 0;
    int v_136 = 0;
    bool v_137 = false;
    uvec2 v_138 = uvec2(0u);
    bool v_139 = false;
    uvec2 v_140 = uvec2(0u);
    bool v_141 = false;
    bool v_142 = false;
    int v_143 = 0;
    int v_144 = 0;
    bool v_145 = false;
    bool v_146 = false;
    bool v_147 = false;
    int v_148 = 0;
    bool v_149 = false;
    int v_150 = 0;
    bool v_151 = false;
    bool v_152 = false;
    bool v_153 = false;
    int v_154 = 0;
    bool v_155 = false;
    float v_156 = 0.0;
    float v_157 = 0.0;
    float v_158 = 0.0;
    float v_159 = 0.0;
    int v_160 = 0;
    int v_161 = 0;
    int v_162 = 0;
    int v_163 = 0;
    int v_164 = 0;
    int v_165 = 0;
    int v_166 = 0;
    int v_167 = 0;
    int v_168 = 0;
    bool v_169 = false;
    bool v_170 = false;
    int v_171 = 0;
    bool v_172 = false;
    bool v_173 = false;
    int v_174 = 0;
    int v_175 = 0;
    int v_176 = 0;
    int v_177 = 0;
    bool v_178 = false;
    bool v_179 = false;
    bool v_180 = false;
    int v_181 = 0;
    bool v_182 = false;
    bool v_183 = false;
    bool v_184 = false;
    float v_185 = 0.0;
    float v_186 = 0.0;
    int v_187 = 0;
    int v_188 = 0;
    float v_189 = 0.0;
    int v_190 = 0;
    int v_191 = 0;
    int v_192 = 0;
    // v_193 = buffer alias for param1
    v_3 = uvec2(0u);
    // v_194 = buffer alias for param2
    v_4 = uvec2(0u);
    // v_195 = buffer alias for param3
    v_5 = uvec2(0u);
    v_6 = int(0);
    v_7 = uvec2(2147483648u, 4294967295u);
    v_8 = i64_ge(v_5, v_7);
    v_9 = uvec2(2147483647u, 0u);
    v_10 = i64_le(v_5, v_9);
    v_11 = v_8 && v_10;
    // String: 32-bit index out of range
    v_12 = i64_to_i32(v_5);
    v_13 = v_12 > v_6;
    v_14 = int(0);
    v_15 = v_12 == v_14;
    v_16 = v_13 || v_15;
    // String: X index out of bounds
    v_17 = int(1);
    v_18 = uvec2(2147483648u, 4294967295u);
    v_19 = i64_ge(v_5, v_18);
    v_20 = uvec2(2147483647u, 0u);
    v_21 = i64_le(v_5, v_20);
    v_22 = v_19 && v_21;
    // String: 32-bit index out of range
    v_23 = i64_to_i32(v_5);
    v_24 = v_23 > v_17;
    // String: X index out of bounds
    int v_196 = int(v_17); // LEA into param3
    v_25 = int(texelFetch(u_param3, ivec2((int(v_196) + u_param3_offset) % u_param3_tileW, (int(v_196) + u_param3_offset) / u_param3_tileW), 0).r);
    v_26 = int(2);
    v_27 = uvec2(2147483648u, 4294967295u);
    v_28 = i64_ge(v_5, v_27);
    v_29 = uvec2(2147483647u, 0u);
    v_30 = i64_le(v_5, v_29);
    v_31 = v_28 && v_30;
    // String: 32-bit index out of range
    v_32 = i64_to_i32(v_5);
    v_33 = v_32 > v_26;
    // String: X index out of bounds
    int v_197 = int(v_26); // LEA into param3
    v_34 = int(texelFetch(u_param3, ivec2((int(v_197) + u_param3_offset) % u_param3_tileW, (int(v_197) + u_param3_offset) / u_param3_tileW), 0).r);
    v_35 = int(3);
    v_36 = uvec2(2147483648u, 4294967295u);
    v_37 = i64_ge(v_5, v_36);
    v_38 = uvec2(2147483647u, 0u);
    v_39 = i64_le(v_5, v_38);
    v_40 = v_37 && v_39;
    // String: 32-bit index out of range
    v_41 = i64_to_i32(v_5);
    v_42 = v_41 > v_35;
    // String: X index out of bounds
    int v_198 = int(v_35); // LEA into param3
    v_43 = int(texelFetch(u_param3, ivec2((int(v_198) + u_param3_offset) % u_param3_tileW, (int(v_198) + u_param3_offset) / u_param3_tileW), 0).r);
    v_44 = int(4);
    v_45 = uvec2(2147483648u, 4294967295u);
    v_46 = i64_ge(v_5, v_45);
    v_47 = uvec2(2147483647u, 0u);
    v_48 = i64_le(v_5, v_47);
    v_49 = v_46 && v_48;
    // String: 32-bit index out of range
    v_50 = i64_to_i32(v_5);
    v_51 = v_50 > v_44;
    // String: X index out of bounds
    int v_199 = int(v_44); // LEA into param3
    v_52 = int(texelFetch(u_param3, ivec2((int(v_199) + u_param3_offset) % u_param3_tileW, (int(v_199) + u_param3_offset) / u_param3_tileW), 0).r);
    v_53 = int(5);
    v_54 = uvec2(2147483648u, 4294967295u);
    v_55 = i64_ge(v_5, v_54);
    v_56 = uvec2(2147483647u, 0u);
    v_57 = i64_le(v_5, v_56);
    v_58 = v_55 && v_57;
    // String: 32-bit index out of range
    v_59 = i64_to_i32(v_5);
    v_60 = v_59 > v_53;
    // String: X index out of bounds
    int v_200 = int(v_53); // LEA into param3
    v_61 = int(texelFetch(u_param3, ivec2((int(v_200) + u_param3_offset) % u_param3_tileW, (int(v_200) + u_param3_offset) / u_param3_tileW), 0).r);
    v_62 = int(6);
    v_63 = uvec2(2147483648u, 4294967295u);
    v_64 = i64_ge(v_5, v_63);
    v_65 = uvec2(2147483647u, 0u);
    v_66 = i64_le(v_5, v_65);
    v_67 = v_64 && v_66;
    // String: 32-bit index out of range
    v_68 = i64_to_i32(v_5);
    v_69 = v_68 > v_62;
    // String: X index out of bounds
    int v_201 = int(v_62); // LEA into param3
    v_70 = int(texelFetch(u_param3, ivec2((int(v_201) + u_param3_offset) % u_param3_tileW, (int(v_201) + u_param3_offset) / u_param3_tileW), 0).r);
    v_71 = int(7);
    v_72 = uvec2(2147483648u, 4294967295u);
    v_73 = i64_ge(v_5, v_72);
    v_74 = uvec2(2147483647u, 0u);
    v_75 = i64_le(v_5, v_74);
    v_76 = v_73 && v_75;
    // String: 32-bit index out of range
    v_77 = i64_to_i32(v_5);
    v_78 = v_77 > v_71;
    // String: X index out of bounds
    int v_202 = int(v_71); // LEA into param3
    v_79 = int(texelFetch(u_param3, ivec2((int(v_202) + u_param3_offset) % u_param3_tileW, (int(v_202) + u_param3_offset) / u_param3_tileW), 0).r);
    v_80 = int(8);
    v_81 = uvec2(2147483648u, 4294967295u);
    v_82 = i64_ge(v_5, v_81);
    v_83 = uvec2(2147483647u, 0u);
    v_84 = i64_le(v_5, v_83);
    v_85 = v_82 && v_84;
    // String: 32-bit index out of range
    v_86 = i64_to_i32(v_5);
    v_87 = v_86 > v_80;
    // String: X index out of bounds
    int v_203 = int(v_80); // LEA into param3
    v_88 = int(texelFetch(u_param3, ivec2((int(v_203) + u_param3_offset) % u_param3_tileW, (int(v_203) + u_param3_offset) / u_param3_tileW), 0).r);
    v_89 = int(9);
    v_90 = uvec2(2147483648u, 4294967295u);
    v_91 = i64_ge(v_5, v_90);
    v_92 = uvec2(2147483647u, 0u);
    v_93 = i64_le(v_5, v_92);
    v_94 = v_91 && v_93;
    // String: 32-bit index out of range
    v_95 = i64_to_i32(v_5);
    v_96 = v_95 > v_89;
    // String: X index out of bounds
    int v_204 = int(v_89); // LEA into param3
    v_97 = int(texelFetch(u_param3, ivec2((int(v_204) + u_param3_offset) % u_param3_tileW, (int(v_204) + u_param3_offset) / u_param3_tileW), 0).r);
    v_98 = int(1);
    v_99 = v_88 << v_98;
    v_100 = v_34 + v_99;
    v_101 = v_100 - v_52;
    v_102 = v_101 / v_70;
    v_103 = int(1);
    v_104 = v_102 + v_103;
    v_105 = int(1);
    v_106 = v_97 << v_105;
    v_107 = v_43 + v_106;
    v_108 = v_107 - v_61;
    v_109 = v_108 / v_79;
    v_110 = int(1);
    v_111 = v_109 + v_110;
    v_112 = _idx % v_111;
    v_113 = _idx / v_111;
    v_114 = v_113 % v_104;
    v_115 = v_113 / v_104;
    v_116 = v_115 % v_25;
    v_117 = v_115 / v_25;
    v_118 = float(0.0);
    v_119 = int(0);
    v_120 = v_117 * v_25;
    v_121 = v_120 + v_116;
    v_122 = v_121 * v_34;
    v_123 = v_122 * v_43;
    v_124 = v_52 * v_61;
    v_125 = int(0);
    v_126 = uvec2(2147483648u, 4294967295u);
    v_127 = i64_ge(v_3, v_126);
    v_128 = uvec2(2147483647u, 0u);
    v_129 = i64_le(v_3, v_128);
    v_130 = v_127 && v_129;
    v_131 = i64_to_i32(v_3);
    v_132 = int(0);
    v_133 = v_131 == v_132;
    v_134 = v_118;
    v_135 = v_119;
    v_136 = v_125;
    for (int _loop0 = 0; _loop0 < 100000; _loop0++) {
        v_137 = v_136 < v_124;
        if (!v_137) {
            break;
        }
        v_160 = v_136 / v_61;
        v_161 = v_136 % v_61;
        v_162 = v_114 * v_70;
        v_163 = v_162 + v_160;
        v_164 = v_163 - v_88;
        v_165 = v_112 * v_79;
        v_166 = v_165 + v_161;
        v_167 = v_166 - v_97;
        v_168 = int(0);
        v_169 = v_164 < v_168;
        if (v_169) {
            v_189 = v_134;
            v_190 = v_135;
        } else {
            v_170 = v_164 >= v_34;
            if (v_170) {
                v_189 = v_134;
                v_190 = v_135;
            } else {
                v_171 = int(0);
                v_172 = v_167 < v_171;
                if (v_172) {
                    v_189 = v_134;
                    v_190 = v_135;
                } else {
                    v_173 = v_167 >= v_43;
                    if (v_173) {
                        v_189 = v_134;
                        v_190 = v_135;
                    } else {
                        v_174 = v_164 * v_43;
                        v_175 = v_123 + v_174;
                        v_176 = v_175 + v_167;
                        // String: 32-bit index out of range
                        v_177 = int(0);
                        v_178 = v_176 >= v_177;
                        v_179 = v_176 < v_131;
                        v_180 = v_178 && v_179;
                        v_181 = int(0);
                        v_182 = v_176 == v_181;
                        v_183 = v_182 && v_133;
                        v_184 = v_180 || v_183;
                        // String: X index out of bounds
                        int v_205 = int(v_176); // LEA into param1
                        v_185 = float(texelFetch(u_param1, ivec2((int(v_205) + u_param1_offset) % u_param1_tileW, (int(v_205) + u_param1_offset) / u_param1_tileW), 0).r);
                        v_186 = v_134 + v_185;
                        v_187 = int(1);
                        v_188 = v_135 + v_187;
                        v_189 = v_186;
                        v_190 = v_188;
                        v_191 = int(1);
                        v_192 = v_136 + v_191;
                        v_134 = v_189;
                        v_135 = v_190;
                        v_136 = v_192;
                        continue;
                    }
                    v_191 = int(1);
                    v_192 = v_136 + v_191;
                    v_134 = v_189;
                    v_135 = v_190;
                    v_136 = v_192;
                    continue;
                }
                v_191 = int(1);
                v_192 = v_136 + v_191;
                v_134 = v_189;
                v_135 = v_190;
                v_136 = v_192;
                continue;
            }
            v_191 = int(1);
            v_192 = v_136 + v_191;
            v_134 = v_189;
            v_135 = v_190;
            v_136 = v_192;
            continue;
        }
        v_191 = int(1);
        v_192 = v_136 + v_191;
        v_134 = v_189;
        v_135 = v_190;
        v_136 = v_192;
        continue;
    }
    v_138 = uvec2(2147483648u, 4294967295u);
    v_139 = i64_ge(v_4, v_138);
    v_140 = uvec2(2147483647u, 0u);
    v_141 = i64_le(v_4, v_140);
    v_142 = v_139 && v_141;
    // String: 32-bit index out of range
    v_143 = i64_to_i32(v_4);
    v_144 = int(0);
    v_145 = _idx >= v_144;
    v_146 = _idx < v_143;
    v_147 = v_145 && v_146;
    v_148 = int(0);
    v_149 = _idx == v_148;
    v_150 = int(0);
    v_151 = v_143 == v_150;
    v_152 = v_149 && v_151;
    v_153 = v_147 || v_152;
    // String: X index out of bounds
    int v_206 = int(_idx); // LEA into param2
    v_154 = int(0);
    v_155 = v_135 > v_154;
    v_156 = float(v_135);
    v_157 = v_134 / v_156;
    v_158 = float(0.0);
    v_159 = v_155 ? v_157 : v_158;
    tf_out_2 = v_159;
    return;
}
