// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T00:44:45.4430000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_367774 {
    int field_0;
    uvec2 field_1;
    int field_2;
};

struct struct_367760 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp isampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp int u_param2_length; // element count
uniform highp sampler2D u_param3; // buffer param[3]
uniform highp int u_param3_tileW;
uniform highp int u_param3_offset;
uniform highp int u_param3_length; // element count

out highp float tf_out_2; // TF output for param[2]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    
    uvec2 v_3 = uvec2(0u);
    uvec2 v_4 = uvec2(0u);
    uvec2 v_5 = uvec2(0u);
    int v_6 = 0;
    uvec2 v_7 = uvec2(0u);
    bool v_8 = false;
    uvec2 v_9 = uvec2(0u);
    bool v_10 = false;
    bool v_11 = false;
    int v_12 = 0;
    bool v_13 = false;
    int v_14 = 0;
    bool v_15 = false;
    bool v_16 = false;
    float v_17 = 0.0;
    int v_18 = 0;
    int v_19 = 0;
    uvec2 v_20 = uvec2(0u);
    bool v_21 = false;
    uvec2 v_22 = uvec2(0u);
    bool v_23 = false;
    bool v_24 = false;
    int v_25 = 0;
    bool v_26 = false;
    float v_27 = 0.0;
    int v_28 = 0;
    int v_29 = 0;
    uvec2 v_30 = uvec2(0u);
    bool v_31 = false;
    uvec2 v_32 = uvec2(0u);
    bool v_33 = false;
    bool v_34 = false;
    int v_35 = 0;
    bool v_36 = false;
    float v_37 = 0.0;
    int v_38 = 0;
    int v_39 = 0;
    uvec2 v_40 = uvec2(0u);
    bool v_41 = false;
    uvec2 v_42 = uvec2(0u);
    bool v_43 = false;
    bool v_44 = false;
    int v_45 = 0;
    bool v_46 = false;
    float v_47 = 0.0;
    int v_48 = 0;
    int v_49 = 0;
    int v_50 = 0;
    float v_51 = 0.0;
    float v_52 = 0.0;
    float v_53 = 0.0;
    float v_54 = 0.0;
    float v_55 = 0.0;
    float v_56 = 0.0;
    float v_57 = 0.0;
    float v_58 = 0.0;
    float v_59 = 0.0;
    float v_60 = 0.0;
    float v_61 = 0.0;
    float v_62 = 0.0;
    float v_63 = 0.0;
    float v_64 = 0.0;
    float v_65 = 0.0;
    float v_66 = 0.0;
    float v_67 = 0.0;
    float v_68 = 0.0;
    int v_69 = 0;
    int v_70 = 0;
    int v_71 = 0;
    int v_72 = 0;
    int v_73 = 0;
    int v_74 = 0;
    float v_75 = 0.0;
    float v_76 = 0.0;
    float v_77 = 0.0;
    float v_78 = 0.0;
    int v_79 = 0;
    bool v_80 = false;
    int v_81 = 0;
    int v_82 = 0;
    bool v_83 = false;
    int v_84 = 0;
    int v_85 = 0;
    int v_86 = 0;
    int v_87 = 0;
    bool v_88 = false;
    int v_89 = 0;
    int v_90 = 0;
    bool v_91 = false;
    int v_92 = 0;
    int v_93 = 0;
    int v_94 = 0;
    int v_95 = 0;
    int v_96 = 0;
    uvec2 v_97 = uvec2(0u);
    bool v_98 = false;
    uvec2 v_99 = uvec2(0u);
    bool v_100 = false;
    bool v_101 = false;
    int v_102 = 0;
    int v_103 = 0;
    bool v_104 = false;
    bool v_105 = false;
    bool v_106 = false;
    int v_107 = 0;
    bool v_108 = false;
    int v_109 = 0;
    bool v_110 = false;
    bool v_111 = false;
    bool v_112 = false;
    int v_113 = 0;
    int v_114 = 0;
    int v_115 = 0;
    float v_116 = 0.0;
    float v_117 = 0.0;
    float v_118 = 0.0;
    int v_119 = 0;
    int v_120 = 0;
    int v_121 = 0;
    int v_122 = 0;
    float v_123 = 0.0;
    float v_124 = 0.0;
    float v_125 = 0.0;
    int v_126 = 0;
    int v_127 = 0;
    int v_128 = 0;
    int v_129 = 0;
    float v_130 = 0.0;
    float v_131 = 0.0;
    float v_132 = 0.0;
    float v_133 = 0.0;
    float v_134 = 0.0;
    float v_135 = 0.0;
    float v_136 = 0.0;
    float v_137 = 0.0;
    float v_138 = 0.0;
    float v_139 = 0.0;
    float v_140 = 0.0;
    int v_141 = 0;
    int v_142 = 0;
    uvec2 v_143 = uvec2(0u);
    bool v_144 = false;
    uvec2 v_145 = uvec2(0u);
    bool v_146 = false;
    bool v_147 = false;
    int v_148 = 0;
    int v_149 = 0;
    bool v_150 = false;
    bool v_151 = false;
    bool v_152 = false;
    int v_153 = 0;
    bool v_154 = false;
    int v_155 = 0;
    bool v_156 = false;
    bool v_157 = false;
    bool v_158 = false;
    int v_159 = 0;
    int v_160 = 0;
    int v_161 = 0;
    float v_162 = 0.0;
    float v_163 = 0.0;
    float v_164 = 0.0;
    int v_165 = 0;
    int v_166 = 0;
    int v_167 = 0;
    int v_168 = 0;
    float v_169 = 0.0;
    float v_170 = 0.0;
    float v_171 = 0.0;
    int v_172 = 0;
    int v_173 = 0;
    int v_174 = 0;
    int v_175 = 0;
    float v_176 = 0.0;
    float v_177 = 0.0;
    float v_178 = 0.0;
    float v_179 = 0.0;
    float v_180 = 0.0;
    float v_181 = 0.0;
    float v_182 = 0.0;
    float v_183 = 0.0;
    float v_184 = 0.0;
    float v_185 = 0.0;
    float v_186 = 0.0;
    int v_187 = 0;
    int v_188 = 0;
    uvec2 v_189 = uvec2(0u);
    bool v_190 = false;
    uvec2 v_191 = uvec2(0u);
    bool v_192 = false;
    bool v_193 = false;
    int v_194 = 0;
    int v_195 = 0;
    bool v_196 = false;
    bool v_197 = false;
    bool v_198 = false;
    int v_199 = 0;
    bool v_200 = false;
    int v_201 = 0;
    bool v_202 = false;
    bool v_203 = false;
    bool v_204 = false;
    int v_205 = 0;
    int v_206 = 0;
    int v_207 = 0;
    float v_208 = 0.0;
    float v_209 = 0.0;
    float v_210 = 0.0;
    int v_211 = 0;
    int v_212 = 0;
    int v_213 = 0;
    int v_214 = 0;
    float v_215 = 0.0;
    float v_216 = 0.0;
    float v_217 = 0.0;
    int v_218 = 0;
    int v_219 = 0;
    int v_220 = 0;
    int v_221 = 0;
    float v_222 = 0.0;
    float v_223 = 0.0;
    float v_224 = 0.0;
    float v_225 = 0.0;
    float v_226 = 0.0;
    float v_227 = 0.0;
    float v_228 = 0.0;
    float v_229 = 0.0;
    float v_230 = 0.0;
    float v_231 = 0.0;
    float v_232 = 0.0;
    int v_233 = 0;
    int v_234 = 0;
    uvec2 v_235 = uvec2(0u);
    bool v_236 = false;
    uvec2 v_237 = uvec2(0u);
    bool v_238 = false;
    bool v_239 = false;
    int v_240 = 0;
    int v_241 = 0;
    bool v_242 = false;
    bool v_243 = false;
    bool v_244 = false;
    int v_245 = 0;
    bool v_246 = false;
    int v_247 = 0;
    bool v_248 = false;
    bool v_249 = false;
    bool v_250 = false;
    int v_251 = 0;
    int v_252 = 0;
    int v_253 = 0;
    float v_254 = 0.0;
    float v_255 = 0.0;
    float v_256 = 0.0;
    int v_257 = 0;
    int v_258 = 0;
    int v_259 = 0;
    int v_260 = 0;
    float v_261 = 0.0;
    float v_262 = 0.0;
    float v_263 = 0.0;
    int v_264 = 0;
    int v_265 = 0;
    int v_266 = 0;
    int v_267 = 0;
    float v_268 = 0.0;
    float v_269 = 0.0;
    float v_270 = 0.0;
    float v_271 = 0.0;
    float v_272 = 0.0;
    float v_273 = 0.0;
    float v_274 = 0.0;
    float v_275 = 0.0;
    float v_276 = 0.0;
    float v_277 = 0.0;
    float v_278 = 0.0;
    uvec2 v_279 = uvec2(0u);
    bool v_280 = false;
    uvec2 v_281 = uvec2(0u);
    bool v_282 = false;
    bool v_283 = false;
    int v_284 = 0;
    int v_285 = 0;
    bool v_286 = false;
    bool v_287 = false;
    bool v_288 = false;
    int v_289 = 0;
    bool v_290 = false;
    int v_291 = 0;
    bool v_292 = false;
    bool v_293 = false;
    bool v_294 = false;
    float v_295 = 0.0;
    float v_296 = 0.0;
    float v_297 = 0.0;
    float v_298 = 0.0;
    float v_299 = 0.0;
    float v_300 = 0.0;
    float v_301 = 0.0;
    float v_302 = 0.0;
    float v_303 = 0.0;
    float v_304 = 0.0;
    float v_305 = 0.0;
    float v_306 = 0.0;
    float v_307 = 0.0;
    float v_308 = 0.0;
    float v_309 = 0.0;
    float v_310 = 0.0;
    float v_311 = 0.0;
    float v_312 = 0.0;
    float v_313 = 0.0;
    // v_314 = buffer alias for param1
    v_3 = uvec2(0u);
    // v_315 = buffer alias for param2
    v_4 = uvec2(0u);
    // v_316 = buffer alias for param3
    v_5 = uvec2(0u);
    v_6 = int(0);
    v_7 = uvec2(2147483648u, 4294967295u);
    v_8 = i64_ge(v_5, v_7);
    v_9 = uvec2(2147483647u, 0u);
    v_10 = i64_le(v_5, v_9);
    v_11 = v_8 && v_10;
    // String: 32-bit index out of range
    v_12 = i64_to_i32(v_5);
    v_13 = v_12 > v_6;
    v_14 = int(0);
    v_15 = v_12 == v_14;
    v_16 = v_13 || v_15;
    // String: X index out of bounds
    int v_317 = int(v_6); // LEA into param3
    v_17 = float(texelFetch(u_param3, ivec2((int(v_317) + u_param3_offset) % u_param3_tileW, (int(v_317) + u_param3_offset) / u_param3_tileW), 0).r);
    v_18 = int(v_17);
    v_19 = int(1);
    v_20 = uvec2(2147483648u, 4294967295u);
    v_21 = i64_ge(v_5, v_20);
    v_22 = uvec2(2147483647u, 0u);
    v_23 = i64_le(v_5, v_22);
    v_24 = v_21 && v_23;
    // String: 32-bit index out of range
    v_25 = i64_to_i32(v_5);
    v_26 = v_25 > v_19;
    // String: X index out of bounds
    int v_318 = int(v_19); // LEA into param3
    v_27 = float(texelFetch(u_param3, ivec2((int(v_318) + u_param3_offset) % u_param3_tileW, (int(v_318) + u_param3_offset) / u_param3_tileW), 0).r);
    v_28 = int(v_27);
    v_29 = int(2);
    v_30 = uvec2(2147483648u, 4294967295u);
    v_31 = i64_ge(v_5, v_30);
    v_32 = uvec2(2147483647u, 0u);
    v_33 = i64_le(v_5, v_32);
    v_34 = v_31 && v_33;
    // String: 32-bit index out of range
    v_35 = i64_to_i32(v_5);
    v_36 = v_35 > v_29;
    // String: X index out of bounds
    int v_319 = int(v_29); // LEA into param3
    v_37 = float(texelFetch(u_param3, ivec2((int(v_319) + u_param3_offset) % u_param3_tileW, (int(v_319) + u_param3_offset) / u_param3_tileW), 0).r);
    v_38 = int(v_37);
    v_39 = int(3);
    v_40 = uvec2(2147483648u, 4294967295u);
    v_41 = i64_ge(v_5, v_40);
    v_42 = uvec2(2147483647u, 0u);
    v_43 = i64_le(v_5, v_42);
    v_44 = v_41 && v_43;
    // String: 32-bit index out of range
    v_45 = i64_to_i32(v_5);
    v_46 = v_45 > v_39;
    // String: X index out of bounds
    int v_320 = int(v_39); // LEA into param3
    v_47 = float(texelFetch(u_param3, ivec2((int(v_320) + u_param3_offset) % u_param3_tileW, (int(v_320) + u_param3_offset) / u_param3_tileW), 0).r);
    v_48 = int(v_47);
    v_49 = _idx / v_38;
    v_50 = _idx % v_38;
    v_51 = float(v_49);
    v_52 = float(0.5);
    v_53 = v_51 + v_52;
    v_54 = float(v_28);
    v_55 = v_53 * v_54;
    v_56 = float(v_48);
    v_57 = v_55 / v_56;
    v_58 = float(0.5);
    v_59 = v_57 - v_58;
    v_60 = float(v_50);
    v_61 = float(0.5);
    v_62 = v_60 + v_61;
    v_63 = float(v_18);
    v_64 = v_62 * v_63;
    v_65 = float(v_38);
    v_66 = v_64 / v_65;
    v_67 = float(0.5);
    v_68 = v_66 - v_67;
    v_69 = int(v_59);
    v_70 = int(1);
    v_71 = v_69 + v_70;
    v_72 = int(v_68);
    v_73 = int(1);
    v_74 = v_72 + v_73;
    v_75 = float(v_69);
    v_76 = v_59 - v_75;
    v_77 = float(v_72);
    v_78 = v_68 - v_77;
    v_79 = int(0);
    v_80 = v_69 >= v_79;
    v_82 = v_69;
    if (v_80) {
    } else {
        v_81 = int(0);
        v_82 = v_81;
    }
    v_83 = v_71 < v_28;
    v_84 = int(1);
    v_85 = v_28 - v_84;
    v_86 = v_83 ? v_71 : v_85;
    v_87 = int(0);
    v_88 = v_72 >= v_87;
    v_89 = int(0);
    v_90 = v_88 ? v_72 : v_89;
    v_91 = v_74 < v_18;
    v_92 = int(1);
    v_93 = v_18 - v_92;
    v_94 = v_91 ? v_74 : v_93;
    v_95 = v_82 * v_18;
    v_96 = v_95 + v_90;
    v_97 = uvec2(2147483648u, 4294967295u);
    v_98 = i64_ge(v_3, v_97);
    v_99 = uvec2(2147483647u, 0u);
    v_100 = i64_le(v_3, v_99);
    v_101 = v_98 && v_100;
    // String: 32-bit index out of range
    v_102 = i64_to_i32(v_3);
    v_103 = int(0);
    v_104 = v_96 >= v_103;
    v_105 = v_96 < v_102;
    v_106 = v_104 && v_105;
    v_107 = int(0);
    v_108 = v_96 == v_107;
    v_109 = int(0);
    v_110 = v_102 == v_109;
    v_111 = v_108 && v_110;
    v_112 = v_106 || v_111;
    // String: X index out of bounds
    int v_321 = int(v_96); // LEA into param1
    v_113 = int(texelFetch(u_param1, ivec2((int(v_321) + u_param1_offset) % u_param1_tileW, (int(v_321) + u_param1_offset) / u_param1_tileW), 0).r);
    v_114 = int(255);
    v_115 = v_113 & v_114;
    v_116 = float(v_115);
    v_117 = float(255.0);
    v_118 = v_116 / v_117;
    v_119 = int(8);
    v_120 = v_113 >> v_119;
    v_121 = int(255);
    v_122 = v_120 & v_121;
    v_123 = float(v_122);
    v_124 = float(255.0);
    v_125 = v_123 / v_124;
    v_126 = int(16);
    v_127 = v_113 >> v_126;
    v_128 = int(255);
    v_129 = v_127 & v_128;
    v_130 = float(v_129);
    v_131 = float(255.0);
    v_132 = v_130 / v_131;
    v_133 = float(0.298999995);
    v_134 = v_118 * v_133;
    v_135 = float(0.587000012);
    v_136 = v_125 * v_135;
    v_137 = v_134 + v_136;
    v_138 = float(0.114);
    v_139 = v_132 * v_138;
    v_140 = v_137 + v_139;
    v_141 = v_82 * v_18;
    v_142 = v_141 + v_94;
    v_143 = uvec2(2147483648u, 4294967295u);
    v_144 = i64_ge(v_3, v_143);
    v_145 = uvec2(2147483647u, 0u);
    v_146 = i64_le(v_3, v_145);
    v_147 = v_144 && v_146;
    // String: 32-bit index out of range
    v_148 = i64_to_i32(v_3);
    v_149 = int(0);
    v_150 = v_142 >= v_149;
    v_151 = v_142 < v_148;
    v_152 = v_150 && v_151;
    v_153 = int(0);
    v_154 = v_142 == v_153;
    v_155 = int(0);
    v_156 = v_148 == v_155;
    v_157 = v_154 && v_156;
    v_158 = v_152 || v_157;
    // String: X index out of bounds
    int v_322 = int(v_142); // LEA into param1
    v_159 = int(texelFetch(u_param1, ivec2((int(v_322) + u_param1_offset) % u_param1_tileW, (int(v_322) + u_param1_offset) / u_param1_tileW), 0).r);
    v_160 = int(255);
    v_161 = v_159 & v_160;
    v_162 = float(v_161);
    v_163 = float(255.0);
    v_164 = v_162 / v_163;
    v_165 = int(8);
    v_166 = v_159 >> v_165;
    v_167 = int(255);
    v_168 = v_166 & v_167;
    v_169 = float(v_168);
    v_170 = float(255.0);
    v_171 = v_169 / v_170;
    v_172 = int(16);
    v_173 = v_159 >> v_172;
    v_174 = int(255);
    v_175 = v_173 & v_174;
    v_176 = float(v_175);
    v_177 = float(255.0);
    v_178 = v_176 / v_177;
    v_179 = float(0.298999995);
    v_180 = v_164 * v_179;
    v_181 = float(0.587000012);
    v_182 = v_171 * v_181;
    v_183 = v_180 + v_182;
    v_184 = float(0.114);
    v_185 = v_178 * v_184;
    v_186 = v_183 + v_185;
    v_187 = v_86 * v_18;
    v_188 = v_187 + v_90;
    v_189 = uvec2(2147483648u, 4294967295u);
    v_190 = i64_ge(v_3, v_189);
    v_191 = uvec2(2147483647u, 0u);
    v_192 = i64_le(v_3, v_191);
    v_193 = v_190 && v_192;
    // String: 32-bit index out of range
    v_194 = i64_to_i32(v_3);
    v_195 = int(0);
    v_196 = v_188 >= v_195;
    v_197 = v_188 < v_194;
    v_198 = v_196 && v_197;
    v_199 = int(0);
    v_200 = v_188 == v_199;
    v_201 = int(0);
    v_202 = v_194 == v_201;
    v_203 = v_200 && v_202;
    v_204 = v_198 || v_203;
    // String: X index out of bounds
    int v_323 = int(v_188); // LEA into param1
    v_205 = int(texelFetch(u_param1, ivec2((int(v_323) + u_param1_offset) % u_param1_tileW, (int(v_323) + u_param1_offset) / u_param1_tileW), 0).r);
    v_206 = int(255);
    v_207 = v_205 & v_206;
    v_208 = float(v_207);
    v_209 = float(255.0);
    v_210 = v_208 / v_209;
    v_211 = int(8);
    v_212 = v_205 >> v_211;
    v_213 = int(255);
    v_214 = v_212 & v_213;
    v_215 = float(v_214);
    v_216 = float(255.0);
    v_217 = v_215 / v_216;
    v_218 = int(16);
    v_219 = v_205 >> v_218;
    v_220 = int(255);
    v_221 = v_219 & v_220;
    v_222 = float(v_221);
    v_223 = float(255.0);
    v_224 = v_222 / v_223;
    v_225 = float(0.298999995);
    v_226 = v_210 * v_225;
    v_227 = float(0.587000012);
    v_228 = v_217 * v_227;
    v_229 = v_226 + v_228;
    v_230 = float(0.114);
    v_231 = v_224 * v_230;
    v_232 = v_229 + v_231;
    v_233 = v_86 * v_18;
    v_234 = v_233 + v_94;
    v_235 = uvec2(2147483648u, 4294967295u);
    v_236 = i64_ge(v_3, v_235);
    v_237 = uvec2(2147483647u, 0u);
    v_238 = i64_le(v_3, v_237);
    v_239 = v_236 && v_238;
    // String: 32-bit index out of range
    v_240 = i64_to_i32(v_3);
    v_241 = int(0);
    v_242 = v_234 >= v_241;
    v_243 = v_234 < v_240;
    v_244 = v_242 && v_243;
    v_245 = int(0);
    v_246 = v_234 == v_245;
    v_247 = int(0);
    v_248 = v_240 == v_247;
    v_249 = v_246 && v_248;
    v_250 = v_244 || v_249;
    // String: X index out of bounds
    int v_324 = int(v_234); // LEA into param1
    v_251 = int(texelFetch(u_param1, ivec2((int(v_324) + u_param1_offset) % u_param1_tileW, (int(v_324) + u_param1_offset) / u_param1_tileW), 0).r);
    v_252 = int(255);
    v_253 = v_251 & v_252;
    v_254 = float(v_253);
    v_255 = float(255.0);
    v_256 = v_254 / v_255;
    v_257 = int(8);
    v_258 = v_251 >> v_257;
    v_259 = int(255);
    v_260 = v_258 & v_259;
    v_261 = float(v_260);
    v_262 = float(255.0);
    v_263 = v_261 / v_262;
    v_264 = int(16);
    v_265 = v_251 >> v_264;
    v_266 = int(255);
    v_267 = v_265 & v_266;
    v_268 = float(v_267);
    v_269 = float(255.0);
    v_270 = v_268 / v_269;
    v_271 = float(0.298999995);
    v_272 = v_256 * v_271;
    v_273 = float(0.587000012);
    v_274 = v_263 * v_273;
    v_275 = v_272 + v_274;
    v_276 = float(0.114);
    v_277 = v_270 * v_276;
    v_278 = v_275 + v_277;
    v_279 = uvec2(2147483648u, 4294967295u);
    v_280 = i64_ge(v_4, v_279);
    v_281 = uvec2(2147483647u, 0u);
    v_282 = i64_le(v_4, v_281);
    v_283 = v_280 && v_282;
    // String: 32-bit index out of range
    v_284 = i64_to_i32(v_4);
    v_285 = int(0);
    v_286 = _idx >= v_285;
    v_287 = _idx < v_284;
    v_288 = v_286 && v_287;
    v_289 = int(0);
    v_290 = _idx == v_289;
    v_291 = int(0);
    v_292 = v_284 == v_291;
    v_293 = v_290 && v_292;
    v_294 = v_288 || v_293;
    // String: X index out of bounds
    int v_325 = int(_idx); // LEA into param2
    v_295 = float(1.0);
    v_296 = v_295 - v_76;
    v_297 = v_140 * v_296;
    v_298 = float(1.0);
    v_299 = v_298 - v_78;
    v_300 = v_297 * v_299;
    v_301 = float(1.0);
    v_302 = v_301 - v_76;
    v_303 = v_186 * v_302;
    v_304 = v_303 * v_78;
    v_305 = v_300 + v_304;
    v_306 = v_232 * v_76;
    v_307 = float(1.0);
    v_308 = v_307 - v_78;
    v_309 = v_306 * v_308;
    v_310 = v_305 + v_309;
    v_311 = v_278 * v_76;
    v_312 = v_311 * v_78;
    v_313 = v_310 + v_312;
    tf_out_2 = v_313;
    return;
}
