// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T00:44:53.3780000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_f64 Emulation Functions (Double-Float: vec2 where x=high, y=low)
// ============================================================================
// ANTI-OPTIMIZATION: Uses the luma.gl/deck.gl 'ONE' technique to prevent
// GLSL compilers (especially ANGLE/D3D11) from optimizing away the error
// terms in double-float arithmetic. The uniform u_one is set to 1.0 at
// runtime but is unknown to the compiler at compile time, so the compiler
// cannot simplify expressions like (s * u_one - a) into (s - a).
// Without this, ANGLE collapses the two-sum error computation, reducing
// ~48-bit precision back to ~24-bit (regular float).
// ============================================================================

// Runtime constant: always 1.0, but opaque to the compiler
uniform highp float u_one;

// --- IEEE 754 double bits to double-float conversion ---
vec2 f64_from_ieee754_bits(uint lo, uint hi) {
    uint sign_bit = (hi >> 31u) & 1u;
    uint exponent = (hi >> 20u) & 0x7FFu;
    uint mantissa_hi20 = hi & 0xFFFFFu;
    uint mantissa_lo32 = lo;

    if (exponent == 0u && mantissa_hi20 == 0u && mantissa_lo32 == 0u) {
        return vec2(0.0, 0.0);
    }
    if (exponent == 0x7FFu) {
        return vec2(0.0, 0.0);
    }

    int exp_bias = 1023;
    int exp_val = int(exponent) - exp_bias;
    int f32_exp_bias = 127;
    int f32_exp = exp_val + f32_exp_bias;

    if (f32_exp <= 0 || f32_exp >= 255) {
        uint f32_bits_approx = (sign_bit << 31u) | (uint(clamp(f32_exp, 1, 254)) << 23u) | (mantissa_hi20 << 3u);
        float val_approx = intBitsToFloat(int(f32_bits_approx));
        return vec2(val_approx, 0.0);
    }

    uint top23 = (mantissa_hi20 << 3u) | (mantissa_lo32 >> 29u);
    uint f32_bits_h = (sign_bit << 31u) | (uint(f32_exp) << 23u) | top23;
    float val_hi = intBitsToFloat(int(f32_bits_h));

    uint remaining = mantissa_lo32 & 0x1FFFFFFFu;
    if (remaining == 0u) {
        return vec2(val_hi, 0.0);
    }

    int lo_exp = exp_val - 29 + f32_exp_bias;
    float val_lo;
    if (lo_exp > 0 && lo_exp < 255) {
        float rem_f = float(remaining);
        int scale_exp = exp_val - 23 + f32_exp_bias;
        if (scale_exp > 0 && scale_exp < 255) {
            uint scale_bits = uint(scale_exp) << 23u;
            float scale = intBitsToFloat(int(scale_bits));
            val_lo = (rem_f / 536870912.0) * scale;
        } else {
            val_lo = 0.0;
        }
    } else {
        val_lo = 0.0;
    }

    if (sign_bit != 0u) {
        val_lo = -val_lo;
    }

    // Inline two-sum normalization with u_one anti-optimization
    float _s = (val_hi + val_lo);
    float _v = (_s * u_one - val_hi) * u_one;
    float _e = (val_hi - (_s - _v) * u_one) * u_one * u_one * u_one + (val_lo - _v);
    return vec2(_s, _e);
}

// Store emu_f64 back to IEEE 754 bits
uvec2 f64_to_ieee754_bits(vec2 v) {
    float val_hi = v.x;
    float val_lo = v.y;

    if (val_hi == 0.0 && val_lo == 0.0) {
        return uvec2(0u, 0u);
    }

    uint f32_bits_h = uint(floatBitsToInt(val_hi));
    uint sign = (f32_bits_h >> 31u) & 1u;
    uint f32_exp = (f32_bits_h >> 23u) & 0xFFu;
    uint f32_mantissa = f32_bits_h & 0x7FFFFFu;

    int f32_bias = 127;
    int f64_bias = 1023;
    int exp_val = int(f32_exp) - f32_bias;
    uint f64_exp = uint(exp_val + f64_bias);

    uint mantissa_hi20 = f32_mantissa >> 3u;
    uint mantissa_lo32 = (f32_mantissa & 0x7u) << 29u;

    if (val_lo != 0.0) {
        int scale_exp = exp_val - 23 + f32_bias;
        if (scale_exp > 0 && scale_exp < 255) {
            uint scale_bits = uint(scale_exp) << 23u;
            float scale = intBitsToFloat(int(scale_bits));
            float abs_lo = abs(val_lo);
            float rem_f = (abs_lo / scale) * 536870912.0;
            uint remaining = uint(clamp(rem_f + 0.5, 0.0, 536870911.0));
            mantissa_lo32 = mantissa_lo32 | (remaining & 0x1FFFFFFFu);
        }
    }

    uint out_hi = (sign << 31u) | (f64_exp << 20u) | mantissa_hi20;
    uint out_lo = mantissa_lo32;
    return uvec2(out_lo, out_hi);
}

vec2 f64_from_f32(float v) { return vec2(v, 0.0); }
float f64_to_f32(vec2 v) { return v.x + v.y; }
vec2 f64_new(float hi, float lo) { return vec2(hi, lo); }
vec2 f64_neg(vec2 a) { return vec2(-a.x, -a.y); }

// ============================================================================
// Double-float arithmetic with ANGLE code-elimination workaround.
// u_one = 1.0 at runtime but opaque to compiler, preventing simplification.
// Based on the battle-tested luma.gl/deck.gl fp64 implementation.
// ============================================================================

// Dekker split: a = a_hi + a_lo, a_hi has <= 12 significant bits
vec2 f64_split(float a) {
    float c = 4097.0 * a;
    float a_hi = c * u_one - (c - a);
    float a_lo = a * u_one - a_hi;
    return vec2(a_hi, a_lo);
}

// Two-sum: s = a + b exactly as (sum, error) — Knuth's algorithm
vec2 f64_two_sum(float a, float b) {
    float s = (a + b);
    float v = (s * u_one - a) * u_one;
    float err = (a - (s - v) * u_one) * u_one * u_one * u_one + (b - v);
    return vec2(s, err);
}

// Quick two-sum: assumes |a| >= |b|
vec2 f64_quick_two_sum(float a, float b) {
    float s = (a + b) * u_one;
    float err = b - (s - a) * u_one;
    return vec2(s, err);
}

// Two-product: p = a * b exactly as (product, error)
vec2 f64_two_prod(float a, float b) {
    float p = a * b;
    vec2 a_s = f64_split(a);
    vec2 b_s = f64_split(b);
    float err = ((a_s.x * b_s.x - p) * u_one + a_s.x * b_s.y * u_one * u_one
        + a_s.y * b_s.x) + a_s.y * b_s.y * u_one * u_one * u_one;
    return vec2(p, err);
}

// emu_f64 addition (full error propagation from both hi and lo parts)
vec2 f64_add(vec2 a, vec2 b) {
    vec2 s = f64_two_sum(a.x, b.x);
    vec2 t = f64_two_sum(a.y, b.y);
    s.y += t.x;
    s = f64_quick_two_sum(s.x, s.y);
    s.y += t.y;
    s = f64_quick_two_sum(s.x, s.y);
    return s;
}

// emu_f64 subtraction
vec2 f64_sub(vec2 a, vec2 b) {
    return f64_add(a, f64_neg(b));
}

// emu_f64 multiplication
vec2 f64_mul(vec2 a, vec2 b) {
    vec2 p = f64_two_prod(a.x, b.x);
    p.y += a.x * b.y;
    p = f64_quick_two_sum(p.x, p.y);
    p.y += a.y * b.x;
    p = f64_quick_two_sum(p.x, p.y);
    return p;
}

// emu_f64 division
vec2 f64_div(vec2 a, vec2 b) {
    float xn = 1.0 / b.x;
    vec2 yn = a * xn;
    float diff = (f64_sub(a, f64_mul(b, yn))).x;
    vec2 prod = f64_two_prod(xn, diff);
    return f64_add(yn, prod);
}

// emu_f64 comparisons (no precision-sensitive operations)
bool f64_lt(vec2 a, vec2 b) {
    return (a.x < b.x) || (a.x == b.x && a.y < b.y);
}

bool f64_le(vec2 a, vec2 b) {
    return (a.x < b.x) || (a.x == b.x && a.y <= b.y);
}

bool f64_gt(vec2 a, vec2 b) {
    return (a.x > b.x) || (a.x == b.x && a.y > b.y);
}

bool f64_ge(vec2 a, vec2 b) {
    return (a.x > b.x) || (a.x == b.x && a.y >= b.y);
}

bool f64_eq(vec2 a, vec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool f64_ne(vec2 a, vec2 b) {
    return a.x != b.x || a.y != b.y;
}

// emu_f64 absolute value
vec2 f64_abs(vec2 a) {
    if (a.x < 0.0 || (a.x == 0.0 && a.y < 0.0)) {
        return f64_neg(a);
    }
    return a;
}

// emu_f64 min/max
vec2 f64_min(vec2 a, vec2 b) {
    if (f64_lt(a, b)) { return a; }
    return b;
}

vec2 f64_max(vec2 a, vec2 b) {
    if (f64_gt(a, b)) { return a; }
    return b;
}


// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_367760 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp sampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp int u_param2_length; // element count
uniform highp int u_param3_length; // element count
uniform highp int u_param4; // scalar param[4]

out highp float tf_out_2; // TF output for param[2]
out highp float tf_out_3; // TF output for param[3]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    int v_3;
    v_3 = u_param4;
    
    uvec2 v_4 = uvec2(0u);
    uvec2 v_5 = uvec2(0u);
    uvec2 v_6 = uvec2(0u);
    int v_7 = 0;
    uvec2 v_8 = uvec2(0u);
    bool v_9 = false;
    uvec2 v_10 = uvec2(0u);
    bool v_11 = false;
    bool v_12 = false;
    int v_13 = 0;
    int v_14 = 0;
    bool v_15 = false;
    bool v_16 = false;
    bool v_17 = false;
    int v_18 = 0;
    bool v_19 = false;
    int v_20 = 0;
    bool v_21 = false;
    bool v_22 = false;
    bool v_23 = false;
    float v_24 = 0.0;
    int v_25 = 0;
    uvec2 v_26 = uvec2(0u);
    bool v_27 = false;
    uvec2 v_28 = uvec2(0u);
    bool v_29 = false;
    bool v_30 = false;
    int v_31 = 0;
    int v_32 = 0;
    bool v_33 = false;
    int v_34 = 0;
    float v_35 = 0.0;
    bool v_36 = false;
    uvec2 v_37 = uvec2(0u);
    bool v_38 = false;
    uvec2 v_39 = uvec2(0u);
    bool v_40 = false;
    bool v_41 = false;
    int v_42 = 0;
    int v_43 = 0;
    bool v_44 = false;
    bool v_45 = false;
    bool v_46 = false;
    int v_47 = 0;
    bool v_48 = false;
    int v_49 = 0;
    bool v_50 = false;
    bool v_51 = false;
    bool v_52 = false;
    vec2 v_53 = vec2(0.0);
    int v_54 = 0;
    uvec2 v_55 = uvec2(0u);
    bool v_56 = false;
    uvec2 v_57 = uvec2(0u);
    bool v_58 = false;
    bool v_59 = false;
    int v_60 = 0;
    int v_61 = 0;
    bool v_62 = false;
    vec2 v_63 = vec2(0.0);
    int v_64 = 0;
    bool v_65 = false;
    uvec2 v_66 = uvec2(0u);
    bool v_67 = false;
    uvec2 v_68 = uvec2(0u);
    bool v_69 = false;
    bool v_70 = false;
    int v_71 = 0;
    int v_72 = 0;
    bool v_73 = false;
    bool v_74 = false;
    bool v_75 = false;
    int v_76 = 0;
    bool v_77 = false;
    int v_78 = 0;
    bool v_79 = false;
    bool v_80 = false;
    bool v_81 = false;
    float v_82 = 0.0;
    int v_83 = 0;
    int v_84 = 0;
    bool v_85 = false;
    bool v_86 = false;
    bool v_87 = false;
    int v_88 = 0;
    bool v_89 = false;
    bool v_90 = false;
    bool v_91 = false;
    float v_92 = 0.0;
    float v_93 = 0.0;
    float v_94 = 0.0;
    vec2 v_95 = vec2(0.0);
    vec2 v_96 = vec2(0.0);
    int v_97 = 0;
    int v_98 = 0;
    int v_99 = 0;
    int v_100 = 0;
    bool v_101 = false;
    bool v_102 = false;
    bool v_103 = false;
    int v_104 = 0;
    bool v_105 = false;
    bool v_106 = false;
    bool v_107 = false;
    float v_108 = 0.0;
    bool v_109 = false;
    float v_110 = 0.0;
    int v_111 = 0;
    int v_112 = 0;
    // v_113 = buffer alias for param1
    v_4 = uvec2(0u);
    // v_114 = buffer alias for param2
    v_5 = uvec2(0u);
    // v_115 = buffer alias for param3
    v_6 = uvec2(0u);
    v_7 = _idx * v_3;
    v_8 = uvec2(2147483648u, 4294967295u);
    v_9 = i64_ge(v_4, v_8);
    v_10 = uvec2(2147483647u, 0u);
    v_11 = i64_le(v_4, v_10);
    v_12 = v_9 && v_11;
    // String: 32-bit index out of range
    v_13 = i64_to_i32(v_4);
    v_14 = int(0);
    v_15 = v_7 >= v_14;
    v_16 = v_7 < v_13;
    v_17 = v_15 && v_16;
    v_18 = int(0);
    v_19 = v_7 == v_18;
    v_20 = int(0);
    v_21 = v_13 == v_20;
    v_22 = v_19 && v_21;
    v_23 = v_17 || v_22;
    // String: X index out of bounds
    int v_116 = int(v_7); // LEA into param1
    v_24 = float(texelFetch(u_param1, ivec2((int(v_116) + u_param1_offset) % u_param1_tileW, (int(v_116) + u_param1_offset) / u_param1_tileW), 0).r);
    v_25 = int(1);
    v_26 = uvec2(2147483648u, 4294967295u);
    v_27 = i64_ge(v_4, v_26);
    v_28 = uvec2(2147483647u, 0u);
    v_29 = i64_le(v_4, v_28);
    v_30 = v_27 && v_29;
    v_31 = i64_to_i32(v_4);
    v_32 = int(0);
    v_33 = v_31 == v_32;
    v_34 = v_25;
    v_35 = v_24;
    for (int _loop0 = 0; _loop0 < 100000; _loop0++) {
        v_36 = v_34 < v_3;
        if (!v_36) {
            break;
        }
        v_99 = v_7 + v_34;
        // String: 32-bit index out of range
        v_100 = int(0);
        v_101 = v_99 >= v_100;
        v_102 = v_99 < v_31;
        v_103 = v_101 && v_102;
        v_104 = int(0);
        v_105 = v_99 == v_104;
        v_106 = v_105 && v_33;
        v_107 = v_103 || v_106;
        // String: X index out of bounds
        int v_117 = int(v_99); // LEA into param1
        v_108 = float(texelFetch(u_param1, ivec2((int(v_117) + u_param1_offset) % u_param1_tileW, (int(v_117) + u_param1_offset) / u_param1_tileW), 0).r);
        v_109 = v_108 <= v_35;
        if (v_109) {
            v_110 = v_35;
        } else {
            v_110 = v_108;
            v_111 = int(1);
            v_112 = v_34 + v_111;
            v_34 = v_112;
            v_35 = v_110;
            continue;
        }
        v_111 = int(1);
        v_112 = v_34 + v_111;
        v_34 = v_112;
        v_35 = v_110;
        continue;
    }
    v_37 = uvec2(2147483648u, 4294967295u);
    v_38 = i64_ge(v_5, v_37);
    v_39 = uvec2(2147483647u, 0u);
    v_40 = i64_le(v_5, v_39);
    v_41 = v_38 && v_40;
    // String: 32-bit index out of range
    v_42 = i64_to_i32(v_5);
    v_43 = int(0);
    v_44 = _idx >= v_43;
    v_45 = _idx < v_42;
    v_46 = v_44 && v_45;
    v_47 = int(0);
    v_48 = _idx == v_47;
    v_49 = int(0);
    v_50 = v_42 == v_49;
    v_51 = v_48 && v_50;
    v_52 = v_46 || v_51;
    // String: X index out of bounds
    int v_118 = int(_idx); // LEA into param2
    tf_out_2 = v_35;
    v_53 = f64_from_ieee754_bits(0u, 0u);
    v_54 = int(0);
    v_55 = uvec2(2147483648u, 4294967295u);
    v_56 = i64_ge(v_4, v_55);
    v_57 = uvec2(2147483647u, 0u);
    v_58 = i64_le(v_4, v_57);
    v_59 = v_56 && v_58;
    v_60 = i64_to_i32(v_4);
    v_61 = int(0);
    v_62 = v_60 == v_61;
    v_63 = v_53;
    v_64 = v_54;
    for (int _loop1 = 0; _loop1 < 100000; _loop1++) {
        v_65 = v_64 < v_3;
        if (!v_65) {
            break;
        }
        v_83 = v_7 + v_64;
        // String: 32-bit index out of range
        v_84 = int(0);
        v_85 = v_83 >= v_84;
        v_86 = v_83 < v_60;
        v_87 = v_85 && v_86;
        v_88 = int(0);
        v_89 = v_83 == v_88;
        v_90 = v_89 && v_62;
        v_91 = v_87 || v_90;
        // String: X index out of bounds
        int v_119 = int(v_83); // LEA into param1
        v_92 = float(texelFetch(u_param1, ivec2((int(v_119) + u_param1_offset) % u_param1_tileW, (int(v_119) + u_param1_offset) / u_param1_tileW), 0).r);
        v_93 = v_92 - v_35;
        v_94 = float(exp(v_93));
        v_95 = f64_from_f32(v_94);
        v_96 = f64_add(v_63, v_95);
        v_97 = int(1);
        v_98 = v_64 + v_97;
        v_63 = v_96;
        v_64 = v_98;
        continue;
    }
    v_66 = uvec2(2147483648u, 4294967295u);
    v_67 = i64_ge(v_6, v_66);
    v_68 = uvec2(2147483647u, 0u);
    v_69 = i64_le(v_6, v_68);
    v_70 = v_67 && v_69;
    // String: 32-bit index out of range
    v_71 = i64_to_i32(v_6);
    v_72 = int(0);
    v_73 = _idx >= v_72;
    v_74 = _idx < v_71;
    v_75 = v_73 && v_74;
    v_76 = int(0);
    v_77 = _idx == v_76;
    v_78 = int(0);
    v_79 = v_71 == v_78;
    v_80 = v_77 && v_79;
    v_81 = v_75 || v_80;
    // String: X index out of bounds
    int v_120 = int(_idx); // LEA into param3
    v_82 = f64_to_f32(v_63);
    tf_out_3 = v_82;
    return;
}
