// GLSL Kernel: glsl_kernel
// Time: 2026-03-24T00:44:56.4940000Z

#version 300 es
//
// Generated by SpawnDev.ILGPU.WebGL v2.0.0
//
precision highp float;
precision highp int;

// ============ 64-bit Emulation Library ============

// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: uvec2 where x=low, y=high)
// ============================================================================

// Create emu_i64 from int (sign-extend)
uvec2 i64_from_i32(int v) {
    uint lo = uint(v);
    uint hi = v < 0 ? 0xFFFFFFFFu : 0u;
    return uvec2(lo, hi);
}

// Create emu_u64 from uint
uvec2 u64_from_u32(uint v) {
    return uvec2(v, 0u);
}

// Convert emu_i64 to int (truncate)
int i64_to_i32(uvec2 v) {
    return int(v.x);
}

// Convert emu_u64 to uint (truncate)
uint u64_to_u32(uvec2 v) {
    return v.x;
}

// Create emu_i64 from low and high
uvec2 i64_new(uint lo, uint hi) {
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 addition with carry
uvec2 i64_add(uvec2 a, uvec2 b) {
    uint lo = a.x + b.x;
    uint carry = lo < a.x ? 1u : 0u;
    uint hi = a.y + b.y + carry;
    return uvec2(lo, hi);
}

// emu_i64/emu_u64 subtraction with borrow
uvec2 i64_sub(uvec2 a, uvec2 b) {
    uint borrow = a.x < b.x ? 1u : 0u;
    uint lo = a.x - b.x;
    uint hi = a.y - b.y - borrow;
    return uvec2(lo, hi);
}

// emu_i64 negation (two's complement)
uvec2 i64_neg(uvec2 a) {
    uvec2 inv = uvec2(~a.x, ~a.y);
    return i64_add(inv, uvec2(1u, 0u));
}

// emu_u64 multiplication
uvec2 u64_mul(uvec2 a, uvec2 b) {
    uint a_lo = a.x & 0xFFFFu;
    uint a_hi = a.x >> 16u;
    uint b_lo = b.x & 0xFFFFu;
    uint b_hi = b.x >> 16u;

    uint p0 = a_lo * b_lo;
    uint p1 = a_lo * b_hi;
    uint p2 = a_hi * b_lo;
    uint p3 = a_hi * b_hi;

    uint mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    uint lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);

    uint hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;

    return uvec2(lo, hi);
}

// emu_i64 multiplication
uvec2 i64_mul(uvec2 a, uvec2 b) {
    bool neg_a = (a.y & 0x80000000u) != 0u;
    bool neg_b = (b.y & 0x80000000u) != 0u;
    uvec2 abs_a = neg_a ? i64_neg(a) : a;
    uvec2 abs_b = neg_b ? i64_neg(b) : b;
    uvec2 result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise operations
uvec2 i64_and(uvec2 a, uvec2 b) {
    return uvec2(a.x & b.x, a.y & b.y);
}

uvec2 i64_or(uvec2 a, uvec2 b) {
    return uvec2(a.x | b.x, a.y | b.y);
}

uvec2 i64_xor(uvec2 a, uvec2 b) {
    return uvec2(a.x ^ b.x, a.y ^ b.y);
}

uvec2 i64_not(uvec2 a) {
    return uvec2(~a.x, ~a.y);
}

// Left shift
uvec2 i64_shl(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(0u, a.x << (shift - 32u));
    }
    uint lo = a.x << shift;
    uint hi = (a.y << shift) | (a.x >> (32u - shift));
    return uvec2(lo, hi);
}

// Logical right shift
uvec2 u64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return uvec2(0u, 0u); }
    if (shift >= 32u) {
        return uvec2(a.y >> (shift - 32u), 0u);
    }
    uint lo = (a.x >> shift) | (a.y << (32u - shift));
    uint hi = a.y >> shift;
    return uvec2(lo, hi);
}

// Arithmetic right shift
uvec2 i64_shr(uvec2 a, uint shift) {
    if (shift == 0u) { return a; }
    uint sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        uint fill = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(fill, fill);
    }
    if (shift >= 32u) {
        int signed_y = int(a.y);
        uint shift_amt = shift - 32u;
        int shifted = signed_y >> int(shift_amt);
        uint lo = uint(shifted);
        uint hi = sign != 0u ? 0xFFFFFFFFu : 0u;
        return uvec2(lo, hi);
    }
    uint lo_r = (a.x >> shift) | (a.y << (32u - shift));
    int signed_y_r = int(a.y);
    int shifted_r = signed_y_r >> int(shift);
    uint hi_r = uint(shifted_r);
    return uvec2(lo_r, hi_r);
}

// Signed comparisons
bool i64_eq(uvec2 a, uvec2 b) {
    return a.x == b.x && a.y == b.y;
}

bool i64_ne(uvec2 a, uvec2 b) {
    return a.x != b.x || a.y != b.y;
}

bool i64_lt(uvec2 a, uvec2 b) {
    bool a_neg = (a.y & 0x80000000u) != 0u;
    bool b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool i64_le(uvec2 a, uvec2 b) {
    return i64_lt(a, b) || i64_eq(a, b);
}

bool i64_gt(uvec2 a, uvec2 b) {
    return i64_lt(b, a);
}

bool i64_ge(uvec2 a, uvec2 b) {
    return !i64_lt(a, b);
}

// Unsigned comparisons
bool u64_lt(uvec2 a, uvec2 b) {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

bool u64_le(uvec2 a, uvec2 b) {
    return u64_lt(a, b) || i64_eq(a, b);
}

bool u64_gt(uvec2 a, uvec2 b) {
    return u64_lt(b, a);
}

bool u64_ge(uvec2 a, uvec2 b) {
    return !u64_lt(a, b);
}

// emu_i64 absolute value
uvec2 i64_abs(uvec2 a) {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}


struct struct_367760 {
    float field_0;
    uvec2 field_1;
    int field_2;
};

uniform highp int u_groupDimX; // threads per workgroup (X)
uniform highp int u_gridDimX; // number of workgroups (X)
uniform highp int u_gridDimY; // number of workgroups (Y)
uniform highp sampler2D u_param1; // buffer param[1]
uniform highp int u_param1_tileW;
uniform highp int u_param1_offset;
uniform highp int u_param1_length; // element count
uniform highp sampler2D u_param2; // buffer param[2]
uniform highp int u_param2_tileW;
uniform highp int u_param2_offset;
uniform highp int u_param2_length; // element count
uniform highp sampler2D u_param3; // buffer param[3]
uniform highp int u_param3_tileW;
uniform highp int u_param3_offset;
uniform highp int u_param3_length; // element count
uniform highp int u_param4_length; // element count

out highp float tf_out_4; // TF output for param[4]

void main() {
    int _idx = gl_VertexID;
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
    
    // param1 is buffer (accessed via u_param1)
    // param2 is buffer (accessed via u_param2)
    // param3 is buffer (accessed via u_param3)
    // param4 is buffer (accessed via u_param4)
    
    uvec2 v_4 = uvec2(0u);
    uvec2 v_5 = uvec2(0u);
    uvec2 v_6 = uvec2(0u);
    uvec2 v_7 = uvec2(0u);
    uvec2 v_8 = uvec2(0u);
    bool v_9 = false;
    uvec2 v_10 = uvec2(0u);
    bool v_11 = false;
    bool v_12 = false;
    int v_13 = 0;
    int v_14 = 0;
    bool v_15 = false;
    bool v_16 = false;
    bool v_17 = false;
    int v_18 = 0;
    bool v_19 = false;
    int v_20 = 0;
    bool v_21 = false;
    bool v_22 = false;
    bool v_23 = false;
    uvec2 v_24 = uvec2(0u);
    bool v_25 = false;
    uvec2 v_26 = uvec2(0u);
    bool v_27 = false;
    bool v_28 = false;
    int v_29 = 0;
    int v_30 = 0;
    bool v_31 = false;
    bool v_32 = false;
    bool v_33 = false;
    int v_34 = 0;
    bool v_35 = false;
    int v_36 = 0;
    bool v_37 = false;
    bool v_38 = false;
    bool v_39 = false;
    float v_40 = 0.0;
    float v_41 = 0.0;
    bool v_42 = false;
    uvec2 v_43 = uvec2(0u);
    bool v_44 = false;
    uvec2 v_45 = uvec2(0u);
    bool v_46 = false;
    bool v_47 = false;
    int v_48 = 0;
    int v_49 = 0;
    bool v_50 = false;
    bool v_51 = false;
    bool v_52 = false;
    int v_53 = 0;
    bool v_54 = false;
    int v_55 = 0;
    bool v_56 = false;
    bool v_57 = false;
    bool v_58 = false;
    float v_59 = 0.0;
    uvec2 v_60 = uvec2(0u);
    bool v_61 = false;
    uvec2 v_62 = uvec2(0u);
    bool v_63 = false;
    bool v_64 = false;
    int v_65 = 0;
    int v_66 = 0;
    bool v_67 = false;
    bool v_68 = false;
    bool v_69 = false;
    int v_70 = 0;
    bool v_71 = false;
    int v_72 = 0;
    bool v_73 = false;
    bool v_74 = false;
    bool v_75 = false;
    float v_76 = 0.0;
    float v_77 = 0.0;
    // v_78 = buffer alias for param1
    v_4 = uvec2(0u);
    // v_79 = buffer alias for param2
    v_5 = uvec2(0u);
    // v_80 = buffer alias for param3
    v_6 = uvec2(0u);
    // v_81 = buffer alias for param4
    v_7 = uvec2(0u);
    v_8 = uvec2(2147483648u, 4294967295u);
    v_9 = i64_ge(v_7, v_8);
    v_10 = uvec2(2147483647u, 0u);
    v_11 = i64_le(v_7, v_10);
    v_12 = v_9 && v_11;
    // String: 32-bit index out of range
    v_13 = i64_to_i32(v_7);
    v_14 = int(0);
    v_15 = _idx >= v_14;
    v_16 = _idx < v_13;
    v_17 = v_15 && v_16;
    v_18 = int(0);
    v_19 = _idx == v_18;
    v_20 = int(0);
    v_21 = v_13 == v_20;
    v_22 = v_19 && v_21;
    v_23 = v_17 || v_22;
    // String: X index out of bounds
    int v_82 = int(_idx); // LEA into param4
    v_24 = uvec2(2147483648u, 4294967295u);
    v_25 = i64_ge(v_4, v_24);
    v_26 = uvec2(2147483647u, 0u);
    v_27 = i64_le(v_4, v_26);
    v_28 = v_25 && v_27;
    // String: 32-bit index out of range
    v_29 = i64_to_i32(v_4);
    v_30 = int(0);
    v_31 = _idx >= v_30;
    v_32 = _idx < v_29;
    v_33 = v_31 && v_32;
    v_34 = int(0);
    v_35 = _idx == v_34;
    v_36 = int(0);
    v_37 = v_29 == v_36;
    v_38 = v_35 && v_37;
    v_39 = v_33 || v_38;
    // String: X index out of bounds
    int v_83 = int(_idx); // LEA into param1
    v_40 = float(texelFetch(u_param1, ivec2((int(v_83) + u_param1_offset) % u_param1_tileW, (int(v_83) + u_param1_offset) / u_param1_tileW), 0).r);
    v_41 = float(0.0);
    v_42 = v_40 != v_41;
    if (v_42) {
        v_60 = uvec2(2147483648u, 4294967295u);
        v_61 = i64_ge(v_5, v_60);
        v_62 = uvec2(2147483647u, 0u);
        v_63 = i64_le(v_5, v_62);
        v_64 = v_61 && v_63;
        // String: 32-bit index out of range
        v_65 = i64_to_i32(v_5);
        v_66 = int(0);
        v_67 = _idx >= v_66;
        v_68 = _idx < v_65;
        v_69 = v_67 && v_68;
        v_70 = int(0);
        v_71 = _idx == v_70;
        v_72 = int(0);
        v_73 = v_65 == v_72;
        v_74 = v_71 && v_73;
        v_75 = v_69 || v_74;
        // String: X index out of bounds
        int v_84 = int(_idx); // LEA into param2
        v_76 = float(texelFetch(u_param2, ivec2((int(v_84) + u_param2_offset) % u_param2_tileW, (int(v_84) + u_param2_offset) / u_param2_tileW), 0).r);
        v_77 = v_76;
    } else {
        v_43 = uvec2(2147483648u, 4294967295u);
        v_44 = i64_ge(v_6, v_43);
        v_45 = uvec2(2147483647u, 0u);
        v_46 = i64_le(v_6, v_45);
        v_47 = v_44 && v_46;
        // String: 32-bit index out of range
        v_48 = i64_to_i32(v_6);
        v_49 = int(0);
        v_50 = _idx >= v_49;
        v_51 = _idx < v_48;
        v_52 = v_50 && v_51;
        v_53 = int(0);
        v_54 = _idx == v_53;
        v_55 = int(0);
        v_56 = v_48 == v_55;
        v_57 = v_54 && v_56;
        v_58 = v_52 || v_57;
        // String: X index out of bounds
        int v_85 = int(_idx); // LEA into param3
        v_59 = float(texelFetch(u_param3, ivec2((int(v_85) + u_param3_offset) % u_param3_tileW, (int(v_85) + u_param3_offset) / u_param3_tileW), 0).r);
        v_77 = v_59;
    }
    tf_out_4 = v_77;
    return;
}
