// Kernel: YChannelImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T04:03:10.2260000Z

// Kernel: YChannelImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: YChannelImpl_29
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_50 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};

struct struct_55 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
// View offset for param3000 at scalar slot 1
// View offset for param4000 at scalar slot 2
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : i32 = 0;
    var v_5 : bool = false;
    var v_6 : i32 = 0;
    var v_7 : bool = false;
    var v_8 : bool = false;
    var v_9 : i32 = 0;
    var v_10 : i32 = 0;
    var v_11 : f32 = 0.0;
    var v_12 : f32 = 0.0;
    var v_13 : f32 = 0.0;
    var v_14 : f32 = 0.0;
    var v_15 : f32 = 0.0;
    var v_16 : f32 = 0.0;
    var v_17 : f32 = 0.0;
    var v_18 : f32 = 0.0;
    var v_19 : i32 = 0;
    var v_20 : i32 = 0;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : f32 = 0.0;
    var v_24 : f32 = 0.0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : i32 = 0;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : bool = false;
    var v_32 : bool = false;
    var v_33 : bool = false;
    var v_34 : bool = false;
    var v_35 : i32 = 0;
    var v_36 : f32 = 0.0;
    var v_37 : i32 = 0;
    var v_38 : i32 = 0;
    var v_39 : f32 = 0.0;
    var v_40 : i32 = 0;
    var v_41 : i32 = 0;
    var v_42 : f32 = 0.0;
    var v_43 : f32 = 0.0;
    var v_44 : f32 = 0.0;
    var v_45 : f32 = 0.0;
    var v_46 : f32 = 0.0;
    var v_47 : f32 = 0.0;
    var v_48 : i32 = 0;
    var v_49 : i32 = 0;
    var v_50 : bool = false;
    var v_51 : bool = false;
    var v_52 : bool = false;
    var v_53 : bool = false;
    var v_54 : i32 = 0;
    var v_55 : f32 = 0.0;
    var v_56 : i32 = 0;
    var v_57 : i32 = 0;
    var v_58 : f32 = 0.0;
    var v_59 : i32 = 0;
    var v_60 : i32 = 0;
    var v_61 : f32 = 0.0;
    var v_62 : f32 = 0.0;
    var v_63 : f32 = 0.0;
    var v_64 : f32 = 0.0;
    var v_65 : f32 = 0.0;
    var v_66 : f32 = 0.0;
    var v_67 : i32 = 0;
    var v_68 : i32 = 0;
    var v_69 : bool = false;
    var v_70 : bool = false;
    var v_71 : bool = false;
    var v_72 : bool = false;
    var v_73 : i32 = 0;
    var v_74 : f32 = 0.0;
    var v_75 : i32 = 0;
    var v_76 : i32 = 0;
    var v_77 : f32 = 0.0;
    var v_78 : i32 = 0;
    var v_79 : i32 = 0;
    var v_80 : f32 = 0.0;
    var v_81 : f32 = 0.0;
    var v_82 : f32 = 0.0;
    var v_83 : f32 = 0.0;
    var v_84 : f32 = 0.0;
    var v_85 : f32 = 0.0;
    var v_86 : i32 = 0;
    var v_87 : i32 = 0;
    var v_88 : bool = false;
    var v_89 : bool = false;
    var v_90 : bool = false;
    var v_91 : bool = false;
    var v_92 : i32 = 0;
    var v_93 : f32 = 0.0;
    var v_94 : i32 = 0;
    var v_95 : i32 = 0;
    var v_96 : f32 = 0.0;
    var v_97 : i32 = 0;
    var v_98 : i32 = 0;
    var v_99 : f32 = 0.0;
    var v_100 : f32 = 0.0;
    var v_101 : f32 = 0.0;
    var v_102 : f32 = 0.0;
    var v_103 : f32 = 0.0;
    var v_104 : f32 = 0.0;
    var v_105 : bool = false;
    var v_106 : bool = false;
    var v_107 : bool = false;
    var v_108 : bool = false;
    var v_109 : f32 = 0.0;
    var v_110 : f32 = 0.0;
    var v_111 : f32 = 0.0;
    var v_112 : f32 = 0.0;
    var v_113 : f32 = 0.0;
    var v_114 : f32 = 0.0;
    var v_115 : f32 = 0.0;
    var v_116 : f32 = 0.0;
    var v_117 : f32 = 0.0;
    var v_118 : f32 = 0.0;
    var v_119 : f32 = 0.0;
    var v_120 : f32 = 0.0;
    var v_121 : f32 = 0.0;
    var v_122 : f32 = 0.0;
    var v_123 : f32 = 0.0;
    var v_124 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_124) >= _ilgpu_user_dim) { return; }
    let v_125_f0 = &param1_f0;
    var v_125_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_126_f0 = &param2_f0;
    var v_126_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_127_f0 = &param3_f0;
    var v_127_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    var v_132 : i32;
    var v_133 : emu_i64;
    var v_135 : emu_i64;
    var v_138 : i32;
    var v_139 : bool;
    var v_141 : i32;
    var v_142 : bool;
    var v_143 : i32;
    var v_146 : f32;
    var v_147 : i32;
    var v_148 : emu_i64;
    var v_150 : emu_i64;
    var v_153 : i32;
    var v_154 : bool;
    var v_156 : i32;
    var v_157 : bool;
    var v_158 : i32;
    var v_161 : f32;
    var v_162 : i32;
    var v_163 : emu_i64;
    var v_165 : emu_i64;
    var v_168 : i32;
    var v_169 : bool;
    var v_171 : i32;
    var v_172 : bool;
    var v_173 : i32;
    var v_176 : f32;
    var v_178 : i32;
    var v_179 : emu_i64;
    var v_181 : emu_i64;
    var v_184 : i32;
    var v_185 : bool;
    var v_187 : i32;
    var v_188 : bool;
    var v_189 : i32;
    var v_192 : f32;
    var v_195 : f32;
    var v_198 : f32;
    var v_200 : f32;
    var v_203 : f32;
    var v_204 : i32;
    var v_205 : i32;
    var v_208 : i32;
    var v_211 : i32;
    var v_212 : i32;
    var v_213 : i32;
    var v_215 : i32;
    var v_216 : i32;
    var v_218 : i32;
    var v_219 : i32;
    var v_220 : emu_i64;
    var v_222 : emu_i64;
    var v_225 : i32;
    var v_228 : i32;
    var v_230 : i32;
    var v_233 : i32;
    var v_234 : i32;
    var v_236 : f32;
    var v_237 : i32;
    var v_238 : i32;
    var v_240 : f32;
    var v_241 : i32;
    var v_242 : i32;
    var v_244 : f32;
    var v_245 : f32;
    var v_246 : f32;
    var v_247 : f32;
    var v_248 : emu_i64;
    var v_250 : emu_i64;
    var v_253 : i32;
    var v_256 : i32;
    var v_258 : i32;
    var v_261 : i32;
    var v_262 : i32;
    var v_264 : f32;
    var v_265 : i32;
    var v_266 : i32;
    var v_268 : f32;
    var v_269 : i32;
    var v_270 : i32;
    var v_272 : f32;
    var v_273 : f32;
    var v_274 : f32;
    var v_275 : f32;
    var v_276 : emu_i64;
    var v_278 : emu_i64;
    var v_281 : i32;
    var v_284 : i32;
    var v_286 : i32;
    var v_289 : i32;
    var v_290 : i32;
    var v_292 : f32;
    var v_293 : i32;
    var v_294 : i32;
    var v_296 : f32;
    var v_297 : i32;
    var v_298 : i32;
    var v_300 : f32;
    var v_301 : f32;
    var v_302 : f32;
    var v_303 : f32;
    var v_304 : emu_i64;
    var v_306 : emu_i64;
    var v_309 : i32;
    var v_312 : i32;
    var v_314 : i32;
    var v_317 : i32;
    var v_318 : i32;
    var v_320 : f32;
    var v_321 : i32;
    var v_322 : i32;
    var v_324 : f32;
    var v_325 : i32;
    var v_326 : i32;
    var v_328 : f32;
    var v_329 : f32;
    var v_330 : f32;
    var v_331 : f32;
    var v_332 : emu_i64;
    var v_334 : emu_i64;
    var v_337 : i32;
    var v_340 : i32;
    var v_342 : i32;
    var v_345 : f32;
    var v_346 : f32;
    var v_347 : f32;
    var v_348 : f32;
    var v_131 : emu_i64;
    var v_134 : bool;
    var v_136 : bool;
    var v_137 : i32;
    var v_140 : bool;
    var v_144 : bool;
    var v_149 : bool;
    var v_151 : bool;
    var v_152 : i32;
    var v_155 : bool;
    var v_159 : bool;
    var v_164 : bool;
    var v_166 : bool;
    var v_167 : i32;
    var v_170 : bool;
    var v_174 : bool;
    var v_177 : i32;
    var v_180 : bool;
    var v_182 : bool;
    var v_183 : i32;
    var v_186 : bool;
    var v_190 : bool;
    var v_193 : i32;
    var v_194 : f32;
    var v_196 : f32;
    var v_197 : f32;
    var v_199 : f32;
    var v_201 : f32;
    var v_202 : f32;
    var v_206 : f32;
    var v_207 : f32;
    var v_209 : bool;
    var v_210 : bool;
    var v_214 : bool;
    var v_217 : bool;
    var v_221 : bool;
    var v_223 : bool;
    var v_224 : i32;
    var v_226 : bool;
    var v_227 : bool;
    var v_229 : bool;
    var v_231 : bool;
    var v_235 : f32;
    var v_239 : f32;
    var v_243 : f32;
    var v_249 : bool;
    var v_251 : bool;
    var v_252 : i32;
    var v_254 : bool;
    var v_255 : bool;
    var v_257 : bool;
    var v_259 : bool;
    var v_263 : f32;
    var v_267 : f32;
    var v_271 : f32;
    var v_277 : bool;
    var v_279 : bool;
    var v_280 : i32;
    var v_282 : bool;
    var v_283 : bool;
    var v_285 : bool;
    var v_287 : bool;
    var v_291 : f32;
    var v_295 : f32;
    var v_299 : f32;
    var v_305 : bool;
    var v_307 : bool;
    var v_308 : i32;
    var v_310 : bool;
    var v_311 : bool;
    var v_313 : bool;
    var v_315 : bool;
    var v_319 : f32;
    var v_323 : f32;
    var v_327 : f32;
    var v_333 : bool;
    var v_335 : bool;
    var v_336 : i32;
    var v_338 : bool;
    var v_339 : bool;
    var v_341 : bool;
    var v_343 : bool;


















































































    let v_128 = v_125_f0;
    let v_129 = v_126_f0;
    let v_130 = v_127_f0;

    v_0 = v_125_f1;

    v_1 = v_126_f1;

    v_131 = v_127_f1;
    v_132 = i32(0);
    v_133 = _c_i64_0;
    v_134 = i64_ge(v_131, v_133);
    v_135 = _c_i64_1;
    v_136 = i64_le(v_131, v_135);
    v_2 = v_134 & v_136;
    v_137 = i64_to_i32(v_131);
    v_138 = i32(0);
    v_139 = true;
    v_140 = v_137 > v_132;
    v_141 = i32(0);
    v_142 = true;
    v_143 = i32(0);
    v_144 = v_137 == v_143;
    v_3 = v_140 | v_144;
    let v_145 = &param3_f0[(i32(_scalar_params[2]) + v_132)];
    v_146 = *v_145;
    v_4 = i32(v_146);
    v_147 = i32(1);
    v_148 = _c_i64_0;
    v_149 = i64_ge(v_131, v_148);
    v_150 = _c_i64_1;
    v_151 = i64_le(v_131, v_150);
    v_5 = v_149 & v_151;
    v_152 = i64_to_i32(v_131);
    v_153 = i32(0);
    v_154 = true;
    v_155 = v_152 > v_147;
    v_156 = i32(0);
    v_157 = false;
    v_158 = i32(0);
    v_159 = v_152 == v_158;
    let v_160 = &param3_f0[(i32(_scalar_params[2]) + v_147)];
    v_161 = *v_160;
    v_6 = i32(v_161);
    v_162 = i32(2);
    v_163 = _c_i64_0;
    v_164 = i64_ge(v_131, v_163);
    v_165 = _c_i64_1;
    v_166 = i64_le(v_131, v_165);
    v_7 = v_164 & v_166;
    v_167 = i64_to_i32(v_131);
    v_168 = i32(0);
    v_169 = true;
    v_170 = v_167 > v_162;
    v_171 = i32(0);
    v_172 = false;
    v_173 = i32(0);
    v_174 = v_167 == v_173;
    let v_175 = &param3_f0[(i32(_scalar_params[2]) + v_162)];
    v_176 = *v_175;
    v_177 = i32(v_176);
    v_178 = i32(3);
    v_179 = _c_i64_0;
    v_180 = i64_ge(v_131, v_179);
    v_181 = _c_i64_1;
    v_182 = i64_le(v_131, v_181);
    v_8 = v_180 & v_182;
    v_183 = i64_to_i32(v_131);
    v_184 = i32(0);
    v_185 = true;
    v_186 = v_183 > v_178;
    v_187 = i32(0);
    v_188 = false;
    v_189 = i32(0);
    v_190 = v_183 == v_189;
    let v_191 = &param3_f0[(i32(_scalar_params[2]) + v_178)];
    v_192 = *v_191;
    v_193 = i32(v_192);
    v_9 = v_124 / v_177;
    v_10 = v_124 % v_177;
    v_194 = f32(v_9);
    v_195 = f32(0.5);
    v_11 = v_194 + v_195;
    v_196 = f32(v_6);
    v_12 = v_11 * v_196;
    v_197 = f32(v_193);
    v_13 = v_12 / v_197;
    v_198 = f32(0.5);
    v_14 = v_13 - v_198;
    v_199 = f32(v_10);
    v_200 = f32(0.5);
    v_15 = v_199 + v_200;
    v_201 = f32(v_4);
    v_16 = v_15 * v_201;
    v_202 = f32(v_177);
    v_17 = v_16 / v_202;
    v_203 = f32(0.5);
    v_18 = v_17 - v_203;
    v_19 = i32(v_14);
    v_204 = i32(1);
    v_20 = v_19 + v_204;
    v_21 = i32(v_18);
    v_205 = i32(1);
    v_22 = v_21 + v_205;
    v_206 = f32(v_19);
    v_23 = v_14 - v_206;
    v_207 = f32(v_21);
    v_24 = v_18 - v_207;
    v_208 = i32(0);
    v_209 = v_19 >= v_208;
    if (!v_209) {
        v_25 = i32(0);
        v_26 = v_25;
    } else {
        v_26 = v_19;
    }
    v_210 = v_20 < v_6;
    v_211 = i32(1);
    v_27 = v_6 - v_211;
    v_212 = select(v_27, v_20, v_210);
    v_213 = i32(0);
    v_214 = v_21 >= v_213;
    v_215 = i32(0);
    v_216 = select(v_215, v_21, v_214);
    v_217 = v_22 < v_4;
    v_218 = i32(1);
    v_28 = v_4 - v_218;
    v_219 = select(v_28, v_22, v_217);
    v_29 = v_26 * v_4;
    v_30 = v_29 + v_216;
    v_220 = _c_i64_0;
    v_221 = i64_ge(v_0, v_220);
    v_222 = _c_i64_1;
    v_223 = i64_le(v_0, v_222);
    v_31 = v_221 & v_223;
    v_224 = i64_to_i32(v_0);
    v_225 = i32(0);
    v_226 = v_30 >= v_225;
    v_227 = v_30 < v_224;
    v_32 = v_226 & v_227;
    v_228 = i32(0);
    v_229 = v_30 == v_228;
    v_230 = i32(0);
    v_231 = v_224 == v_230;
    v_33 = v_229 & v_231;
    v_34 = v_32 | v_33;
    let v_232 = &param1_f0[(i32(_scalar_params[0]) + v_30)];
    v_233 = *v_232;
    v_234 = i32(255);
    v_35 = v_233 & v_234;
    v_235 = f32(v_35);
    v_236 = f32(255.0);
    v_36 = v_235 / v_236;
    v_237 = i32(8);
    v_37 = v_233 >> u32(v_237);
    v_238 = i32(255);
    v_38 = v_37 & v_238;
    v_239 = f32(v_38);
    v_240 = f32(255.0);
    v_39 = v_239 / v_240;
    v_241 = i32(16);
    v_40 = v_233 >> u32(v_241);
    v_242 = i32(255);
    v_41 = v_40 & v_242;
    v_243 = f32(v_41);
    v_244 = f32(255.0);
    v_42 = v_243 / v_244;
    v_245 = f32(0.298999995);
    v_43 = v_36 * v_245;
    v_246 = f32(0.587000012);
    v_44 = v_39 * v_246;
    v_45 = v_43 + v_44;
    v_247 = f32(0.114);
    v_46 = v_42 * v_247;
    v_47 = v_45 + v_46;
    v_48 = v_26 * v_4;
    v_49 = v_48 + v_219;
    v_248 = _c_i64_0;
    v_249 = i64_ge(v_0, v_248);
    v_250 = _c_i64_1;
    v_251 = i64_le(v_0, v_250);
    v_50 = v_249 & v_251;
    v_252 = i64_to_i32(v_0);
    v_253 = i32(0);
    v_254 = v_49 >= v_253;
    v_255 = v_49 < v_252;
    v_51 = v_254 & v_255;
    v_256 = i32(0);
    v_257 = v_49 == v_256;
    v_258 = i32(0);
    v_259 = v_252 == v_258;
    v_52 = v_257 & v_259;
    v_53 = v_51 | v_52;
    let v_260 = &param1_f0[(i32(_scalar_params[0]) + v_49)];
    v_261 = *v_260;
    v_262 = i32(255);
    v_54 = v_261 & v_262;
    v_263 = f32(v_54);
    v_264 = f32(255.0);
    v_55 = v_263 / v_264;
    v_265 = i32(8);
    v_56 = v_261 >> u32(v_265);
    v_266 = i32(255);
    v_57 = v_56 & v_266;
    v_267 = f32(v_57);
    v_268 = f32(255.0);
    v_58 = v_267 / v_268;
    v_269 = i32(16);
    v_59 = v_261 >> u32(v_269);
    v_270 = i32(255);
    v_60 = v_59 & v_270;
    v_271 = f32(v_60);
    v_272 = f32(255.0);
    v_61 = v_271 / v_272;
    v_273 = f32(0.298999995);
    v_62 = v_55 * v_273;
    v_274 = f32(0.587000012);
    v_63 = v_58 * v_274;
    v_64 = v_62 + v_63;
    v_275 = f32(0.114);
    v_65 = v_61 * v_275;
    v_66 = v_64 + v_65;
    v_67 = v_212 * v_4;
    v_68 = v_67 + v_216;
    v_276 = _c_i64_0;
    v_277 = i64_ge(v_0, v_276);
    v_278 = _c_i64_1;
    v_279 = i64_le(v_0, v_278);
    v_69 = v_277 & v_279;
    v_280 = i64_to_i32(v_0);
    v_281 = i32(0);
    v_282 = v_68 >= v_281;
    v_283 = v_68 < v_280;
    v_70 = v_282 & v_283;
    v_284 = i32(0);
    v_285 = v_68 == v_284;
    v_286 = i32(0);
    v_287 = v_280 == v_286;
    v_71 = v_285 & v_287;
    v_72 = v_70 | v_71;
    let v_288 = &param1_f0[(i32(_scalar_params[0]) + v_68)];
    v_289 = *v_288;
    v_290 = i32(255);
    v_73 = v_289 & v_290;
    v_291 = f32(v_73);
    v_292 = f32(255.0);
    v_74 = v_291 / v_292;
    v_293 = i32(8);
    v_75 = v_289 >> u32(v_293);
    v_294 = i32(255);
    v_76 = v_75 & v_294;
    v_295 = f32(v_76);
    v_296 = f32(255.0);
    v_77 = v_295 / v_296;
    v_297 = i32(16);
    v_78 = v_289 >> u32(v_297);
    v_298 = i32(255);
    v_79 = v_78 & v_298;
    v_299 = f32(v_79);
    v_300 = f32(255.0);
    v_80 = v_299 / v_300;
    v_301 = f32(0.298999995);
    v_81 = v_74 * v_301;
    v_302 = f32(0.587000012);
    v_82 = v_77 * v_302;
    v_83 = v_81 + v_82;
    v_303 = f32(0.114);
    v_84 = v_80 * v_303;
    v_85 = v_83 + v_84;
    v_86 = v_212 * v_4;
    v_87 = v_86 + v_219;
    v_304 = _c_i64_0;
    v_305 = i64_ge(v_0, v_304);
    v_306 = _c_i64_1;
    v_307 = i64_le(v_0, v_306);
    v_88 = v_305 & v_307;
    v_308 = i64_to_i32(v_0);
    v_309 = i32(0);
    v_310 = v_87 >= v_309;
    v_311 = v_87 < v_308;
    v_89 = v_310 & v_311;
    v_312 = i32(0);
    v_313 = v_87 == v_312;
    v_314 = i32(0);
    v_315 = v_308 == v_314;
    v_90 = v_313 & v_315;
    v_91 = v_89 | v_90;
    let v_316 = &param1_f0[(i32(_scalar_params[0]) + v_87)];
    v_317 = *v_316;
    v_318 = i32(255);
    v_92 = v_317 & v_318;
    v_319 = f32(v_92);
    v_320 = f32(255.0);
    v_93 = v_319 / v_320;
    v_321 = i32(8);
    v_94 = v_317 >> u32(v_321);
    v_322 = i32(255);
    v_95 = v_94 & v_322;
    v_323 = f32(v_95);
    v_324 = f32(255.0);
    v_96 = v_323 / v_324;
    v_325 = i32(16);
    v_97 = v_317 >> u32(v_325);
    v_326 = i32(255);
    v_98 = v_97 & v_326;
    v_327 = f32(v_98);
    v_328 = f32(255.0);
    v_99 = v_327 / v_328;
    v_329 = f32(0.298999995);
    v_100 = v_93 * v_329;
    v_330 = f32(0.587000012);
    v_101 = v_96 * v_330;
    v_102 = v_100 + v_101;
    v_331 = f32(0.114);
    v_103 = v_99 * v_331;
    v_104 = v_102 + v_103;
    v_332 = _c_i64_0;
    v_333 = i64_ge(v_1, v_332);
    v_334 = _c_i64_1;
    v_335 = i64_le(v_1, v_334);
    v_105 = v_333 & v_335;
    v_336 = i64_to_i32(v_1);
    v_337 = i32(0);
    v_338 = v_124 >= v_337;
    v_339 = v_124 < v_336;
    v_106 = v_338 & v_339;
    v_340 = i32(0);
    v_341 = v_124 == v_340;
    v_342 = i32(0);
    v_343 = v_336 == v_342;
    v_107 = v_341 & v_343;
    v_108 = v_106 | v_107;
    let v_344 = &param2_f0[(i32(_scalar_params[1]) + v_124)];
    v_345 = f32(1.0);
    v_109 = v_345 - v_23;
    v_110 = v_47 * v_109;
    v_346 = f32(1.0);
    v_111 = v_346 - v_24;
    v_112 = v_110 * v_111;
    v_347 = f32(1.0);
    v_113 = v_347 - v_23;
    v_114 = v_66 * v_113;
    v_115 = v_114 * v_24;
    v_116 = v_112 + v_115;
    v_117 = v_85 * v_23;
    v_348 = f32(1.0);
    v_118 = v_348 - v_24;
    v_119 = v_117 * v_118;
    v_120 = v_116 + v_119;
    v_121 = v_104 * v_23;
    v_122 = v_121 * v_24;
    v_123 = v_120 + v_122;
    *v_344 = v_123;
    return;
}
