// Kernel: SigmoidInPlaceImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 2
// Time: 2026-03-24T02:16:10.5140000Z

// Kernel: SigmoidInPlaceImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: SigmoidInPlaceImpl_43
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
@group(0) @binding(1) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : bool = false;
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : bool = false;
    var v_5 : f32 = 0.0;
    var v_6 : bool = false;
    var v_7 : bool = false;
    var v_8 : bool = false;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : bool = false;
    var v_13 : bool = false;
    var v_14 : bool = false;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : bool = false;
    var v_18 : f32 = 0.0;
    var v_19 : f32 = 0.0;
    var v_20 : f32 = 0.0;
    var v_21 : f32 = 0.0;
    var v_22 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_22) >= _ilgpu_user_dim) { return; }
    let v_23_f0 = &param1_f0;
    var v_23_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    var v_25 : emu_i64;
    var v_27 : emu_i64;
    var v_30 : i32;
    var v_33 : i32;
    var v_35 : i32;
    var v_38 : f32;
    var v_40 : f32;
    var v_42 : emu_i64;
    var v_44 : emu_i64;
    var v_47 : i32;
    var v_50 : i32;
    var v_52 : i32;
    var v_55 : f32;
    var v_56 : emu_i64;
    var v_58 : emu_i64;
    var v_61 : i32;
    var v_64 : i32;
    var v_66 : i32;
    var v_69 : f32;
    var v_70 : emu_i64;
    var v_72 : emu_i64;
    var v_75 : i32;
    var v_78 : i32;
    var v_80 : i32;
    var v_83 : f32;
    var v_26 : bool;
    var v_28 : bool;
    var v_29 : i32;
    var v_31 : bool;
    var v_32 : bool;
    var v_34 : bool;
    var v_36 : bool;
    var v_39 : bool;
    var v_41 : bool;
    var v_43 : bool;
    var v_45 : bool;
    var v_46 : i32;
    var v_48 : bool;
    var v_49 : bool;
    var v_51 : bool;
    var v_53 : bool;
    var v_57 : bool;
    var v_59 : bool;
    var v_60 : i32;
    var v_62 : bool;
    var v_63 : bool;
    var v_65 : bool;
    var v_67 : bool;
    var v_71 : bool;
    var v_73 : bool;
    var v_74 : i32;
    var v_76 : bool;
    var v_77 : bool;
    var v_79 : bool;
    var v_81 : bool;






























    let v_24 = v_23_f0;

    v_0 = v_23_f1;
    v_25 = _c_i64_0;
    v_26 = i64_ge(v_0, v_25);
    v_27 = _c_i64_1;
    v_28 = i64_le(v_0, v_27);
    v_1 = v_26 & v_28;
    v_29 = i64_to_i32(v_0);
    v_30 = i32(0);
    v_31 = v_22 >= v_30;
    v_32 = v_22 < v_29;
    v_2 = v_31 & v_32;
    v_33 = i32(0);
    v_34 = v_22 == v_33;
    v_35 = i32(0);
    v_36 = v_29 == v_35;
    v_3 = v_34 & v_36;
    v_4 = v_2 | v_3;
    let v_37 = &param1_f0[(i32(_scalar_params[0]) + v_22)];
    v_5 = *v_37;
    v_38 = f32(80.0);
    v_39 = v_5 <= v_38;
    if (v_39) {
        v_40 = f32(-80.0);
        v_41 = v_5 >= v_40;
        if (v_41) {
            v_42 = _c_i64_0;
            v_43 = i64_ge(v_0, v_42);
            v_44 = _c_i64_1;
            v_45 = i64_le(v_0, v_44);
            v_14 = v_43 & v_45;
            v_46 = i64_to_i32(v_0);
            v_47 = i32(0);
            v_48 = v_22 >= v_47;
            v_49 = v_22 < v_46;
            v_15 = v_48 & v_49;
            v_50 = i32(0);
            v_51 = v_22 == v_50;
            v_52 = i32(0);
            v_53 = v_46 == v_52;
            v_16 = v_51 & v_53;
            v_17 = v_15 | v_16;
            let v_54 = &param1_f0[(i32(_scalar_params[0]) + v_22)];
            v_55 = f32(1.0);
            v_18 = -v_5;
            v_19 = exp(v_18);
            v_20 = v_19 + v_55;
            v_21 = 1.0 / v_20;
            *v_54 = v_21;
        } else {
            v_56 = _c_i64_0;
            v_57 = i64_ge(v_0, v_56);
            v_58 = _c_i64_1;
            v_59 = i64_le(v_0, v_58);
            v_10 = v_57 & v_59;
            v_60 = i64_to_i32(v_0);
            v_61 = i32(0);
            v_62 = v_22 >= v_61;
            v_63 = v_22 < v_60;
            v_11 = v_62 & v_63;
            v_64 = i32(0);
            v_65 = v_22 == v_64;
            v_66 = i32(0);
            v_67 = v_60 == v_66;
            v_12 = v_65 & v_67;
            v_13 = v_11 | v_12;
            let v_68 = &param1_f0[(i32(_scalar_params[0]) + v_22)];
            v_69 = f32(0.0);
            *v_68 = v_69;
        }
    } else {
        v_70 = _c_i64_0;
        v_71 = i64_ge(v_0, v_70);
        v_72 = _c_i64_1;
        v_73 = i64_le(v_0, v_72);
        v_6 = v_71 & v_73;
        v_74 = i64_to_i32(v_0);
        v_75 = i32(0);
        v_76 = v_22 >= v_75;
        v_77 = v_22 < v_74;
        v_7 = v_76 & v_77;
        v_78 = i32(0);
        v_79 = v_22 == v_78;
        v_80 = i32(0);
        v_81 = v_74 == v_80;
        v_8 = v_79 & v_81;
        v_9 = v_7 | v_8;
        let v_82 = &param1_f0[(i32(_scalar_params[0]) + v_22)];
        v_83 = f32(1.0);
        *v_82 = v_83;
    }
    return;
}
