// Kernel: ConvTranspose2DImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 6
// Time: 2026-03-24T02:16:19.8530000Z

// Kernel: ConvTranspose2DImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: ConvTranspose2DImpl_128
// WorkgroupSize: 64
// Emulation: i64, f64


// ============ 64-bit Emulation Library ============
alias emu_f64 = vec2<f32>;
// Create emu_f64 from a single f32 value
fn f64_from_f32(v: f32) -> emu_f64 {
    return emu_f64(v, 0.0);
}

// Convert emu_f64 back to f32 (loses precision)
fn f64_to_f32(v: emu_f64) -> f32 {
    return v.x + v.y;
}

// emu_f64 addition using Dekker's algorithm
fn f64_add(a: emu_f64, b: emu_f64) -> emu_f64 {
    let s = a.x + b.x;
    let v = s - a.x;
    let e = (a.x - (s - v)) + (b.x - v) + a.y + b.y;
    let z_hi = s + e;
    let z_lo = e - (z_hi - s);
    return emu_f64(z_hi, z_lo);
}

// Helper: split f32 into high and low parts for multiplication
fn f64_split(a: f32) -> vec2<f32> {
    let c = 4097.0 * a;  // 2^12 + 1
    let a_hi = c - (c - a);
    let a_lo = a - a_hi;
    return vec2<f32>(a_hi, a_lo);
}

// Helper: two-product algorithm (exact a*b = p + e)
fn f64_two_prod(a: f32, b: f32) -> emu_f64 {
    let p = a * b;
    let a_s = f64_split(a);
    let b_s = f64_split(b);
    let e = ((a_s.x * b_s.x - p) + a_s.x * b_s.y + a_s.y * b_s.x) + a_s.y * b_s.y;
    return emu_f64(p, e);
}

// emu_f64 multiplication
fn f64_mul(a: emu_f64, b: emu_f64) -> emu_f64 {
    let p = f64_two_prod(a.x, b.x);
    let e = a.x * b.y + a.y * b.x + p.y;
    let z_hi = p.x + e;
    let z_lo = e - (z_hi - p.x);
    return emu_f64(z_hi, z_lo);
}

alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

struct struct_10132 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(3) var<storage, read_write> param4_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 5: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(4) var<storage, read_write> param5_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
// View offset for param3000 at scalar slot 1
// View offset for param4000 at scalar slot 2
// View offset for param5000 at scalar slot 3
// View offset for param6000 at scalar slot 4
@group(0) @binding(5) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : bool = false;
    var v_2 : bool = false;
    var v_3 : i32 = 0;
    var v_4 : bool = false;
    var v_5 : i32 = 0;
    var v_6 : bool = false;
    var v_7 : i32 = 0;
    var v_8 : bool = false;
    var v_9 : i32 = 0;
    var v_10 : bool = false;
    var v_11 : i32 = 0;
    var v_12 : bool = false;
    var v_13 : i32 = 0;
    var v_14 : bool = false;
    var v_15 : i32 = 0;
    var v_16 : bool = false;
    var v_17 : i32 = 0;
    var v_18 : i32 = 0;
    var v_19 : i32 = 0;
    var v_20 : i32 = 0;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : i32 = 0;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : i32 = 0;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : i32 = 0;
    var v_32 : bool = false;
    var v_33 : bool = false;
    var v_34 : bool = false;
    var v_35 : bool = false;
    var v_36 : emu_f64 = emu_f64(0.0, 0.0);
    var v_37 : i32 = 0;
    var v_38 : bool = false;
    var v_39 : i32 = 0;
    var v_40 : bool = false;
    var v_41 : bool = false;
    var v_42 : i32 = 0;
    var v_43 : bool = false;
    var v_44 : emu_f64 = emu_f64(0.0, 0.0);
    var v_45 : i32 = 0;
    var v_46 : bool = false;
    var v_47 : bool = false;
    var v_48 : bool = false;
    var v_49 : bool = false;
    var v_50 : i32 = 0;
    var v_51 : i32 = 0;
    var v_52 : emu_f64 = emu_f64(0.0, 0.0);
    var v_53 : i32 = 0;
    var v_54 : i32 = 0;
    var v_55 : i32 = 0;
    var v_56 : i32 = 0;
    var v_57 : i32 = 0;
    var v_58 : i32 = 0;
    var v_59 : i32 = 0;
    var v_60 : emu_f64 = emu_f64(0.0, 0.0);
    var v_61 : i32 = 0;
    var v_62 : i32 = 0;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    var v_65 : i32 = 0;
    var v_66 : i32 = 0;
    var v_67 : i32 = 0;
    var v_68 : i32 = 0;
    var v_69 : i32 = 0;
    var v_70 : bool = false;
    var v_71 : bool = false;
    var v_72 : bool = false;
    var v_73 : i32 = 0;
    var v_74 : i32 = 0;
    var v_75 : i32 = 0;
    var v_76 : i32 = 0;
    var v_77 : i32 = 0;
    var v_78 : i32 = 0;
    var v_79 : i32 = 0;
    var v_80 : i32 = 0;
    var v_81 : i32 = 0;
    var v_82 : bool = false;
    var v_83 : bool = false;
    var v_84 : bool = false;
    var v_85 : emu_f64 = emu_f64(0.0, 0.0);
    var v_86 : emu_f64 = emu_f64(0.0, 0.0);
    var v_87 : emu_f64 = emu_f64(0.0, 0.0);
    var v_88 : i32 = 0;
    var v_89 : emu_f64 = emu_f64(0.0, 0.0);
    var v_90 : i32 = 0;
    var v_91 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_91) >= _ilgpu_user_dim) { return; }
    let v_92_f0 = &param1_f0;
    var v_92_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_93_f0 = &param2_f0;
    var v_93_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_94_f0 = &param3_f0;
    var v_94_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    let v_95_f0 = &param4_f0;
    var v_95_f1 = i64_from_i32(i32(arrayLength(&param4_f0)));
    let v_96_f0 = &param5_f0;
    var v_96_f1 = i64_from_i32(i32(arrayLength(&param5_f0)));
    var v_106 : i32;
    var v_107 : emu_i64;
    var v_109 : emu_i64;
    var v_113 : i32;
    var v_116 : i32;
    var v_117 : emu_i64;
    var v_119 : emu_i64;
    var v_124 : i32;
    var v_125 : emu_i64;
    var v_127 : emu_i64;
    var v_132 : i32;
    var v_133 : emu_i64;
    var v_135 : emu_i64;
    var v_140 : i32;
    var v_141 : emu_i64;
    var v_143 : emu_i64;
    var v_148 : i32;
    var v_149 : emu_i64;
    var v_151 : emu_i64;
    var v_156 : i32;
    var v_157 : emu_i64;
    var v_159 : emu_i64;
    var v_164 : i32;
    var v_165 : emu_i64;
    var v_167 : emu_i64;
    var v_172 : i32;
    var v_173 : i32;
    var v_174 : i32;
    var v_175 : i32;
    var v_176 : emu_i64;
    var v_178 : emu_i64;
    var v_181 : i32;
    var v_184 : i32;
    var v_186 : i32;
    var v_189 : f32;
    var v_190 : emu_i64;
    var v_192 : emu_i64;
    var v_194 : i32;
    var v_195 : emu_i64;
    var v_197 : emu_i64;
    var v_199 : i32;
    var v_202 : i32;
    var v_204 : i32;
    var v_208 : i32;
    var v_210 : i32;
    var v_213 : i32;
    var v_216 : i32;
    var v_219 : f32;
    var v_221 : i32;
    var v_224 : i32;
    var v_227 : f32;
    var v_229 : i32;
    var v_230 : i32;
    var v_231 : i32;
    var v_232 : emu_i64;
    var v_234 : emu_i64;
    var v_237 : i32;
    var v_240 : i32;
    var v_242 : i32;
    var v_98 : emu_i64;
    var v_100 : emu_i64;
    var v_102 : emu_i64;
    var v_105 : emu_i64;
    var v_108 : bool;
    var v_110 : bool;
    var v_111 : i32;
    var v_112 : bool;
    var v_114 : bool;
    var v_118 : bool;
    var v_120 : bool;
    var v_121 : i32;
    var v_122 : bool;
    var v_126 : bool;
    var v_128 : bool;
    var v_129 : i32;
    var v_130 : bool;
    var v_134 : bool;
    var v_136 : bool;
    var v_137 : i32;
    var v_138 : bool;
    var v_142 : bool;
    var v_144 : bool;
    var v_145 : i32;
    var v_146 : bool;
    var v_150 : bool;
    var v_152 : bool;
    var v_153 : i32;
    var v_154 : bool;
    var v_158 : bool;
    var v_160 : bool;
    var v_161 : i32;
    var v_162 : bool;
    var v_166 : bool;
    var v_168 : bool;
    var v_169 : i32;
    var v_170 : bool;
    var v_177 : bool;
    var v_179 : bool;
    var v_180 : i32;
    var v_182 : bool;
    var v_183 : bool;
    var v_185 : bool;
    var v_187 : bool;
    var v_191 : bool;
    var v_193 : bool;
    var v_196 : bool;
    var v_198 : bool;
    var v_200 : bool;
    var v_201 : bool;
    var v_203 : bool;
    var v_205 : bool;
    var v_206 : bool;
    var v_207 : bool;
    var v_209 : bool;
    var v_211 : bool;
    var v_212 : bool;
    var v_214 : bool;
    var v_215 : bool;
    var v_217 : bool;
    var v_220 : emu_f64;
    var v_222 : bool;
    var v_223 : bool;
    var v_225 : bool;
    var v_228 : emu_f64;
    var v_233 : bool;
    var v_235 : bool;
    var v_236 : i32;
    var v_238 : bool;
    var v_239 : bool;
    var v_241 : bool;
    var v_243 : bool;
    var v_245 : f32;









































































    let v_97 = v_92_f0;
    let v_99 = v_93_f0;
    let v_101 = v_94_f0;
    let v_103 = v_95_f0;
    let v_104 = v_96_f0;

    v_98 = v_92_f1;

    v_100 = v_93_f1;

    v_102 = v_94_f1;

    v_0 = v_95_f1;

    v_105 = v_96_f1;
    v_106 = i32(0);
    v_107 = _c_i64_0;
    v_108 = i64_ge(v_105, v_107);
    v_109 = _c_i64_1;
    v_110 = i64_le(v_105, v_109);
    v_1 = v_108 & v_110;
    v_111 = i64_to_i32(v_105);
    v_112 = v_111 > v_106;
    v_113 = i32(0);
    v_114 = v_111 == v_113;
    v_2 = v_112 | v_114;
    let v_115 = &param5_f0[(i32(_scalar_params[4]) + v_106)];
    v_3 = *v_115;
    v_116 = i32(1);
    v_117 = _c_i64_0;
    v_118 = i64_ge(v_105, v_117);
    v_119 = _c_i64_1;
    v_120 = i64_le(v_105, v_119);
    v_4 = v_118 & v_120;
    v_121 = i64_to_i32(v_105);
    v_122 = v_121 > v_116;
    let v_123 = &param5_f0[(i32(_scalar_params[4]) + v_116)];
    v_5 = *v_123;
    v_124 = i32(2);
    v_125 = _c_i64_0;
    v_126 = i64_ge(v_105, v_125);
    v_127 = _c_i64_1;
    v_128 = i64_le(v_105, v_127);
    v_6 = v_126 & v_128;
    v_129 = i64_to_i32(v_105);
    v_130 = v_129 > v_124;
    let v_131 = &param5_f0[(i32(_scalar_params[4]) + v_124)];
    v_7 = *v_131;
    v_132 = i32(3);
    v_133 = _c_i64_0;
    v_134 = i64_ge(v_105, v_133);
    v_135 = _c_i64_1;
    v_136 = i64_le(v_105, v_135);
    v_8 = v_134 & v_136;
    v_137 = i64_to_i32(v_105);
    v_138 = v_137 > v_132;
    let v_139 = &param5_f0[(i32(_scalar_params[4]) + v_132)];
    v_9 = *v_139;
    v_140 = i32(4);
    v_141 = _c_i64_0;
    v_142 = i64_ge(v_105, v_141);
    v_143 = _c_i64_1;
    v_144 = i64_le(v_105, v_143);
    v_10 = v_142 & v_144;
    v_145 = i64_to_i32(v_105);
    v_146 = v_145 > v_140;
    let v_147 = &param5_f0[(i32(_scalar_params[4]) + v_140)];
    v_11 = *v_147;
    v_148 = i32(5);
    v_149 = _c_i64_0;
    v_150 = i64_ge(v_105, v_149);
    v_151 = _c_i64_1;
    v_152 = i64_le(v_105, v_151);
    v_12 = v_150 & v_152;
    v_153 = i64_to_i32(v_105);
    v_154 = v_153 > v_148;
    let v_155 = &param5_f0[(i32(_scalar_params[4]) + v_148)];
    v_13 = *v_155;
    v_156 = i32(6);
    v_157 = _c_i64_0;
    v_158 = i64_ge(v_105, v_157);
    v_159 = _c_i64_1;
    v_160 = i64_le(v_105, v_159);
    v_14 = v_158 & v_160;
    v_161 = i64_to_i32(v_105);
    v_162 = v_161 > v_156;
    let v_163 = &param5_f0[(i32(_scalar_params[4]) + v_156)];
    v_15 = *v_163;
    v_164 = i32(7);
    v_165 = _c_i64_0;
    v_166 = i64_ge(v_105, v_165);
    v_167 = _c_i64_1;
    v_168 = i64_le(v_105, v_167);
    v_16 = v_166 & v_168;
    v_169 = i64_to_i32(v_105);
    v_170 = v_169 > v_164;
    let v_171 = &param5_f0[(i32(_scalar_params[4]) + v_164)];
    v_17 = *v_171;
    v_172 = i32(1);
    v_18 = v_5 - v_172;
    v_19 = v_18 * v_15;
    v_173 = i32(1);
    v_20 = v_17 << u32(v_173);
    v_21 = v_19 - v_20;
    v_22 = v_21 + v_11;
    v_174 = i32(1);
    v_23 = v_7 - v_174;
    v_24 = v_23 * v_15;
    v_175 = i32(1);
    v_25 = v_17 << u32(v_175);
    v_26 = v_24 - v_25;
    v_27 = v_26 + v_13;
    v_28 = v_91 % v_27;
    v_29 = v_91 / v_27;
    v_30 = v_29 % v_22;
    v_31 = v_29 / v_22;
    v_176 = _c_i64_0;
    v_177 = i64_ge(v_102, v_176);
    v_178 = _c_i64_1;
    v_179 = i64_le(v_102, v_178);
    v_32 = v_177 & v_179;
    v_180 = i64_to_i32(v_102);
    v_181 = i32(0);
    v_182 = v_31 >= v_181;
    v_183 = v_31 < v_180;
    v_33 = v_182 & v_183;
    v_184 = i32(0);
    v_185 = v_31 == v_184;
    v_186 = i32(0);
    v_187 = v_180 == v_186;
    v_34 = v_185 & v_187;
    v_35 = v_33 | v_34;
    let v_188 = &param3_f0[(i32(_scalar_params[2]) + v_31)];
    v_189 = *v_188;
    v_36 = f64_from_f32(v_189);
    v_37 = i32(0);
    v_190 = _c_i64_0;
    v_191 = i64_ge(v_98, v_190);
    v_192 = _c_i64_1;
    v_193 = i64_le(v_98, v_192);
    v_38 = v_191 & v_193;
    v_39 = i64_to_i32(v_98);
    v_194 = i32(0);
    v_40 = v_39 == v_194;
    v_195 = _c_i64_0;
    v_196 = i64_ge(v_100, v_195);
    v_197 = _c_i64_1;
    v_198 = i64_le(v_100, v_197);
    v_41 = v_196 & v_198;
    v_42 = i64_to_i32(v_100);
    v_199 = i32(0);
    v_43 = v_42 == v_199;
    v_44 = v_36;
    v_45 = v_37;
    loop {
        v_200 = v_45 < v_3;
        if (!v_200) {
            break;
        }
        v_50 = i32(0);
        v_51 = v_50;
        v_52 = v_44;
        loop {
            v_201 = v_51 < v_11;
            if (!v_201) {
                break;
            }
            v_54 = v_30 + v_17;
            v_55 = v_54 - v_51;
            v_202 = i32(0);
            v_203 = v_55 < v_202;
            if (!v_203) {
                v_56 = v_55 % v_15;
                v_204 = i32(0);
                v_205 = v_56 != v_204;
                if (!v_205) {
                    v_57 = v_55 / v_15;
                    v_206 = v_57 >= v_5;
                    if (!v_206) {
                        v_58 = i32(0);
                        v_59 = v_58;
                        v_60 = v_52;
                        loop {
                            v_207 = v_59 < v_13;
                            if (!v_207) {
                                v_89 = v_60;
                                break;
                            }
                            v_61 = v_28 + v_17;
                            v_62 = v_61 - v_59;
                            v_208 = i32(0);
                            v_209 = v_62 < v_208;
                            if (!v_209) {
                                v_63 = v_62 % v_15;
                                v_210 = i32(0);
                                v_211 = v_63 != v_210;
                                if (!v_211) {
                                    v_64 = v_62 / v_15;
                                    v_212 = v_64 >= v_7;
                                    if (!v_212) {
                                        v_65 = v_45 * v_5;
                                        v_66 = v_65 * v_7;
                                        v_67 = v_57 * v_7;
                                        v_68 = v_66 + v_67;
                                        v_69 = v_68 + v_64;
                                        v_213 = i32(0);
                                        v_214 = v_69 >= v_213;
                                        v_215 = v_69 < v_39;
                                        v_70 = v_214 & v_215;
                                        v_216 = i32(0);
                                        v_217 = v_69 == v_216;
                                        v_71 = v_217 & v_40;
                                        v_72 = v_70 | v_71;
                                        let v_218 = &param1_f0[(i32(_scalar_params[0]) + v_69)];
                                        v_219 = *v_218;
                                        v_220 = f64_from_f32(v_219);
                                        v_73 = v_45 * v_9;
                                        v_74 = v_73 * v_11;
                                        v_75 = v_74 * v_13;
                                        v_76 = v_31 * v_11;
                                        v_77 = v_76 * v_13;
                                        v_78 = v_75 + v_77;
                                        v_79 = v_51 * v_13;
                                        v_80 = v_78 + v_79;
                                        v_81 = v_80 + v_59;
                                        v_221 = i32(0);
                                        v_222 = v_81 >= v_221;
                                        v_223 = v_81 < v_42;
                                        v_82 = v_222 & v_223;
                                        v_224 = i32(0);
                                        v_225 = v_81 == v_224;
                                        v_83 = v_225 & v_43;
                                        v_84 = v_82 | v_83;
                                        let v_226 = &param2_f0[(i32(_scalar_params[1]) + v_81)];
                                        v_227 = *v_226;
                                        v_228 = f64_from_f32(v_227);
                                        v_85 = f64_mul(v_220, v_228);
                                        v_86 = f64_add(v_60, v_85);
                                        v_87 = v_86;
                                    } else {
                                        v_87 = v_60;
                                    }
                                } else {
                                    v_87 = v_60;
                                }
                            } else {
                                v_87 = v_60;
                            }
                            v_229 = i32(1);
                            v_88 = v_59 + v_229;
                            v_59 = v_88;
                            v_60 = v_87;
                        }
                    } else {
                        v_89 = v_52;
                    }
                } else {
                    v_89 = v_52;
                }
            } else {
                v_89 = v_52;
            }
            v_230 = i32(1);
            v_90 = v_51 + v_230;
            v_51 = v_90;
            v_52 = v_89;
        }
        v_231 = i32(1);
        v_53 = v_45 + v_231;
        v_44 = v_52;
        v_45 = v_53;
    }
    v_232 = _c_i64_0;
    v_233 = i64_ge(v_0, v_232);
    v_234 = _c_i64_1;
    v_235 = i64_le(v_0, v_234);
    v_46 = v_233 & v_235;
    v_236 = i64_to_i32(v_0);
    v_237 = i32(0);
    v_238 = v_91 >= v_237;
    v_239 = v_91 < v_236;
    v_47 = v_238 & v_239;
    v_240 = i32(0);
    v_241 = v_91 == v_240;
    v_242 = i32(0);
    v_243 = v_236 == v_242;
    v_48 = v_241 & v_243;
    v_49 = v_47 | v_48;
    let v_244 = &param4_f0[(i32(_scalar_params[3]) + v_91)];
    v_245 = f64_to_f32(v_44);
    *v_244 = v_245;
    return;
}
