// Kernel: RMSNormStatsImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 3
// Time: 2026-03-24T00:40:35.7620000Z

// Kernel: RMSNormStatsImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: RMSNormStatsImpl_166
// WorkgroupSize: 64
// Emulation: i64, f64


// ============ 64-bit Emulation Library ============
alias emu_f64 = vec2<f32>;
// --- IEEE 754 double bits to double-float conversion ---
// Properly splits a 64-bit IEEE 754 double into a double-float emu_f64(hi, lo)
// preserving ~48 bits of mantissa precision via Dekker-style two-sum.
// When CPU sends a raw 64-bit double, we receive it as vec2<u32> (lo, hi bits)
fn f64_from_ieee754_bits(lo: u32, hi: u32) -> emu_f64 {
    let sign_bit = (hi >> 31u) & 1u;
    let exponent = (hi >> 20u) & 0x7FFu;
    let mantissa_hi20 = hi & 0xFFFFFu;
    let mantissa_lo32 = lo;

    // Zero
    if (exponent == 0u && mantissa_hi20 == 0u && mantissa_lo32 == 0u) {
        return emu_f64(0.0, 0.0);
    }
    // Inf/NaN: preserve in f32 high word so IsNaN/IsInf propagation works.
    // Map +Inf/-Inf to f32 Inf, NaN to f32 NaN (sign preserved via sign_bit).
    if (exponent == 0x7FFu) {
        let is_nan = (mantissa_hi20 != 0u) || (mantissa_lo32 != 0u);
        if (is_nan) {
            // Produce f32 NaN with sign preserved
            let nan_bits = (sign_bit << 31u) | 0x7FC00000u; // quiet NaN
            return emu_f64(bitcast<f32>(nan_bits), 0.0);
        } else {
            // Produce f32 Inf with sign preserved
            let inf_bits = (sign_bit << 31u) | 0x7F800000u;
            return emu_f64(bitcast<f32>(inf_bits), 0.0);
        }
    }

    let exp_bias: i32 = 1023;
    let exp_val: i32 = i32(exponent) - exp_bias;
    let f32_exp_bias: i32 = 127;
    let f32_exp: i32 = exp_val + f32_exp_bias;

    // Out of f32 exponent range
    if (f32_exp <= 0 || f32_exp >= 255) {
        let f32_bits_approx = (sign_bit << 31u) | (u32(clamp(f32_exp, 1, 254)) << 23u) | (mantissa_hi20 << 3u);
        let val_approx = bitcast<f32>(f32_bits_approx);
        return emu_f64(val_approx, 0.0);
    }

    // Build high part: sign + exponent + top 23 bits of 52-bit mantissa
    // We take all 20 bits from mantissa_hi20 + top 3 bits from mantissa_lo32
    let top23 = (mantissa_hi20 << 3u) | (mantissa_lo32 >> 29u);
    let f32_bits_h = (sign_bit << 31u) | (u32(f32_exp) << 23u) | top23;
    let val_hi = bitcast<f32>(f32_bits_h);

    // Build low part: remaining 29 bits of mantissa, scaled properly
    let remaining = mantissa_lo32 & 0x1FFFFFFFu;
    if (remaining == 0u) {
        return emu_f64(val_hi, 0.0);
    }

    // remaining represents bits at position 2^(exp_val - 52) relative to 1.0
    // = remaining * 2^(-29) * 2^(exp_val - 23)
    let lo_exp: i32 = exp_val - 29 + f32_exp_bias;
    var val_lo: f32 = 0.0;
    if (lo_exp > 0 && lo_exp < 255) {
        let rem_f = f32(remaining);
        let scale_exp: i32 = exp_val - 23 + f32_exp_bias;
        if (scale_exp > 0 && scale_exp < 255) {
            let scale_bits = u32(scale_exp) << 23u;
            let scale = bitcast<f32>(scale_bits);
            val_lo = (rem_f / 536870912.0) * scale;
        }
    }

    if (sign_bit != 0u) {
        val_lo = -val_lo;
    }

    // Inline two-sum normalization (Knuth's algorithm)
    // Cannot call f64_add here as it may be declared later in the library
    let s = val_hi + val_lo;
    let e = val_lo - (s - val_hi);
    return emu_f64(s, e);
}

// Create emu_f64 from a single f32 value
fn f64_from_f32(v: f32) -> emu_f64 {
    return emu_f64(v, 0.0);
}

// Convert emu_f64 back to f32 (loses precision)
fn f64_to_f32(v: emu_f64) -> f32 {
    return v.x + v.y;
}

// emu_f64 negation
fn f64_neg(a: emu_f64) -> emu_f64 {
    return emu_f64(-a.x, -a.y);
}

// emu_f64 addition using Dekker's algorithm
fn f64_add(a: emu_f64, b: emu_f64) -> emu_f64 {
    let s = a.x + b.x;
    let v = s - a.x;
    let e = (a.x - (s - v)) + (b.x - v) + a.y + b.y;
    let z_hi = s + e;
    let z_lo = e - (z_hi - s);
    return emu_f64(z_hi, z_lo);
}

// emu_f64 subtraction
fn f64_sub(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_add(a, f64_neg(b));
}

// Helper: split f32 into high and low parts for multiplication
fn f64_split(a: f32) -> vec2<f32> {
    let c = 4097.0 * a;  // 2^12 + 1
    let a_hi = c - (c - a);
    let a_lo = a - a_hi;
    return vec2<f32>(a_hi, a_lo);
}

// Helper: two-product algorithm (exact a*b = p + e)
fn f64_two_prod(a: f32, b: f32) -> emu_f64 {
    let p = a * b;
    let a_s = f64_split(a);
    let b_s = f64_split(b);
    let e = ((a_s.x * b_s.x - p) + a_s.x * b_s.y + a_s.y * b_s.x) + a_s.y * b_s.y;
    return emu_f64(p, e);
}

// emu_f64 multiplication
fn f64_mul(a: emu_f64, b: emu_f64) -> emu_f64 {
    let p = f64_two_prod(a.x, b.x);
    let e = a.x * b.y + a.y * b.x + p.y;
    let z_hi = p.x + e;
    let z_lo = e - (z_hi - p.x);
    return emu_f64(z_hi, z_lo);
}

// emu_f64 division (approximate)
fn f64_div(a: emu_f64, b: emu_f64) -> emu_f64 {
    let q = a.x / b.x;
    let r = f64_sub(a, f64_mul(b, f64_from_f32(q)));
    let q2 = r.x / b.x;
    return f64_add(f64_from_f32(q), f64_from_f32(q2));
}

alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 4: Float32 (Element: Float32)
// -> Packed scalar at slot 1 (1 slots, type: f32)
// View offset for param2000 at scalar slot 2
// View offset for param3000 at scalar slot 3
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : i32 = 0;
    var v_2 : emu_f64 = emu_f64(0.0, 0.0);
    var v_3 : i32 = 0;
    var v_4 : bool = false;
    var v_5 : i32 = 0;
    var v_6 : bool = false;
    var v_7 : emu_f64 = emu_f64(0.0, 0.0);
    var v_8 : i32 = 0;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : bool = false;
    var v_13 : emu_f64 = emu_f64(0.0, 0.0);
    var v_14 : f32 = 0.0;
    var v_15 : f32 = 0.0;
    var v_16 : f32 = 0.0;
    var v_17 : i32 = 0;
    var v_18 : bool = false;
    var v_19 : bool = false;
    var v_20 : bool = false;
    var v_21 : emu_f64 = emu_f64(0.0, 0.0);
    var v_22 : emu_f64 = emu_f64(0.0, 0.0);
    var v_23 : i32 = 0;
    var v_24 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_24) >= _ilgpu_user_dim) { return; }
    let v_25_f0 = &param1_f0;
    var v_25_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_26_f0 = &param2_f0;
    var v_26_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    var v_27 = bitcast<i32>(_scalar_params[0]);
    var v_28 = bitcast<f32>(_scalar_params[1]);
    var v_32 : emu_i64;
    var v_34 : emu_i64;
    var v_36 : i32;
    var v_38 : i32;
    var v_41 : i32;
    var v_44 : f32;
    var v_46 : i32;
    var v_47 : emu_i64;
    var v_49 : emu_i64;
    var v_52 : i32;
    var v_55 : i32;
    var v_57 : i32;
    var v_30 : emu_i64;
    var v_33 : bool;
    var v_35 : bool;
    var v_37 : bool;
    var v_39 : bool;
    var v_40 : bool;
    var v_42 : bool;
    var v_45 : emu_f64;
    var v_48 : bool;
    var v_50 : bool;
    var v_51 : i32;
    var v_53 : bool;
    var v_54 : bool;
    var v_56 : bool;
    var v_58 : bool;
    var v_60 : emu_f64;
    var v_61 : f32;

















    let v_29 = v_25_f0;
    let v_31 = v_26_f0;

    v_30 = v_25_f1;

    v_0 = v_26_f1;
    v_1 = v_24 * v_27;
    v_2 = f64_from_ieee754_bits(0u, 0u);
    v_3 = i32(0);
    v_32 = _c_i64_0;
    v_33 = i64_ge(v_30, v_32);
    v_34 = _c_i64_1;
    v_35 = i64_le(v_30, v_34);
    v_4 = v_33 & v_35;
    v_5 = i64_to_i32(v_30);
    v_36 = i32(0);
    v_6 = v_5 == v_36;
    v_7 = v_2;
    v_8 = v_3;
    loop {
        v_37 = v_8 < v_27;
        if (!v_37) {
            break;
        }
        v_17 = v_1 + v_8;
        v_38 = i32(0);
        v_39 = v_17 >= v_38;
        v_40 = v_17 < v_5;
        v_18 = v_39 & v_40;
        v_41 = i32(0);
        v_42 = v_17 == v_41;
        v_19 = v_42 & v_6;
        v_20 = v_18 | v_19;
        let v_43 = &param1_f0[(i32(_scalar_params[2]) + v_17)];
        v_44 = *v_43;
        v_45 = f64_from_f32(v_44);
        v_21 = f64_mul(v_45, v_45);
        v_22 = f64_add(v_7, v_21);
        v_46 = i32(1);
        v_23 = v_8 + v_46;
        v_7 = v_22;
        v_8 = v_23;
    }
    v_47 = _c_i64_0;
    v_48 = i64_ge(v_0, v_47);
    v_49 = _c_i64_1;
    v_50 = i64_le(v_0, v_49);
    v_9 = v_48 & v_50;
    v_51 = i64_to_i32(v_0);
    v_52 = i32(0);
    v_53 = v_24 >= v_52;
    v_54 = v_24 < v_51;
    v_10 = v_53 & v_54;
    v_55 = i32(0);
    v_56 = v_24 == v_55;
    v_57 = i32(0);
    v_58 = v_51 == v_57;
    v_11 = v_56 & v_58;
    v_12 = v_10 | v_11;
    let v_59 = &param2_f0[(i32(_scalar_params[3]) + v_24)];
    v_60 = f64_from_f32(f32(v_27));
    v_13 = f64_div(v_7, v_60);
    v_61 = f64_to_f32(v_13);
    v_14 = v_61 + v_28;
    v_15 = sqrt(v_14);
    v_16 = 1.0 / v_15;
    *v_59 = v_16;
    return;
}
