// Kernel: PadImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T02:17:07.8950000Z

// Kernel: PadImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: PadImpl_275
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

struct struct_10132 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Float32 (Element: Float32)
// -> Packed scalar at slot 0 (1 slots, type: f32)
// View offset for param2000 at scalar slot 1
// View offset for param3000 at scalar slot 2
// View offset for param4000 at scalar slot 3
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : i32 = 0;
    var v_5 : bool = false;
    var v_6 : i32 = 0;
    var v_7 : i32 = 0;
    var v_8 : bool = false;
    var v_9 : i32 = 0;
    var v_10 : bool = false;
    var v_11 : i32 = 0;
    var v_12 : bool = false;
    var v_13 : bool = false;
    var v_14 : i32 = 0;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : i32 = 0;
    var v_18 : bool = false;
    var v_19 : bool = false;
    var v_20 : i32 = 0;
    var v_21 : bool = false;
    var v_22 : i32 = 0;
    var v_23 : i32 = 0;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : bool = false;
    var v_29 : bool = false;
    var v_30 : bool = false;
    var v_31 : i32 = 0;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : bool = false;
    var v_35 : bool = false;
    var v_36 : bool = false;
    var v_37 : i32 = 0;
    var v_38 : i32 = 0;
    var v_39 : i32 = 0;
    var v_40 : bool = false;
    var v_41 : bool = false;
    var v_42 : bool = false;
    var v_43 : i32 = 0;
    var v_44 : i32 = 0;
    var v_45 : i32 = 0;
    var v_46 : bool = false;
    var v_47 : bool = false;
    var v_48 : bool = false;
    var v_49 : i32 = 0;
    var v_50 : i32 = 0;
    var v_51 : bool = false;
    var v_52 : bool = false;
    var v_53 : bool = false;
    var v_54 : bool = false;
    var v_55 : bool = false;
    var v_56 : bool = false;
    var v_57 : bool = false;
    var v_58 : bool = false;
    var v_59 : bool = false;
    var v_60 : bool = false;
    var v_61 : f32 = 0.0;
    var v_62 : f32 = 0.0;
    var v_63 : i32 = 0;
    var v_64 : i32 = 0;
    var v_65 : i32 = 0;
    var v_66 : i32 = 0;
    var v_67 : i32 = 0;
    var v_68 : i32 = 0;
    var v_69 : i32 = 0;
    var v_70 : i32 = 0;
    var v_71 : i32 = 0;
    var v_72 : i32 = 0;
    var v_73 : i32 = 0;
    var v_74 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_74) >= _ilgpu_user_dim) { return; }
    let v_75_f0 = &param1_f0;
    var v_75_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_76_f0 = &param2_f0;
    var v_76_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_77_f0 = &param3_f0;
    var v_77_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    var v_78 = bitcast<f32>(_scalar_params[0]);
    var v_83 : i32;
    var v_84 : emu_i64;
    var v_86 : emu_i64;
    var v_90 : i32;
    var v_93 : i32;
    var v_94 : emu_i64;
    var v_96 : emu_i64;
    var v_101 : emu_i64;
    var v_103 : emu_i64;
    var v_105 : i32;
    var v_106 : emu_i64;
    var v_108 : emu_i64;
    var v_110 : i32;
    var v_111 : emu_i64;
    var v_113 : emu_i64;
    var v_115 : i32;
    var v_116 : emu_i64;
    var v_118 : emu_i64;
    var v_120 : i32;
    var v_122 : i32;
    var v_123 : i32;
    var v_124 : i32;
    var v_127 : i32;
    var v_130 : i32;
    var v_131 : i32;
    var v_132 : i32;
    var v_135 : i32;
    var v_138 : i32;
    var v_139 : i32;
    var v_142 : i32;
    var v_145 : i32;
    var v_146 : i32;
    var v_147 : i32;
    var v_148 : i32;
    var v_151 : i32;
    var v_154 : i32;
    var v_156 : i32;
    var v_158 : i32;
    var v_160 : i32;
    var v_163 : i32;
    var v_164 : i32;
    var v_165 : i32;
    var v_167 : i32;
    var v_168 : i32;
    var v_169 : i32;
    var v_171 : emu_i64;
    var v_173 : emu_i64;
    var v_176 : i32;
    var v_179 : i32;
    var v_181 : i32;
    var v_184 : emu_i64;
    var v_186 : emu_i64;
    var v_189 : i32;
    var v_192 : i32;
    var v_194 : i32;
    var v_82 : emu_i64;
    var v_85 : bool;
    var v_87 : bool;
    var v_88 : i32;
    var v_89 : bool;
    var v_91 : bool;
    var v_95 : bool;
    var v_97 : bool;
    var v_98 : i32;
    var v_99 : bool;
    var v_102 : bool;
    var v_104 : bool;
    var v_107 : bool;
    var v_109 : bool;
    var v_112 : bool;
    var v_114 : bool;
    var v_117 : bool;
    var v_119 : bool;
    var v_121 : bool;
    var v_125 : bool;
    var v_126 : bool;
    var v_128 : bool;
    var v_133 : bool;
    var v_134 : bool;
    var v_136 : bool;
    var v_140 : bool;
    var v_141 : bool;
    var v_143 : bool;
    var v_149 : bool;
    var v_150 : bool;
    var v_152 : bool;
    var v_155 : bool;
    var v_157 : bool;
    var v_159 : bool;
    var v_161 : bool;
    var v_162 : bool;
    var v_166 : bool;
    var v_170 : bool;
    var v_172 : bool;
    var v_174 : bool;
    var v_175 : i32;
    var v_177 : bool;
    var v_178 : bool;
    var v_180 : bool;
    var v_182 : bool;
    var v_185 : bool;
    var v_187 : bool;
    var v_188 : i32;
    var v_190 : bool;
    var v_191 : bool;
    var v_193 : bool;
    var v_195 : bool;




















































    let v_79 = v_75_f0;
    let v_80 = v_76_f0;
    let v_81 = v_77_f0;

    v_0 = v_75_f1;

    v_1 = v_76_f1;

    v_82 = v_77_f1;
    v_83 = i32(0);
    v_84 = _c_i64_0;
    v_85 = i64_ge(v_82, v_84);
    v_86 = _c_i64_1;
    v_87 = i64_le(v_82, v_86);
    v_2 = v_85 & v_87;
    v_88 = i64_to_i32(v_82);
    v_89 = v_88 > v_83;
    v_90 = i32(0);
    v_91 = v_88 == v_90;
    v_3 = v_89 | v_91;
    let v_92 = &param3_f0[(i32(_scalar_params[3]) + v_83)];
    v_4 = *v_92;
    v_93 = i32(1);
    v_94 = _c_i64_0;
    v_95 = i64_ge(v_82, v_94);
    v_96 = _c_i64_1;
    v_97 = i64_le(v_82, v_96);
    v_5 = v_95 & v_97;
    v_98 = i64_to_i32(v_82);
    v_99 = v_98 > v_93;
    let v_100 = &param3_f0[(i32(_scalar_params[3]) + v_93)];
    v_6 = *v_100;
    v_7 = i32(0);
    v_8 = false;
    v_9 = i32(0);
    v_101 = _c_i64_0;
    v_102 = i64_ge(v_82, v_101);
    v_103 = _c_i64_1;
    v_104 = i64_le(v_82, v_103);
    v_10 = v_102 & v_104;
    v_11 = i64_to_i32(v_82);
    v_105 = i32(0);
    v_12 = v_11 == v_105;
    v_106 = _c_i64_0;
    v_107 = i64_ge(v_82, v_106);
    v_108 = _c_i64_1;
    v_109 = i64_le(v_82, v_108);
    v_13 = v_107 & v_109;
    v_14 = i64_to_i32(v_82);
    v_110 = i32(0);
    v_15 = v_14 == v_110;
    v_111 = _c_i64_0;
    v_112 = i64_ge(v_82, v_111);
    v_113 = _c_i64_1;
    v_114 = i64_le(v_82, v_113);
    v_16 = v_112 & v_114;
    v_17 = i64_to_i32(v_82);
    v_115 = i32(0);
    v_18 = v_17 == v_115;
    v_116 = _c_i64_0;
    v_117 = i64_ge(v_82, v_116);
    v_118 = _c_i64_1;
    v_119 = i64_le(v_82, v_118);
    v_19 = v_117 & v_119;
    v_20 = i64_to_i32(v_82);
    v_120 = i32(0);
    v_21 = v_20 == v_120;
    v_22 = v_9;
    v_23 = v_74;
    v_24 = v_7;
    loop {
        v_121 = v_22 < v_4;
        if (!v_121) {
            v_52 = v_8;
            break;
        }
        v_122 = i32(2);
        v_123 = i32(2);
        v_25 = v_4 << u32(v_123);
        v_26 = v_25 + v_122;
        v_27 = v_26 + v_22;
        v_124 = i32(0);
        v_125 = v_27 >= v_124;
        v_126 = v_27 < v_11;
        v_28 = v_125 & v_126;
        v_127 = i32(0);
        v_128 = v_27 == v_127;
        v_29 = v_128 & v_12;
        v_30 = v_28 | v_29;
        let v_129 = &param3_f0[(i32(_scalar_params[3]) + v_27)];
        v_130 = *v_129;
        v_31 = v_23 / v_130;
        v_32 = v_23 % v_130;
        v_131 = i32(2);
        v_33 = v_22 + v_131;
        v_132 = i32(0);
        v_133 = v_33 >= v_132;
        v_134 = v_33 < v_14;
        v_34 = v_133 & v_134;
        v_135 = i32(0);
        v_136 = v_33 == v_135;
        v_35 = v_136 & v_15;
        v_36 = v_34 | v_35;
        let v_137 = &param3_f0[(i32(_scalar_params[3]) + v_33)];
        v_37 = *v_137;
        v_138 = i32(2);
        v_38 = v_4 + v_138;
        v_39 = v_38 + v_22;
        v_139 = i32(0);
        v_140 = v_39 >= v_139;
        v_141 = v_39 < v_17;
        v_40 = v_140 & v_141;
        v_142 = i32(0);
        v_143 = v_39 == v_142;
        v_41 = v_143 & v_18;
        v_42 = v_40 | v_41;
        let v_144 = &param3_f0[(i32(_scalar_params[3]) + v_39)];
        v_145 = *v_144;
        v_146 = i32(2);
        v_147 = i32(3);
        v_43 = v_4 * v_147;
        v_44 = v_43 + v_146;
        v_45 = v_44 + v_22;
        v_148 = i32(0);
        v_149 = v_45 >= v_148;
        v_150 = v_45 < v_20;
        v_46 = v_149 & v_150;
        v_151 = i32(0);
        v_152 = v_45 == v_151;
        v_47 = v_152 & v_21;
        v_48 = v_46 | v_47;
        let v_153 = &param3_f0[(i32(_scalar_params[3]) + v_45)];
        v_49 = *v_153;
        v_50 = v_31 - v_145;
        v_154 = i32(0);
        v_155 = v_50 < v_154;
        if (v_155) {
            v_156 = i32(0);
            v_157 = v_6 != v_156;
            if (!v_157) {
                v_51 = true;
                v_52 = v_51;
                break;
            }
            v_158 = i32(1);
            v_159 = v_6 != v_158;
            if (v_159) {
                v_160 = i32(0);
                v_161 = v_50 >= v_160;
                v_65 = -v_50;
                v_66 = select(v_65, v_50, v_161);
                v_162 = v_66 < v_37;
                if (!v_162) {
                    v_163 = i32(1);
                    v_67 = v_37 - v_163;
                    v_164 = i32(1);
                    v_68 = v_67 << u32(v_164);
                    v_69 = v_68 - v_66;
                    v_70 = v_69;
                } else {
                    v_70 = v_66;
                }
            } else {
                v_165 = i32(0);
                v_166 = v_50 < v_165;
                v_167 = i32(0);
                v_168 = i32(1);
                v_63 = v_37 - v_168;
                v_64 = select(v_63, v_167, v_166);
                v_70 = v_64;
            }
            v_71 = v_70 * v_49;
            v_72 = v_24 + v_71;
            v_169 = i32(1);
            v_73 = v_22 + v_169;
            v_22 = v_73;
            v_23 = v_32;
            v_24 = v_72;
        } else {
            v_170 = v_50 < v_37;
            if (!v_170) {
                v_156 = i32(0);
                v_157 = v_6 != v_156;
                if (!v_157) {
                    v_51 = true;
                    v_52 = v_51;
                    break;
                }
                v_158 = i32(1);
                v_159 = v_6 != v_158;
                if (v_159) {
                    v_160 = i32(0);
                    v_161 = v_50 >= v_160;
                    v_65 = -v_50;
                    v_66 = select(v_65, v_50, v_161);
                    v_162 = v_66 < v_37;
                    if (!v_162) {
                        v_163 = i32(1);
                        v_67 = v_37 - v_163;
                        v_164 = i32(1);
                        v_68 = v_67 << u32(v_164);
                        v_69 = v_68 - v_66;
                        v_70 = v_69;
                    } else {
                        v_70 = v_66;
                    }
                } else {
                    v_165 = i32(0);
                    v_166 = v_50 < v_165;
                    v_167 = i32(0);
                    v_168 = i32(1);
                    v_63 = v_37 - v_168;
                    v_64 = select(v_63, v_167, v_166);
                    v_70 = v_64;
                }
            } else {
                v_70 = v_50;
            }
            v_71 = v_70 * v_49;
            v_72 = v_24 + v_71;
            v_169 = i32(1);
            v_73 = v_22 + v_169;
            v_22 = v_73;
            v_23 = v_32;
            v_24 = v_72;
        }
    }
    v_171 = _c_i64_0;
    v_172 = i64_ge(v_1, v_171);
    v_173 = _c_i64_1;
    v_174 = i64_le(v_1, v_173);
    v_53 = v_172 & v_174;
    v_175 = i64_to_i32(v_1);
    v_176 = i32(0);
    v_177 = v_74 >= v_176;
    v_178 = v_74 < v_175;
    v_54 = v_177 & v_178;
    v_179 = i32(0);
    v_180 = v_74 == v_179;
    v_181 = i32(0);
    v_182 = v_175 == v_181;
    v_55 = v_180 & v_182;
    v_56 = v_54 | v_55;
    let v_183 = &param2_f0[(i32(_scalar_params[2]) + v_74)];
    if (v_52) {
        v_62 = v_78;
    } else {
        v_184 = _c_i64_0;
        v_185 = i64_ge(v_0, v_184);
        v_186 = _c_i64_1;
        v_187 = i64_le(v_0, v_186);
        v_57 = v_185 & v_187;
        v_188 = i64_to_i32(v_0);
        v_189 = i32(0);
        v_190 = v_24 >= v_189;
        v_191 = v_24 < v_188;
        v_58 = v_190 & v_191;
        v_192 = i32(0);
        v_193 = v_24 == v_192;
        v_194 = i32(0);
        v_195 = v_188 == v_194;
        v_59 = v_193 & v_195;
        v_60 = v_58 | v_59;
        let v_196 = &param1_f0[(i32(_scalar_params[1]) + v_24)];
        v_61 = *v_196;
        v_62 = v_61;
    }
    param2_f0[(i32(_scalar_params[2]) + v_74)] = v_62;
    return;
}
