// Kernel: ScaleInPlaceImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 2
// Time: 2026-03-23T19:58:23.9290000Z

// Kernel: ScaleInPlaceImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: ScaleInPlaceImpl_415
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Float32 (Element: Float32)
// -> Packed scalar at slot 0 (1 slots, type: f32)
// View offset for param2000 at scalar slot 1
@group(0) @binding(1) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : bool = false;
    var v_1 : bool = false;
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : f32 = 0.0;
    var v_5 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_5) >= _ilgpu_user_dim) { return; }
    let v_6_f0 = &param1_f0;
    var v_6_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    var v_7 = bitcast<f32>(_scalar_params[0]);
    let v_8 = v_6_f0;
    let v_9 = v_6_f1;
    var v_10 : emu_i64;
    v_10 = _c_i64_0;
    let v_11 = i64_ge(v_9, v_10);
    var v_12 : emu_i64;
    v_12 = _c_i64_1;
    let v_13 = i64_le(v_9, v_12);
    v_0 = v_11 & v_13;
    let v_14 = i64_to_i32(v_9);
    var v_15 : i32;
    v_15 = i32(0);
    let v_16 = v_5 >= v_15;
    let v_17 = v_5 < v_14;
    v_1 = v_16 & v_17;
    var v_18 : i32;
    v_18 = i32(0);
    let v_19 = v_5 == v_18;
    var v_20 : i32;
    v_20 = i32(0);
    let v_21 = v_14 == v_20;
    v_2 = v_19 & v_21;
    v_3 = v_1 | v_2;
    let v_22 = &param1_f0[(i32(_scalar_params[1]) + v_5)];
    var v_23 : f32;
    v_23 = *v_22;
    v_4 = v_23 * v_7;
    *v_22 = v_4;
        return;
}
