// Kernel: WhereImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 5
// Time: 2026-03-24T02:18:01.2760000Z

// Kernel: WhereImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: WhereImpl_509
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(3) var<storage, read_write> param4_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
// View offset for param3000 at scalar slot 1
// View offset for param4000 at scalar slot 2
// View offset for param5000 at scalar slot 3
@group(0) @binding(4) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : bool = false;
    var v_5 : bool = false;
    var v_6 : bool = false;
    var v_7 : bool = false;
    var v_8 : bool = false;
    var v_9 : bool = false;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : bool = false;
    var v_13 : bool = false;
    var v_14 : f32 = 0.0;
    var v_15 : bool = false;
    var v_16 : bool = false;
    var v_17 : bool = false;
    var v_18 : bool = false;
    var v_19 : f32 = 0.0;
    var v_20 : f32 = 0.0;
    var v_21 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_21) >= _ilgpu_user_dim) { return; }
    let v_22_f0 = &param1_f0;
    var v_22_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_23_f0 = &param2_f0;
    var v_23_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_24_f0 = &param3_f0;
    var v_24_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    let v_25_f0 = &param4_f0;
    var v_25_f1 = i64_from_i32(i32(arrayLength(&param4_f0)));
    var v_32 : emu_i64;
    var v_34 : emu_i64;
    var v_37 : i32;
    var v_40 : i32;
    var v_42 : i32;
    var v_45 : emu_i64;
    var v_47 : emu_i64;
    var v_50 : i32;
    var v_53 : i32;
    var v_55 : i32;
    var v_58 : f32;
    var v_59 : f32;
    var v_61 : emu_i64;
    var v_63 : emu_i64;
    var v_66 : i32;
    var v_69 : i32;
    var v_71 : i32;
    var v_74 : emu_i64;
    var v_76 : emu_i64;
    var v_79 : i32;
    var v_82 : i32;
    var v_84 : i32;
    var v_27 : emu_i64;
    var v_31 : emu_i64;
    var v_33 : bool;
    var v_35 : bool;
    var v_36 : i32;
    var v_38 : bool;
    var v_39 : bool;
    var v_41 : bool;
    var v_43 : bool;
    var v_46 : bool;
    var v_48 : bool;
    var v_49 : i32;
    var v_51 : bool;
    var v_52 : bool;
    var v_54 : bool;
    var v_56 : bool;
    var v_60 : bool;
    var v_62 : bool;
    var v_64 : bool;
    var v_65 : i32;
    var v_67 : bool;
    var v_68 : bool;
    var v_70 : bool;
    var v_72 : bool;
    var v_75 : bool;
    var v_77 : bool;
    var v_78 : i32;
    var v_80 : bool;
    var v_81 : bool;
    var v_83 : bool;
    var v_85 : bool;































    let v_26 = v_22_f0;
    let v_28 = v_23_f0;
    let v_29 = v_24_f0;
    let v_30 = v_25_f0;

    v_27 = v_22_f1;

    v_0 = v_23_f1;

    v_1 = v_24_f1;

    v_31 = v_25_f1;
    v_32 = _c_i64_0;
    v_33 = i64_ge(v_31, v_32);
    v_34 = _c_i64_1;
    v_35 = i64_le(v_31, v_34);
    v_2 = v_33 & v_35;
    v_36 = i64_to_i32(v_31);
    v_37 = i32(0);
    v_38 = v_21 >= v_37;
    v_39 = v_21 < v_36;
    v_3 = v_38 & v_39;
    v_40 = i32(0);
    v_41 = v_21 == v_40;
    v_42 = i32(0);
    v_43 = v_36 == v_42;
    v_4 = v_41 & v_43;
    v_5 = v_3 | v_4;
    let v_44 = &param4_f0[(i32(_scalar_params[3]) + v_21)];
    v_45 = _c_i64_0;
    v_46 = i64_ge(v_27, v_45);
    v_47 = _c_i64_1;
    v_48 = i64_le(v_27, v_47);
    v_6 = v_46 & v_48;
    v_49 = i64_to_i32(v_27);
    v_50 = i32(0);
    v_51 = v_21 >= v_50;
    v_52 = v_21 < v_49;
    v_7 = v_51 & v_52;
    v_53 = i32(0);
    v_54 = v_21 == v_53;
    v_55 = i32(0);
    v_56 = v_49 == v_55;
    v_8 = v_54 & v_56;
    v_9 = v_7 | v_8;
    let v_57 = &param1_f0[(i32(_scalar_params[0]) + v_21)];
    v_58 = *v_57;
    v_59 = f32(0.0);
    v_60 = v_58 != v_59;
    if (v_60) {
        v_61 = _c_i64_0;
        v_62 = i64_ge(v_0, v_61);
        v_63 = _c_i64_1;
        v_64 = i64_le(v_0, v_63);
        v_15 = v_62 & v_64;
        v_65 = i64_to_i32(v_0);
        v_66 = i32(0);
        v_67 = v_21 >= v_66;
        v_68 = v_21 < v_65;
        v_16 = v_67 & v_68;
        v_69 = i32(0);
        v_70 = v_21 == v_69;
        v_71 = i32(0);
        v_72 = v_65 == v_71;
        v_17 = v_70 & v_72;
        v_18 = v_16 | v_17;
        let v_73 = &param2_f0[(i32(_scalar_params[1]) + v_21)];
        v_19 = *v_73;
        v_20 = v_19;
    } else {
        v_74 = _c_i64_0;
        v_75 = i64_ge(v_1, v_74);
        v_76 = _c_i64_1;
        v_77 = i64_le(v_1, v_76);
        v_10 = v_75 & v_77;
        v_78 = i64_to_i32(v_1);
        v_79 = i32(0);
        v_80 = v_21 >= v_79;
        v_81 = v_21 < v_78;
        v_11 = v_80 & v_81;
        v_82 = i32(0);
        v_83 = v_21 == v_82;
        v_84 = i32(0);
        v_85 = v_78 == v_84;
        v_12 = v_83 & v_85;
        v_13 = v_11 | v_12;
        let v_86 = &param3_f0[(i32(_scalar_params[2]) + v_21)];
        v_14 = *v_86;
        v_20 = v_14;
    }
    param4_f0[(i32(_scalar_params[3]) + v_21)] = v_20;
    return;
}
