// Kernel: SimpleBatchedMatMulImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T02:18:22.3070000Z

// Kernel: SimpleBatchedMatMulImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: SimpleBatchedMatMulImpl_574
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// Param 7: Int32 (Element: Int32)
// -> Packed scalar at slot 3 (1 slots, type: i32)
// View offset for param2000 at scalar slot 4
// View offset for param3000 at scalar slot 5
// View offset for param4000 at scalar slot 6
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : emu_i64 = emu_i64(0u, 0u);
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : i32 = 0;
    var v_6 : i32 = 0;
    var v_7 : i32 = 0;
    var v_8 : i32 = 0;
    var v_9 : i32 = 0;
    var v_10 : i32 = 0;
    var v_11 : i32 = 0;
    var v_12 : f32 = 0.0;
    var v_13 : i32 = 0;
    var v_14 : i32 = 0;
    var v_15 : i32 = 0;
    var v_16 : bool = false;
    var v_17 : i32 = 0;
    var v_18 : bool = false;
    var v_19 : bool = false;
    var v_20 : i32 = 0;
    var v_21 : bool = false;
    var v_22 : f32 = 0.0;
    var v_23 : i32 = 0;
    var v_24 : bool = false;
    var v_25 : bool = false;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : i32 = 0;
    var v_29 : bool = false;
    var v_30 : bool = false;
    var v_31 : bool = false;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : bool = false;
    var v_36 : bool = false;
    var v_37 : bool = false;
    var v_38 : f32 = 0.0;
    var v_39 : f32 = 0.0;
    var v_40 : i32 = 0;
    var v_41 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_41) >= _ilgpu_user_dim) { return; }
    let v_42_f0 = &param1_f0;
    var v_42_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_43_f0 = &param2_f0;
    var v_43_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_44_f0 = &param3_f0;
    var v_44_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    var v_45 = bitcast<i32>(_scalar_params[0]);
    var v_46 = bitcast<i32>(_scalar_params[1]);
    var v_47 = bitcast<i32>(_scalar_params[2]);
    var v_48 = bitcast<i32>(_scalar_params[3]);
    var v_54 : emu_i64;
    var v_56 : emu_i64;
    var v_58 : i32;
    var v_59 : emu_i64;
    var v_61 : emu_i64;
    var v_63 : i32;
    var v_65 : i32;
    var v_68 : i32;
    var v_71 : f32;
    var v_72 : i32;
    var v_75 : i32;
    var v_78 : f32;
    var v_79 : i32;
    var v_80 : emu_i64;
    var v_82 : emu_i64;
    var v_85 : i32;
    var v_88 : i32;
    var v_90 : i32;
    var v_52 : bool;
    var v_53 : bool;
    var v_55 : bool;
    var v_57 : bool;
    var v_60 : bool;
    var v_62 : bool;
    var v_64 : bool;
    var v_66 : bool;
    var v_67 : bool;
    var v_69 : bool;
    var v_73 : bool;
    var v_74 : bool;
    var v_76 : bool;
    var v_81 : bool;
    var v_83 : bool;
    var v_84 : i32;
    var v_86 : bool;
    var v_87 : bool;
    var v_89 : bool;
    var v_91 : bool;




















    let v_49 = v_42_f0;
    let v_50 = v_43_f0;
    let v_51 = v_44_f0;

    v_0 = v_42_f1;

    v_1 = v_43_f1;

    v_2 = v_44_f1;
    v_3 = v_46 * v_48;
    v_4 = v_41 / v_3;
    v_5 = v_41 % v_3;
    v_6 = v_5 % v_48;
    v_7 = v_5 / v_48;
    v_52 = v_4 >= v_45;
    if (v_52) {
    } else {
        v_53 = v_7 < v_46;
        if (v_53) {
            v_8 = v_4 * v_46;
            v_9 = v_8 * v_47;
            v_10 = v_4 * v_47;
            v_11 = v_10 * v_48;
            v_12 = f32(0.0);
            v_13 = i32(0);
            v_14 = v_7 * v_47;
            v_15 = v_9 + v_14;
            v_54 = _c_i64_0;
            v_55 = i64_ge(v_0, v_54);
            v_56 = _c_i64_1;
            v_57 = i64_le(v_0, v_56);
            v_16 = v_55 & v_57;
            v_17 = i64_to_i32(v_0);
            v_58 = i32(0);
            v_18 = v_17 == v_58;
            v_59 = _c_i64_0;
            v_60 = i64_ge(v_1, v_59);
            v_61 = _c_i64_1;
            v_62 = i64_le(v_1, v_61);
            v_19 = v_60 & v_62;
            v_20 = i64_to_i32(v_1);
            v_63 = i32(0);
            v_21 = v_20 == v_63;
            v_22 = v_12;
            v_23 = v_13;
            loop {
                v_64 = v_23 < v_47;
                if (!v_64) {
                    break;
                }
                v_28 = v_15 + v_23;
                v_65 = i32(0);
                v_66 = v_28 >= v_65;
                v_67 = v_28 < v_17;
                v_29 = v_66 & v_67;
                v_68 = i32(0);
                v_69 = v_28 == v_68;
                v_30 = v_69 & v_18;
                v_31 = v_29 | v_30;
                let v_70 = &param1_f0[(i32(_scalar_params[4]) + v_28)];
                v_71 = *v_70;
                v_32 = v_23 * v_48;
                v_33 = v_11 + v_32;
                v_34 = v_33 + v_6;
                v_72 = i32(0);
                v_73 = v_34 >= v_72;
                v_74 = v_34 < v_20;
                v_35 = v_73 & v_74;
                v_75 = i32(0);
                v_76 = v_34 == v_75;
                v_36 = v_76 & v_21;
                v_37 = v_35 | v_36;
                let v_77 = &param2_f0[(i32(_scalar_params[5]) + v_34)];
                v_78 = *v_77;
                v_38 = v_71 * v_78;
                v_39 = v_22 + v_38;
                v_79 = i32(1);
                v_40 = v_23 + v_79;
                v_22 = v_39;
                v_23 = v_40;
            }
            v_80 = _c_i64_0;
            v_81 = i64_ge(v_2, v_80);
            v_82 = _c_i64_1;
            v_83 = i64_le(v_2, v_82);
            v_24 = v_81 & v_83;
            v_84 = i64_to_i32(v_2);
            v_85 = i32(0);
            v_86 = v_41 >= v_85;
            v_87 = v_41 < v_84;
            v_25 = v_86 & v_87;
            v_88 = i32(0);
            v_89 = v_41 == v_88;
            v_90 = i32(0);
            v_91 = v_84 == v_90;
            v_26 = v_89 & v_91;
            v_27 = v_25 | v_26;
            let v_92 = &param3_f0[(i32(_scalar_params[6]) + v_41)];
            *v_92 = v_22;
        } else {
        }
    }
    return;
}
