// Kernel: SimpleMatMulImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T02:18:27.0200000Z

// Kernel: SimpleMatMulImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: SimpleMatMulImpl_577
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// View offset for param2000 at scalar slot 3
// View offset for param3000 at scalar slot 4
// View offset for param4000 at scalar slot 5
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : emu_i64 = emu_i64(0u, 0u);
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : f32 = 0.0;
    var v_6 : i32 = 0;
    var v_7 : i32 = 0;
    var v_8 : bool = false;
    var v_9 : i32 = 0;
    var v_10 : bool = false;
    var v_11 : bool = false;
    var v_12 : i32 = 0;
    var v_13 : bool = false;
    var v_14 : f32 = 0.0;
    var v_15 : i32 = 0;
    var v_16 : bool = false;
    var v_17 : bool = false;
    var v_18 : bool = false;
    var v_19 : bool = false;
    var v_20 : i32 = 0;
    var v_21 : bool = false;
    var v_22 : bool = false;
    var v_23 : bool = false;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : bool = false;
    var v_29 : f32 = 0.0;
    var v_30 : f32 = 0.0;
    var v_31 : i32 = 0;
    var v_32 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_32) >= _ilgpu_user_dim) { return; }
    let v_33_f0 = &param1_f0;
    var v_33_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_34_f0 = &param2_f0;
    var v_34_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_35_f0 = &param3_f0;
    var v_35_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    var v_36 = bitcast<i32>(_scalar_params[0]);
    var v_37 = bitcast<i32>(_scalar_params[1]);
    var v_38 = bitcast<i32>(_scalar_params[2]);
    var v_43 : emu_i64;
    var v_45 : emu_i64;
    var v_47 : i32;
    var v_48 : emu_i64;
    var v_50 : emu_i64;
    var v_52 : i32;
    var v_54 : i32;
    var v_57 : i32;
    var v_60 : f32;
    var v_61 : i32;
    var v_64 : i32;
    var v_67 : f32;
    var v_68 : i32;
    var v_69 : emu_i64;
    var v_71 : emu_i64;
    var v_74 : i32;
    var v_77 : i32;
    var v_79 : i32;
    var v_42 : bool;
    var v_44 : bool;
    var v_46 : bool;
    var v_49 : bool;
    var v_51 : bool;
    var v_53 : bool;
    var v_55 : bool;
    var v_56 : bool;
    var v_58 : bool;
    var v_62 : bool;
    var v_63 : bool;
    var v_65 : bool;
    var v_70 : bool;
    var v_72 : bool;
    var v_73 : i32;
    var v_75 : bool;
    var v_76 : bool;
    var v_78 : bool;
    var v_80 : bool;



















    let v_39 = v_33_f0;
    let v_40 = v_34_f0;
    let v_41 = v_35_f0;

    v_0 = v_33_f1;

    v_1 = v_34_f1;

    v_2 = v_35_f1;
    v_3 = v_32 % v_38;
    v_4 = v_32 / v_38;
    v_42 = v_4 < v_36;
    if (v_42) {
        v_5 = f32(0.0);
        v_6 = i32(0);
        v_7 = v_4 * v_37;
        v_43 = _c_i64_0;
        v_44 = i64_ge(v_0, v_43);
        v_45 = _c_i64_1;
        v_46 = i64_le(v_0, v_45);
        v_8 = v_44 & v_46;
        v_9 = i64_to_i32(v_0);
        v_47 = i32(0);
        v_10 = v_9 == v_47;
        v_48 = _c_i64_0;
        v_49 = i64_ge(v_1, v_48);
        v_50 = _c_i64_1;
        v_51 = i64_le(v_1, v_50);
        v_11 = v_49 & v_51;
        v_12 = i64_to_i32(v_1);
        v_52 = i32(0);
        v_13 = v_12 == v_52;
        v_14 = v_5;
        v_15 = v_6;
        loop {
            v_53 = v_15 < v_37;
            if (!v_53) {
                break;
            }
            v_20 = v_7 + v_15;
            v_54 = i32(0);
            v_55 = v_20 >= v_54;
            v_56 = v_20 < v_9;
            v_21 = v_55 & v_56;
            v_57 = i32(0);
            v_58 = v_20 == v_57;
            v_22 = v_58 & v_10;
            v_23 = v_21 | v_22;
            let v_59 = &param1_f0[(i32(_scalar_params[3]) + v_20)];
            v_60 = *v_59;
            v_24 = v_15 * v_38;
            v_25 = v_24 + v_3;
            v_61 = i32(0);
            v_62 = v_25 >= v_61;
            v_63 = v_25 < v_12;
            v_26 = v_62 & v_63;
            v_64 = i32(0);
            v_65 = v_25 == v_64;
            v_27 = v_65 & v_13;
            v_28 = v_26 | v_27;
            let v_66 = &param2_f0[(i32(_scalar_params[4]) + v_25)];
            v_67 = *v_66;
            v_29 = v_60 * v_67;
            v_30 = v_14 + v_29;
            v_68 = i32(1);
            v_31 = v_15 + v_68;
            v_14 = v_30;
            v_15 = v_31;
        }
        v_69 = _c_i64_0;
        v_70 = i64_ge(v_2, v_69);
        v_71 = _c_i64_1;
        v_72 = i64_le(v_2, v_71);
        v_16 = v_70 & v_72;
        v_73 = i64_to_i32(v_2);
        v_74 = i32(0);
        v_75 = v_32 >= v_74;
        v_76 = v_32 < v_73;
        v_17 = v_75 & v_76;
        v_77 = i32(0);
        v_78 = v_32 == v_77;
        v_79 = i32(0);
        v_80 = v_73 == v_79;
        v_18 = v_78 & v_80;
        v_19 = v_17 | v_18;
        let v_81 = &param3_f0[(i32(_scalar_params[5]) + v_32)];
        *v_81 = v_14;
    } else {
    }
    return;
}
