// Kernel: ErfImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 3
// Time: 2026-03-23T19:59:00.8560000Z

// Kernel: ErfImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: ErfImpl_751
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
// View offset for param3000 at scalar slot 1
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : bool = false;
    var v_1 : bool = false;
    var v_2 : bool = false;
    var v_3 : bool = false;
    var v_4 : f32 = 0.0;
    var v_5 : f32 = 0.0;
    var v_6 : f32 = 0.0;
    var v_7 : f32 = 0.0;
    var v_8 : f32 = 0.0;
    var v_9 : f32 = 0.0;
    var v_10 : f32 = 0.0;
    var v_11 : f32 = 0.0;
    var v_12 : f32 = 0.0;
    var v_13 : f32 = 0.0;
    var v_14 : f32 = 0.0;
    var v_15 : f32 = 0.0;
    var v_16 : f32 = 0.0;
    var v_17 : f32 = 0.0;
    var v_18 : f32 = 0.0;
    var v_19 : f32 = 0.0;
    var v_20 : f32 = 0.0;
    var v_21 : f32 = 0.0;
    var v_22 : f32 = 0.0;
    var v_23 : f32 = 0.0;
    var v_24 : f32 = 0.0;
    var v_25 : f32 = 0.0;
    var v_26 : bool = false;
    var v_27 : bool = false;
    var v_28 : bool = false;
    var v_29 : bool = false;
    var v_30 : f32 = 0.0;
    var v_31 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_31) >= _ilgpu_user_dim) { return; }
    let v_32_f0 = &param1_f0;
    var v_32_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_33_f0 = &param2_f0;
    var v_33_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_34 = v_32_f0;
    let v_35 = v_32_f1;
    let v_36 = v_33_f0;
    let v_37 = v_33_f1;
    var v_38 : emu_i64;
    v_38 = _c_i64_0;
    let v_39 = i64_ge(v_35, v_38);
    var v_40 : emu_i64;
    v_40 = _c_i64_1;
    let v_41 = i64_le(v_35, v_40);
    v_0 = v_39 & v_41;
    let v_42 = i64_to_i32(v_35);
    var v_43 : i32;
    v_43 = i32(0);
    let v_44 = v_31 >= v_43;
    let v_45 = v_31 < v_42;
    v_1 = v_44 & v_45;
    var v_46 : i32;
    v_46 = i32(0);
    let v_47 = v_31 == v_46;
    var v_48 : i32;
    v_48 = i32(0);
    let v_49 = v_42 == v_48;
    v_2 = v_47 & v_49;
    v_3 = v_1 | v_2;
    let v_50 = &param1_f0[(i32(_scalar_params[0]) + v_31)];
    var v_51 : f32;
    v_51 = *v_50;
    var v_52 : f32;
    v_52 = f32(0.0);
    let v_53 = v_51 < v_52;
    v_4 = -v_51;
    var v_54 : f32;
    v_54 = select(v_51, v_4, v_53);
    var v_55 : f32;
    v_55 = f32(1.0);
    var v_56 : f32;
    v_56 = f32(0.327591091);
    v_5 = v_54 * v_56;
    v_6 = v_5 + v_55;
    v_7 = 1.0 / v_6;
    v_8 = v_7 * v_7;
    v_9 = v_8 * v_7;
    v_10 = v_9 * v_7;
    v_11 = v_10 * v_7;
    var v_57 : f32;
    v_57 = f32(1.0);
    var v_58 : f32;
    v_58 = f32(0.254829586);
    v_12 = v_7 * v_58;
    var v_59 : f32;
    v_59 = f32(-0.284496725);
    v_13 = v_8 * v_59;
    v_14 = v_12 + v_13;
    var v_60 : f32;
    v_60 = f32(1.42141378);
    v_15 = v_9 * v_60;
    v_16 = v_14 + v_15;
    var v_61 : f32;
    v_61 = f32(-1.45315206);
    v_17 = v_10 * v_61;
    v_18 = v_16 + v_17;
    var v_62 : f32;
    v_62 = f32(1.06140542);
    v_19 = v_11 * v_62;
    v_20 = v_18 + v_19;
    v_21 = -v_54;
    v_22 = v_21 * v_54;
    v_23 = exp(v_22);
    v_24 = v_20 * v_23;
    v_25 = v_57 - v_24;
    var v_63 : emu_i64;
    v_63 = _c_i64_0;
    let v_64 = i64_ge(v_37, v_63);
    var v_65 : emu_i64;
    v_65 = _c_i64_1;
    let v_66 = i64_le(v_37, v_65);
    v_26 = v_64 & v_66;
    let v_67 = i64_to_i32(v_37);
    var v_68 : i32;
    v_68 = i32(0);
    let v_69 = v_31 >= v_68;
    let v_70 = v_31 < v_67;
    v_27 = v_69 & v_70;
    var v_71 : i32;
    v_71 = i32(0);
    let v_72 = v_31 == v_71;
    var v_73 : i32;
    v_73 = i32(0);
    let v_74 = v_67 == v_73;
    v_28 = v_72 & v_74;
    v_29 = v_27 | v_28;
    let v_75 = &param2_f0[(i32(_scalar_params[1]) + v_31)];
    var v_76 : f32;
    v_76 = f32(0.0);
    let v_77 = v_51 < v_76;
    v_30 = -v_25;
    var v_78 : f32;
    v_78 = select(v_25, v_30, v_77);
    *v_75 = v_78;
        return;
}
