// Kernel: PreprocessImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T02:18:36.4160000Z

// Kernel: PreprocessImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: PreprocessImpl_695
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_10132 {
    field_0 : i32,
    field_1 : emu_i64,
    field_2 : i32,
};

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Int32, Generic> [0], Int64 [8], Int8 [16]> (Element: Int32)
// Body struct field 0: View<Int32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<i32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(2) var<storage, read_write> param3_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// View offset for param2000 at scalar slot 0
// View offset for param3000 at scalar slot 1
// View offset for param4000 at scalar slot 2
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : emu_i64 = emu_i64(0u, 0u);
    var v_3 : bool = false;
    var v_4 : bool = false;
    var v_5 : i32 = 0;
    var v_6 : bool = false;
    var v_7 : i32 = 0;
    var v_8 : bool = false;
    var v_9 : bool = false;
    var v_10 : i32 = 0;
    var v_11 : i32 = 0;
    var v_12 : i32 = 0;
    var v_13 : i32 = 0;
    var v_14 : i32 = 0;
    var v_15 : f32 = 0.0;
    var v_16 : f32 = 0.0;
    var v_17 : f32 = 0.0;
    var v_18 : f32 = 0.0;
    var v_19 : f32 = 0.0;
    var v_20 : f32 = 0.0;
    var v_21 : f32 = 0.0;
    var v_22 : f32 = 0.0;
    var v_23 : i32 = 0;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : f32 = 0.0;
    var v_28 : f32 = 0.0;
    var v_29 : i32 = 0;
    var v_30 : i32 = 0;
    var v_31 : i32 = 0;
    var v_32 : i32 = 0;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : i32 = 0;
    var v_36 : bool = false;
    var v_37 : bool = false;
    var v_38 : bool = false;
    var v_39 : bool = false;
    var v_40 : i32 = 0;
    var v_41 : i32 = 0;
    var v_42 : i32 = 0;
    var v_43 : f32 = 0.0;
    var v_44 : i32 = 0;
    var v_45 : i32 = 0;
    var v_46 : bool = false;
    var v_47 : bool = false;
    var v_48 : bool = false;
    var v_49 : bool = false;
    var v_50 : i32 = 0;
    var v_51 : i32 = 0;
    var v_52 : i32 = 0;
    var v_53 : f32 = 0.0;
    var v_54 : i32 = 0;
    var v_55 : i32 = 0;
    var v_56 : bool = false;
    var v_57 : bool = false;
    var v_58 : bool = false;
    var v_59 : bool = false;
    var v_60 : i32 = 0;
    var v_61 : i32 = 0;
    var v_62 : i32 = 0;
    var v_63 : f32 = 0.0;
    var v_64 : i32 = 0;
    var v_65 : i32 = 0;
    var v_66 : bool = false;
    var v_67 : bool = false;
    var v_68 : bool = false;
    var v_69 : bool = false;
    var v_70 : i32 = 0;
    var v_71 : i32 = 0;
    var v_72 : i32 = 0;
    var v_73 : f32 = 0.0;
    var v_74 : f32 = 0.0;
    var v_75 : f32 = 0.0;
    var v_76 : f32 = 0.0;
    var v_77 : f32 = 0.0;
    var v_78 : f32 = 0.0;
    var v_79 : f32 = 0.0;
    var v_80 : f32 = 0.0;
    var v_81 : f32 = 0.0;
    var v_82 : f32 = 0.0;
    var v_83 : f32 = 0.0;
    var v_84 : f32 = 0.0;
    var v_85 : f32 = 0.0;
    var v_86 : f32 = 0.0;
    var v_87 : f32 = 0.0;
    var v_88 : f32 = 0.0;
    var v_89 : i32 = 0;
    var v_90 : bool = false;
    var v_91 : bool = false;
    var v_92 : bool = false;
    var v_93 : bool = false;
    var v_94 : i32 = 0;
    var v_95 : bool = false;
    var v_96 : bool = false;
    var v_97 : bool = false;
    var v_98 : bool = false;
    var v_99 : bool = false;
    var v_100 : bool = false;
    var v_101 : bool = false;
    var v_102 : bool = false;
    var v_103 : f32 = 0.0;
    var v_104 : f32 = 0.0;
    var v_105 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_105) >= _ilgpu_user_dim) { return; }
    let v_106_f0 = &param1_f0;
    var v_106_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_107_f0 = &param2_f0;
    var v_107_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    let v_108_f0 = &param3_f0;
    var v_108_f1 = i64_from_i32(i32(arrayLength(&param3_f0)));
    var v_112 : i32;
    var v_113 : emu_i64;
    var v_115 : emu_i64;
    var v_119 : i32;
    var v_122 : f32;
    var v_123 : i32;
    var v_124 : emu_i64;
    var v_126 : emu_i64;
    var v_131 : f32;
    var v_132 : i32;
    var v_133 : emu_i64;
    var v_135 : emu_i64;
    var v_140 : f32;
    var v_142 : i32;
    var v_143 : emu_i64;
    var v_145 : emu_i64;
    var v_150 : f32;
    var v_153 : f32;
    var v_156 : f32;
    var v_158 : f32;
    var v_161 : f32;
    var v_162 : i32;
    var v_163 : i32;
    var v_166 : i32;
    var v_169 : i32;
    var v_170 : i32;
    var v_171 : i32;
    var v_173 : i32;
    var v_174 : i32;
    var v_176 : i32;
    var v_177 : i32;
    var v_178 : i32;
    var v_179 : emu_i64;
    var v_181 : emu_i64;
    var v_184 : i32;
    var v_187 : i32;
    var v_189 : i32;
    var v_192 : i32;
    var v_193 : i32;
    var v_194 : i32;
    var v_196 : f32;
    var v_197 : emu_i64;
    var v_199 : emu_i64;
    var v_202 : i32;
    var v_205 : i32;
    var v_207 : i32;
    var v_210 : i32;
    var v_211 : i32;
    var v_212 : i32;
    var v_214 : f32;
    var v_215 : emu_i64;
    var v_217 : emu_i64;
    var v_220 : i32;
    var v_223 : i32;
    var v_225 : i32;
    var v_228 : i32;
    var v_229 : i32;
    var v_230 : i32;
    var v_232 : f32;
    var v_233 : emu_i64;
    var v_235 : emu_i64;
    var v_238 : i32;
    var v_241 : i32;
    var v_243 : i32;
    var v_246 : i32;
    var v_247 : i32;
    var v_248 : i32;
    var v_250 : f32;
    var v_251 : f32;
    var v_252 : f32;
    var v_253 : f32;
    var v_254 : f32;
    var v_255 : i32;
    var v_256 : emu_i64;
    var v_258 : emu_i64;
    var v_261 : i32;
    var v_264 : i32;
    var v_266 : i32;
    var v_269 : f32;
    var v_270 : i32;
    var v_271 : emu_i64;
    var v_273 : emu_i64;
    var v_276 : i32;
    var v_279 : i32;
    var v_281 : i32;
    var v_284 : f32;
    var v_285 : emu_i64;
    var v_287 : emu_i64;
    var v_290 : i32;
    var v_293 : i32;
    var v_295 : i32;
    var v_114 : bool;
    var v_116 : bool;
    var v_117 : i32;
    var v_118 : bool;
    var v_120 : bool;
    var v_125 : bool;
    var v_127 : bool;
    var v_128 : i32;
    var v_129 : bool;
    var v_134 : bool;
    var v_136 : bool;
    var v_137 : i32;
    var v_138 : bool;
    var v_141 : i32;
    var v_144 : bool;
    var v_146 : bool;
    var v_147 : i32;
    var v_148 : bool;
    var v_151 : i32;
    var v_152 : f32;
    var v_154 : f32;
    var v_155 : f32;
    var v_157 : f32;
    var v_159 : f32;
    var v_160 : f32;
    var v_164 : f32;
    var v_165 : f32;
    var v_167 : bool;
    var v_168 : bool;
    var v_172 : bool;
    var v_175 : bool;
    var v_180 : bool;
    var v_182 : bool;
    var v_183 : i32;
    var v_185 : bool;
    var v_186 : bool;
    var v_188 : bool;
    var v_190 : bool;
    var v_195 : f32;
    var v_198 : bool;
    var v_200 : bool;
    var v_201 : i32;
    var v_203 : bool;
    var v_204 : bool;
    var v_206 : bool;
    var v_208 : bool;
    var v_213 : f32;
    var v_216 : bool;
    var v_218 : bool;
    var v_219 : i32;
    var v_221 : bool;
    var v_222 : bool;
    var v_224 : bool;
    var v_226 : bool;
    var v_231 : f32;
    var v_234 : bool;
    var v_236 : bool;
    var v_237 : i32;
    var v_239 : bool;
    var v_240 : bool;
    var v_242 : bool;
    var v_244 : bool;
    var v_249 : f32;
    var v_257 : bool;
    var v_259 : bool;
    var v_260 : i32;
    var v_262 : bool;
    var v_263 : bool;
    var v_265 : bool;
    var v_267 : bool;
    var v_272 : bool;
    var v_274 : bool;
    var v_275 : i32;
    var v_277 : bool;
    var v_278 : bool;
    var v_280 : bool;
    var v_282 : bool;
    var v_286 : bool;
    var v_288 : bool;
    var v_289 : i32;
    var v_291 : bool;
    var v_292 : bool;
    var v_294 : bool;
    var v_296 : bool;




















































































    let v_109 = v_106_f0;
    let v_110 = v_107_f0;
    let v_111 = v_108_f0;

    v_0 = v_106_f1;

    v_1 = v_107_f1;

    v_2 = v_108_f1;
    v_112 = i32(0);
    v_113 = _c_i64_0;
    v_114 = i64_ge(v_2, v_113);
    v_115 = _c_i64_1;
    v_116 = i64_le(v_2, v_115);
    v_3 = v_114 & v_116;
    v_117 = i64_to_i32(v_2);
    v_118 = v_117 > v_112;
    v_119 = i32(0);
    v_120 = v_117 == v_119;
    v_4 = v_118 | v_120;
    let v_121 = &param3_f0[(i32(_scalar_params[2]) + v_112)];
    v_122 = *v_121;
    v_5 = i32(v_122);
    v_123 = i32(1);
    v_124 = _c_i64_0;
    v_125 = i64_ge(v_2, v_124);
    v_126 = _c_i64_1;
    v_127 = i64_le(v_2, v_126);
    v_6 = v_125 & v_127;
    v_128 = i64_to_i32(v_2);
    v_129 = v_128 > v_123;
    let v_130 = &param3_f0[(i32(_scalar_params[2]) + v_123)];
    v_131 = *v_130;
    v_7 = i32(v_131);
    v_132 = i32(2);
    v_133 = _c_i64_0;
    v_134 = i64_ge(v_2, v_133);
    v_135 = _c_i64_1;
    v_136 = i64_le(v_2, v_135);
    v_8 = v_134 & v_136;
    v_137 = i64_to_i32(v_2);
    v_138 = v_137 > v_132;
    let v_139 = &param3_f0[(i32(_scalar_params[2]) + v_132)];
    v_140 = *v_139;
    v_141 = i32(v_140);
    v_142 = i32(3);
    v_143 = _c_i64_0;
    v_144 = i64_ge(v_2, v_143);
    v_145 = _c_i64_1;
    v_146 = i64_le(v_2, v_145);
    v_9 = v_144 & v_146;
    v_147 = i64_to_i32(v_2);
    v_148 = v_147 > v_142;
    let v_149 = &param3_f0[(i32(_scalar_params[2]) + v_142)];
    v_150 = *v_149;
    v_151 = i32(v_150);
    v_10 = v_151 * v_141;
    v_11 = v_105 / v_10;
    v_12 = v_105 % v_10;
    v_13 = v_12 / v_141;
    v_14 = v_12 % v_141;
    v_152 = f32(v_13);
    v_153 = f32(0.5);
    v_15 = v_152 + v_153;
    v_154 = f32(v_7);
    v_16 = v_15 * v_154;
    v_155 = f32(v_151);
    v_17 = v_16 / v_155;
    v_156 = f32(0.5);
    v_18 = v_17 - v_156;
    v_157 = f32(v_14);
    v_158 = f32(0.5);
    v_19 = v_157 + v_158;
    v_159 = f32(v_5);
    v_20 = v_19 * v_159;
    v_160 = f32(v_141);
    v_21 = v_20 / v_160;
    v_161 = f32(0.5);
    v_22 = v_21 - v_161;
    v_23 = i32(v_18);
    v_162 = i32(1);
    v_24 = v_23 + v_162;
    v_25 = i32(v_22);
    v_163 = i32(1);
    v_26 = v_25 + v_163;
    v_164 = f32(v_23);
    v_27 = v_18 - v_164;
    v_165 = f32(v_25);
    v_28 = v_22 - v_165;
    v_166 = i32(0);
    v_167 = v_23 >= v_166;
    if (!v_167) {
        v_29 = i32(0);
        v_30 = v_29;
    } else {
        v_30 = v_23;
    }
    v_168 = v_24 < v_7;
    v_169 = i32(1);
    v_31 = v_7 - v_169;
    v_170 = select(v_31, v_24, v_168);
    v_171 = i32(0);
    v_172 = v_25 >= v_171;
    v_173 = i32(0);
    v_174 = select(v_173, v_25, v_172);
    v_175 = v_26 < v_5;
    v_176 = i32(1);
    v_32 = v_5 - v_176;
    v_177 = select(v_32, v_26, v_175);
    v_178 = i32(3);
    v_33 = v_11 << u32(v_178);
    v_34 = v_30 * v_5;
    v_35 = v_34 + v_174;
    v_179 = _c_i64_0;
    v_180 = i64_ge(v_0, v_179);
    v_181 = _c_i64_1;
    v_182 = i64_le(v_0, v_181);
    v_36 = v_180 & v_182;
    v_183 = i64_to_i32(v_0);
    v_184 = i32(0);
    v_185 = v_35 >= v_184;
    v_186 = v_35 < v_183;
    v_37 = v_185 & v_186;
    v_187 = i32(0);
    v_188 = v_35 == v_187;
    v_189 = i32(0);
    v_190 = v_183 == v_189;
    v_38 = v_188 & v_190;
    v_39 = v_37 | v_38;
    let v_191 = &param1_f0[(i32(_scalar_params[0]) + v_35)];
    v_192 = *v_191;
    v_193 = i32(31);
    v_40 = v_33 & v_193;
    v_41 = v_192 >> u32(v_40);
    v_194 = i32(255);
    v_42 = v_41 & v_194;
    v_195 = f32(v_42);
    v_196 = f32(255.0);
    v_43 = v_195 / v_196;
    v_44 = v_30 * v_5;
    v_45 = v_44 + v_177;
    v_197 = _c_i64_0;
    v_198 = i64_ge(v_0, v_197);
    v_199 = _c_i64_1;
    v_200 = i64_le(v_0, v_199);
    v_46 = v_198 & v_200;
    v_201 = i64_to_i32(v_0);
    v_202 = i32(0);
    v_203 = v_45 >= v_202;
    v_204 = v_45 < v_201;
    v_47 = v_203 & v_204;
    v_205 = i32(0);
    v_206 = v_45 == v_205;
    v_207 = i32(0);
    v_208 = v_201 == v_207;
    v_48 = v_206 & v_208;
    v_49 = v_47 | v_48;
    let v_209 = &param1_f0[(i32(_scalar_params[0]) + v_45)];
    v_210 = *v_209;
    v_211 = i32(31);
    v_50 = v_33 & v_211;
    v_51 = v_210 >> u32(v_50);
    v_212 = i32(255);
    v_52 = v_51 & v_212;
    v_213 = f32(v_52);
    v_214 = f32(255.0);
    v_53 = v_213 / v_214;
    v_54 = v_170 * v_5;
    v_55 = v_54 + v_174;
    v_215 = _c_i64_0;
    v_216 = i64_ge(v_0, v_215);
    v_217 = _c_i64_1;
    v_218 = i64_le(v_0, v_217);
    v_56 = v_216 & v_218;
    v_219 = i64_to_i32(v_0);
    v_220 = i32(0);
    v_221 = v_55 >= v_220;
    v_222 = v_55 < v_219;
    v_57 = v_221 & v_222;
    v_223 = i32(0);
    v_224 = v_55 == v_223;
    v_225 = i32(0);
    v_226 = v_219 == v_225;
    v_58 = v_224 & v_226;
    v_59 = v_57 | v_58;
    let v_227 = &param1_f0[(i32(_scalar_params[0]) + v_55)];
    v_228 = *v_227;
    v_229 = i32(31);
    v_60 = v_33 & v_229;
    v_61 = v_228 >> u32(v_60);
    v_230 = i32(255);
    v_62 = v_61 & v_230;
    v_231 = f32(v_62);
    v_232 = f32(255.0);
    v_63 = v_231 / v_232;
    v_64 = v_170 * v_5;
    v_65 = v_64 + v_177;
    v_233 = _c_i64_0;
    v_234 = i64_ge(v_0, v_233);
    v_235 = _c_i64_1;
    v_236 = i64_le(v_0, v_235);
    v_66 = v_234 & v_236;
    v_237 = i64_to_i32(v_0);
    v_238 = i32(0);
    v_239 = v_65 >= v_238;
    v_240 = v_65 < v_237;
    v_67 = v_239 & v_240;
    v_241 = i32(0);
    v_242 = v_65 == v_241;
    v_243 = i32(0);
    v_244 = v_237 == v_243;
    v_68 = v_242 & v_244;
    v_69 = v_67 | v_68;
    let v_245 = &param1_f0[(i32(_scalar_params[0]) + v_65)];
    v_246 = *v_245;
    v_247 = i32(31);
    v_70 = v_33 & v_247;
    v_71 = v_246 >> u32(v_70);
    v_248 = i32(255);
    v_72 = v_71 & v_248;
    v_249 = f32(v_72);
    v_250 = f32(255.0);
    v_73 = v_249 / v_250;
    v_251 = f32(1.0);
    v_74 = v_251 - v_27;
    v_75 = v_43 * v_74;
    v_252 = f32(1.0);
    v_76 = v_252 - v_28;
    v_77 = v_75 * v_76;
    v_253 = f32(1.0);
    v_78 = v_253 - v_27;
    v_79 = v_53 * v_78;
    v_80 = v_79 * v_28;
    v_81 = v_77 + v_80;
    v_82 = v_63 * v_27;
    v_254 = f32(1.0);
    v_83 = v_254 - v_28;
    v_84 = v_82 * v_83;
    v_85 = v_81 + v_84;
    v_86 = v_73 * v_27;
    v_87 = v_86 * v_28;
    v_88 = v_85 + v_87;
    v_255 = i32(4);
    v_89 = v_11 + v_255;
    v_256 = _c_i64_0;
    v_257 = i64_ge(v_2, v_256);
    v_258 = _c_i64_1;
    v_259 = i64_le(v_2, v_258);
    v_90 = v_257 & v_259;
    v_260 = i64_to_i32(v_2);
    v_261 = i32(0);
    v_262 = v_89 >= v_261;
    v_263 = v_89 < v_260;
    v_91 = v_262 & v_263;
    v_264 = i32(0);
    v_265 = v_89 == v_264;
    v_266 = i32(0);
    v_267 = v_260 == v_266;
    v_92 = v_265 & v_267;
    v_93 = v_91 | v_92;
    let v_268 = &param3_f0[(i32(_scalar_params[2]) + v_89)];
    v_269 = *v_268;
    v_270 = i32(7);
    v_94 = v_11 + v_270;
    v_271 = _c_i64_0;
    v_272 = i64_ge(v_2, v_271);
    v_273 = _c_i64_1;
    v_274 = i64_le(v_2, v_273);
    v_95 = v_272 & v_274;
    v_275 = i64_to_i32(v_2);
    v_276 = i32(0);
    v_277 = v_94 >= v_276;
    v_278 = v_94 < v_275;
    v_96 = v_277 & v_278;
    v_279 = i32(0);
    v_280 = v_94 == v_279;
    v_281 = i32(0);
    v_282 = v_275 == v_281;
    v_97 = v_280 & v_282;
    v_98 = v_96 | v_97;
    let v_283 = &param3_f0[(i32(_scalar_params[2]) + v_94)];
    v_284 = *v_283;
    v_285 = _c_i64_0;
    v_286 = i64_ge(v_1, v_285);
    v_287 = _c_i64_1;
    v_288 = i64_le(v_1, v_287);
    v_99 = v_286 & v_288;
    v_289 = i64_to_i32(v_1);
    v_290 = i32(0);
    v_291 = v_105 >= v_290;
    v_292 = v_105 < v_289;
    v_100 = v_291 & v_292;
    v_293 = i32(0);
    v_294 = v_105 == v_293;
    v_295 = i32(0);
    v_296 = v_289 == v_295;
    v_101 = v_294 & v_296;
    v_102 = v_100 | v_101;
    let v_297 = &param2_f0[(i32(_scalar_params[1]) + v_105)];
    v_103 = v_88 - v_269;
    v_104 = v_103 * v_284;
    *v_297 = v_104;
    return;
}
