// Kernel: BilinearUpsampleImpl
// Workgroup: 64
// SharedMem: 0B
// Bindings: 3
// Time: 2026-03-23T19:59:03.0340000Z

// Kernel: BilinearUpsampleImpl
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: BilinearUpsampleImpl_829
// WorkgroupSize: 64
// Emulation: i64


// ============ 64-bit Emulation Library ============
alias emu_i64 = vec2<u32>;
alias emu_u64 = vec2<u32>;
// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}


// ============ Hoisted i64 Constants ============
const _c_i64_0 : vec2<u32> = vec2<u32>(2147483648u, 4294967295u);
const _c_i64_1 : vec2<u32> = vec2<u32>(2147483647u, 0u);

override _ilgpu_user_dim : u32 = 4294967295u;

struct struct_42 {
    field_0 : f32,
    field_1 : emu_i64,
    field_2 : i32,
};

// Param 1: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(0) var<storage, read_write> param1_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 2: Struct<View<Float32, Generic> [0], Int64 [8], Int8 [16]> (Element: Float32)
// Body struct field 0: View<Float32, Generic> (view)
@group(0) @binding(1) var<storage, read_write> param2_f0 : array<f32>;
// Body struct field 1: Int64 (view metadata, length)
// Body struct field 2: Int8 (view metadata, flag)
// Param 3: Int32 (Element: Int32)
// -> Packed scalar at slot 0 (1 slots, type: i32)
// Param 4: Int32 (Element: Int32)
// -> Packed scalar at slot 1 (1 slots, type: i32)
// Param 5: Int32 (Element: Int32)
// -> Packed scalar at slot 2 (1 slots, type: i32)
// Param 6: Int32 (Element: Int32)
// -> Packed scalar at slot 3 (1 slots, type: i32)
// Param 7: Int32 (Element: Int32)
// -> Packed scalar at slot 4 (1 slots, type: i32)
// View offset for param2000 at scalar slot 5
// View offset for param3000 at scalar slot 6
@group(0) @binding(2) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : emu_i64 = emu_i64(0u, 0u);
    var v_1 : emu_i64 = emu_i64(0u, 0u);
    var v_2 : i32 = 0;
    var v_3 : i32 = 0;
    var v_4 : i32 = 0;
    var v_5 : i32 = 0;
    var v_6 : f32 = 0.0;
    var v_7 : f32 = 0.0;
    var v_8 : f32 = 0.0;
    var v_9 : f32 = 0.0;
    var v_10 : f32 = 0.0;
    var v_11 : f32 = 0.0;
    var v_12 : f32 = 0.0;
    var v_13 : f32 = 0.0;
    var v_14 : i32 = 0;
    var v_15 : i32 = 0;
    var v_16 : i32 = 0;
    var v_17 : i32 = 0;
    var v_18 : f32 = 0.0;
    var v_19 : f32 = 0.0;
    var v_20 : i32 = 0;
    var v_21 : i32 = 0;
    var v_22 : i32 = 0;
    var v_23 : i32 = 0;
    var v_24 : i32 = 0;
    var v_25 : i32 = 0;
    var v_26 : i32 = 0;
    var v_27 : i32 = 0;
    var v_28 : i32 = 0;
    var v_29 : bool = false;
    var v_30 : bool = false;
    var v_31 : bool = false;
    var v_32 : bool = false;
    var v_33 : i32 = 0;
    var v_34 : i32 = 0;
    var v_35 : i32 = 0;
    var v_36 : bool = false;
    var v_37 : bool = false;
    var v_38 : bool = false;
    var v_39 : bool = false;
    var v_40 : i32 = 0;
    var v_41 : i32 = 0;
    var v_42 : i32 = 0;
    var v_43 : bool = false;
    var v_44 : bool = false;
    var v_45 : bool = false;
    var v_46 : bool = false;
    var v_47 : i32 = 0;
    var v_48 : i32 = 0;
    var v_49 : i32 = 0;
    var v_50 : bool = false;
    var v_51 : bool = false;
    var v_52 : bool = false;
    var v_53 : bool = false;
    var v_54 : bool = false;
    var v_55 : bool = false;
    var v_56 : bool = false;
    var v_57 : bool = false;
    var v_58 : f32 = 0.0;
    var v_59 : f32 = 0.0;
    var v_60 : f32 = 0.0;
    var v_61 : f32 = 0.0;
    var v_62 : f32 = 0.0;
    var v_63 : f32 = 0.0;
    var v_64 : f32 = 0.0;
    var v_65 : f32 = 0.0;
    var v_66 : f32 = 0.0;
    var v_67 : f32 = 0.0;
    var v_68 : f32 = 0.0;
    var v_69 : f32 = 0.0;
    var v_70 : f32 = 0.0;
    var v_71 : f32 = 0.0;
    var v_72 : f32 = 0.0;
    var v_73 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_73) >= _ilgpu_user_dim) { return; }
    let v_74_f0 = &param1_f0;
    var v_74_f1 = i64_from_i32(i32(arrayLength(&param1_f0)));
    let v_75_f0 = &param2_f0;
    var v_75_f1 = i64_from_i32(i32(arrayLength(&param2_f0)));
    var v_77 = bitcast<i32>(_scalar_params[1]);
    var v_78 = bitcast<i32>(_scalar_params[2]);
    var v_79 = bitcast<i32>(_scalar_params[3]);
    var v_80 = bitcast<i32>(_scalar_params[4]);
    var v_84 : f32;
    var v_87 : f32;
    var v_89 : f32;
    var v_92 : f32;
    var v_93 : i32;
    var v_94 : i32;
    var v_97 : i32;
    var v_100 : i32;
    var v_101 : i32;
    var v_102 : i32;
    var v_104 : i32;
    var v_105 : i32;
    var v_107 : i32;
    var v_108 : i32;
    var v_109 : emu_i64;
    var v_111 : emu_i64;
    var v_114 : i32;
    var v_117 : i32;
    var v_119 : i32;
    var v_122 : f32;
    var v_123 : emu_i64;
    var v_125 : emu_i64;
    var v_128 : i32;
    var v_131 : i32;
    var v_133 : i32;
    var v_136 : f32;
    var v_137 : emu_i64;
    var v_139 : emu_i64;
    var v_142 : i32;
    var v_145 : i32;
    var v_147 : i32;
    var v_150 : f32;
    var v_151 : emu_i64;
    var v_153 : emu_i64;
    var v_156 : i32;
    var v_159 : i32;
    var v_161 : i32;
    var v_164 : f32;
    var v_165 : emu_i64;
    var v_167 : emu_i64;
    var v_170 : i32;
    var v_173 : i32;
    var v_175 : i32;
    var v_178 : f32;
    var v_179 : f32;
    var v_180 : f32;
    var v_181 : f32;
    var v_83 : f32;
    var v_85 : f32;
    var v_86 : f32;
    var v_88 : f32;
    var v_90 : f32;
    var v_91 : f32;
    var v_95 : f32;
    var v_96 : f32;
    var v_98 : bool;
    var v_99 : bool;
    var v_103 : bool;
    var v_106 : bool;
    var v_110 : bool;
    var v_112 : bool;
    var v_113 : i32;
    var v_115 : bool;
    var v_116 : bool;
    var v_118 : bool;
    var v_120 : bool;
    var v_124 : bool;
    var v_126 : bool;
    var v_127 : i32;
    var v_129 : bool;
    var v_130 : bool;
    var v_132 : bool;
    var v_134 : bool;
    var v_138 : bool;
    var v_140 : bool;
    var v_141 : i32;
    var v_143 : bool;
    var v_144 : bool;
    var v_146 : bool;
    var v_148 : bool;
    var v_152 : bool;
    var v_154 : bool;
    var v_155 : i32;
    var v_157 : bool;
    var v_158 : bool;
    var v_160 : bool;
    var v_162 : bool;
    var v_166 : bool;
    var v_168 : bool;
    var v_169 : i32;
    var v_171 : bool;
    var v_172 : bool;
    var v_174 : bool;
    var v_176 : bool;















































    let v_81 = v_74_f0;
    let v_82 = v_75_f0;

    v_0 = v_74_f1;

    v_1 = v_75_f1;
    v_2 = v_73 % v_80;
    v_3 = v_73 / v_80;
    v_4 = v_3 % v_79;
    v_5 = v_3 / v_79;
    v_83 = f32(v_4);
    v_84 = f32(0.5);
    v_6 = v_83 + v_84;
    v_85 = f32(v_77);
    v_7 = v_6 * v_85;
    v_86 = f32(v_79);
    v_8 = v_7 / v_86;
    v_87 = f32(0.5);
    v_9 = v_8 - v_87;
    v_88 = f32(v_2);
    v_89 = f32(0.5);
    v_10 = v_88 + v_89;
    v_90 = f32(v_78);
    v_11 = v_10 * v_90;
    v_91 = f32(v_80);
    v_12 = v_11 / v_91;
    v_92 = f32(0.5);
    v_13 = v_12 - v_92;
    v_14 = i32(v_9);
    v_93 = i32(1);
    v_15 = v_14 + v_93;
    v_16 = i32(v_13);
    v_94 = i32(1);
    v_17 = v_16 + v_94;
    v_95 = f32(v_14);
    v_18 = v_9 - v_95;
    v_96 = f32(v_16);
    v_19 = v_13 - v_96;
    v_97 = i32(0);
    v_98 = v_14 >= v_97;
    if (!v_98) {
        v_20 = i32(0);
        v_21 = v_20;
    } else {
        v_21 = v_14;
    }
    v_99 = v_15 < v_77;
    v_100 = i32(1);
    v_22 = v_77 - v_100;
    v_101 = select(v_22, v_15, v_99);
    v_102 = i32(0);
    v_103 = v_16 >= v_102;
    v_104 = i32(0);
    v_105 = select(v_104, v_16, v_103);
    v_106 = v_17 < v_78;
    v_107 = i32(1);
    v_23 = v_78 - v_107;
    v_108 = select(v_23, v_17, v_106);
    v_24 = v_5 * v_77;
    v_25 = v_24 * v_78;
    v_26 = v_21 * v_78;
    v_27 = v_25 + v_26;
    v_28 = v_27 + v_105;
    v_109 = _c_i64_0;
    v_110 = i64_ge(v_0, v_109);
    v_111 = _c_i64_1;
    v_112 = i64_le(v_0, v_111);
    v_29 = v_110 & v_112;
    v_113 = i64_to_i32(v_0);
    v_114 = i32(0);
    v_115 = v_28 >= v_114;
    v_116 = v_28 < v_113;
    v_30 = v_115 & v_116;
    v_117 = i32(0);
    v_118 = v_28 == v_117;
    v_119 = i32(0);
    v_120 = v_113 == v_119;
    v_31 = v_118 & v_120;
    v_32 = v_30 | v_31;
    let v_121 = &param1_f0[(i32(_scalar_params[5]) + v_28)];
    v_122 = *v_121;
    v_33 = v_21 * v_78;
    v_34 = v_25 + v_33;
    v_35 = v_34 + v_108;
    v_123 = _c_i64_0;
    v_124 = i64_ge(v_0, v_123);
    v_125 = _c_i64_1;
    v_126 = i64_le(v_0, v_125);
    v_36 = v_124 & v_126;
    v_127 = i64_to_i32(v_0);
    v_128 = i32(0);
    v_129 = v_35 >= v_128;
    v_130 = v_35 < v_127;
    v_37 = v_129 & v_130;
    v_131 = i32(0);
    v_132 = v_35 == v_131;
    v_133 = i32(0);
    v_134 = v_127 == v_133;
    v_38 = v_132 & v_134;
    v_39 = v_37 | v_38;
    let v_135 = &param1_f0[(i32(_scalar_params[5]) + v_35)];
    v_136 = *v_135;
    v_40 = v_101 * v_78;
    v_41 = v_25 + v_40;
    v_42 = v_41 + v_105;
    v_137 = _c_i64_0;
    v_138 = i64_ge(v_0, v_137);
    v_139 = _c_i64_1;
    v_140 = i64_le(v_0, v_139);
    v_43 = v_138 & v_140;
    v_141 = i64_to_i32(v_0);
    v_142 = i32(0);
    v_143 = v_42 >= v_142;
    v_144 = v_42 < v_141;
    v_44 = v_143 & v_144;
    v_145 = i32(0);
    v_146 = v_42 == v_145;
    v_147 = i32(0);
    v_148 = v_141 == v_147;
    v_45 = v_146 & v_148;
    v_46 = v_44 | v_45;
    let v_149 = &param1_f0[(i32(_scalar_params[5]) + v_42)];
    v_150 = *v_149;
    v_47 = v_101 * v_78;
    v_48 = v_25 + v_47;
    v_49 = v_48 + v_108;
    v_151 = _c_i64_0;
    v_152 = i64_ge(v_0, v_151);
    v_153 = _c_i64_1;
    v_154 = i64_le(v_0, v_153);
    v_50 = v_152 & v_154;
    v_155 = i64_to_i32(v_0);
    v_156 = i32(0);
    v_157 = v_49 >= v_156;
    v_158 = v_49 < v_155;
    v_51 = v_157 & v_158;
    v_159 = i32(0);
    v_160 = v_49 == v_159;
    v_161 = i32(0);
    v_162 = v_155 == v_161;
    v_52 = v_160 & v_162;
    v_53 = v_51 | v_52;
    let v_163 = &param1_f0[(i32(_scalar_params[5]) + v_49)];
    v_164 = *v_163;
    v_165 = _c_i64_0;
    v_166 = i64_ge(v_1, v_165);
    v_167 = _c_i64_1;
    v_168 = i64_le(v_1, v_167);
    v_54 = v_166 & v_168;
    v_169 = i64_to_i32(v_1);
    v_170 = i32(0);
    v_171 = v_73 >= v_170;
    v_172 = v_73 < v_169;
    v_55 = v_171 & v_172;
    v_173 = i32(0);
    v_174 = v_73 == v_173;
    v_175 = i32(0);
    v_176 = v_169 == v_175;
    v_56 = v_174 & v_176;
    v_57 = v_55 | v_56;
    let v_177 = &param2_f0[(i32(_scalar_params[6]) + v_73)];
    v_178 = f32(1.0);
    v_58 = v_178 - v_18;
    v_59 = v_122 * v_58;
    v_179 = f32(1.0);
    v_60 = v_179 - v_19;
    v_61 = v_59 * v_60;
    v_180 = f32(1.0);
    v_62 = v_180 - v_18;
    v_63 = v_136 * v_62;
    v_64 = v_63 * v_19;
    v_65 = v_61 + v_64;
    v_66 = v_150 * v_18;
    v_181 = f32(1.0);
    v_67 = v_181 - v_19;
    v_68 = v_66 * v_67;
    v_69 = v_65 + v_68;
    v_70 = v_164 * v_18;
    v_71 = v_70 * v_19;
    v_72 = v_69 + v_71;
    *v_177 = v_72;
    return;
}
