// Kernel: AddKernel
// Workgroup: 64
// SharedMem: 0B
// Bindings: 4
// Time: 2026-03-24T00:45:23.4680000Z

// Kernel: AddKernel
//
// Generated by SpawnDev.ILGPU.WebGPU v2.0.0
//

// Kernel: AddKernel_2
// WorkgroupSize: 64


override _ilgpu_user_dim : u32 = 4294967295u;

// Param 1: View<Int32, Generic> (Element: Int32)
@group(0) @binding(0) var<storage, read_write> param1 : array<i32>;
// Param 2: View<Int32, Generic> (Element: Int32)
@group(0) @binding(1) var<storage, read_write> param2 : array<i32>;
// Param 3: View<Int32, Generic> (Element: Int32)
@group(0) @binding(2) var<storage, read_write> param3 : array<i32>;
// View offset for param1 at scalar slot 0
// View offset for param2 at scalar slot 1
// View offset for param3 at scalar slot 2
@group(0) @binding(3) var<storage, read> _scalar_params : array<u32>;

const workgroup_size : vec3<u32> = vec3<u32>(64u, 1u, 1u);

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) _ep_global_id : vec3<u32>, @builtin(local_invocation_id) _ep_local_id : vec3<u32>, @builtin(workgroup_id) _ep_group_id : vec3<u32>, @builtin(num_workgroups) _ep_num_workgroups : vec3<u32>, @builtin(local_invocation_index) _ep_local_index : u32) {
    // All builtins use 'let' (not var<private>) for WGSL uniformity analysis.
    // 'let' preserves uniformity tracking from @builtin parameters.
    let global_id = _ep_global_id;
    let local_id = _ep_local_id;
    let group_id = _ep_group_id;
    let num_workgroups = _ep_num_workgroups;
    let local_index = _ep_local_index;

    var v_0 : i32 = 0;
    var v_1 : i32 = i32(local_index + (group_id.x + group_id.y * num_workgroups.x) * workgroup_size.x);
    if (u32(v_1) >= _ilgpu_user_dim) { return; }
    let v_2 = &param1;
    let v_3 = &param2;
    let v_4 = &param3;
    let v_5 = &param1[(i32(_scalar_params[0]) + v_1)];
    let v_6 = &param2[(i32(_scalar_params[1]) + v_1)];
    var v_7 : i32;
    v_7 = *v_6;
    let v_8 = &param3[(i32(_scalar_params[2]) + v_1)];
    var v_9 : i32;
    v_9 = *v_8;
    v_0 = v_7 + v_9;
    *v_5 = v_0;
        return;
}
